### PR TITLE
fix: remove anchor tags from cookie banner affecting lighthouse score

### LINKED ISSUE #6882: [Lighthouse] - Update cookie banner to not use anchor links for accept/decline
Cookie banner is using anchor links for accept/decline buttons and is affecting the lighthouse score.

## Screenshot 📸
image

image

image

### PR DESCRIPTION
**Pull request by thnaylor**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #6882 
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [ ] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=123PCJXhjb15i6JwVVRGd7KvN2sSNZrtPjr5doJq9oWctoTt)

## Comments
Cookie banner pops up during lighthouse testing causing non crawlable links error. Since I had it saved my tests on #6844 did not take it into account.

Lets pretend this was part of  #6844 for my own sanity 🤣 🤣 

### <samp>🤖 Generated by Copilot at 4db31c1</samp>

Improved cookie banner component by using `<span>` tags instead of `<a>` tags in `components/CookieBanner.vue`. This prevents unwanted page navigation and enhances accessibility.

### <samp>🤖 Generated by Copilot at 4db31c1</samp>

> _`<a>` tags are gone_
> _`<span>` tags improve the banner_
> _Autumn leaves don't fall_

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
would it be possible to use `NeoButton` variant `text` instead?

**Comment by thnaylor** [comment]
@roiLeo 

> would it be possible to use `NeoButton` variant `text` instead?

Working like a charm 😄 Thanks

image

File: components/CookieBanner.vue [hunk 1]
```diff
@@ -48,6 +53,8 @@ const declineCookies = () => {
 </script>
 
 <style lang="scss">
+@import '@/styles/abstracts/variables';
+
```
Comment (roiLeo) [inline components/CookieBanner.vue:57]:
```suggestion
```

not needed

**Review by roiLeo — APPROVED** [review]

**Review by Jarsen136 — APPROVED** [review]

**Comment by yangwao** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 4.42 USD/DOT ~ 4.525 $DOT
🧗 [123PCJXhjb15i6JwVVRGd7KvN2sSNZrtPjr5doJq9oWctoTt](https://polkadot.subscan.io/account/123PCJXhjb15i6JwVVRGd7KvN2sSNZrtPjr5doJq9oWctoTt)
🔗 [0x12848f6957302508672f8f0239213c9a769f5f1b3dcc12f3ee43a416b7700be1](https://polkadot.subscan.io/extrinsic/0x12848f6957302508672f8f0239213c9a769f5f1b3dcc12f3ee43a416b7700be1)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
