### PR TITLE
fix: drop modal bugs

### LINKED ISSUE #8483: Seems after countdown of 2 minutes gone, empty art rendered
image

image

and [ List NFT ] button was disabled, however managed to click on it

### LINKED ISSUE #8485: Drop asked me to subscribe again
https://github.com/kodadot/nft-gallery/assets/36627808/8685116b-d64b-43ae-b3f2-2778ad90ff82

nft was minted properly tho

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #8483
- add: Multiple retries when preloading nft cover

- [x] Closes #8485
- ref: modal steps will not move back to email step if count goes to 0 seconds  

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

https://github.com/kodadot/nft-gallery/assets/44554284/392e1640-577c-4571-9281-aebdcf003fdf

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at ebb8a1a</samp>

Refactored the drop confirmation modal to use a more declarative approach with a `modalStep` ref and watch effects. Improved the error handling and performance of the NFT image preloading by using the `error` event and rejecting the promise in `preloadImage`.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at ebb8a1a</samp>

> _To show off an NFT in a modal_
> _We preload the image with a portal_
> _But if there's an `error`_
> _We don't want to terror_
> _So we reject the promise as normal_

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]

**Comment by prury** [comment]
asking again for subscription problem only truly happened when drop went live, lets see! 

minting process: 

https://github.com/kodadot/nft-gallery/assets/36627808/99e3bbc4-4ad7-4788-8b39-a75250b03859

**Comment by hassnian** [comment]
> asking again for subscription problem only truly happened when drop went live, lets see! 
> 
> 
> 
> minting process: 
> 
> 
> 
> https://github.com/kodadot/nft-gallery/assets/36627808/99e3bbc4-4ad7-4788-8b39-a75250b03859
> 
> 
> 
> 

that's https://github.com/kodadot/nft-gallery/issues/8371

File: components/collection/drop/modal/DropConfirmModal.vue [hunk 1]
```diff
@@ -106,9 +115,37 @@ watch(
...
 })
+
+watch(
+  () => props.modelValue,
+  (isOpen) => {
+    if (isOpen) {
+      modalStep.value = 'email'
+    }
+  },
+)
```
Comment (daiagi) [inline components/collection/drop/modal/DropConfirmModal.vue:150]: i think it would be more concise if you used a single watchEffect

File: components/collection/drop/modal/DropConfirmModal.vue [hunk 2]
```diff
@@ -34,6 +36,8 @@ import {
   useCountDown,
 } from '@/components/collection/unlockable/utils/useCountDown'
 
+type ModalStep = 'email' | 'claiming' | 'succeded'
```
Comment (daiagi) [inline components/collection/drop/modal/DropConfirmModal.vue:39]: the code will have less "free roaming" strings around if you would used an enum...

**Review by daiagi — APPROVED** [review]
looks good overall
some minor code style suggestions

File: components/collection/drop/modal/DropConfirmModal.vue (hunk 1 above)
Comment (hassnian) [reply components/collection/drop/modal/DropConfirmModal.vue]: fixed

File: components/collection/drop/modal/DropConfirmModal.vue (hunk 2 above)
Comment (hassnian) [reply components/collection/drop/modal/DropConfirmModal.vue]: fixed

**Comment by hassnian** [comment]
https://github.com/kodadot/nft-gallery/assets/44554284/537ebca9-04c7-4690-b149-df3bf82b1caf


https://github.com/kodadot/nft-gallery/assets/44554284/dc5d6996-e609-48bb-b67b-76197338db3e

**Comment by vikiival** [comment]
@hassnian Is it good to go?

**Comment by hassnian** [comment]
> @hassnian Is it good to go?

almost done

**Comment by hassnian** [comment]
> > @hassnian Is it good to go?
> 
> almost done

oh nevermind wrong pr I thought you meant the pr review that you requested :d 

this is ready

**Comment by vikiival** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 7.49 USD/DOT ~ 2.67 $DOT
🧗 [13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh](https://polkadot.subscan.io/account/13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)
🔗 [0xf6b2dbc5eb2a19b345064543f172d0b555722b9be44b15af88054b9f282ef5ed](https://polkadot.subscan.io/extrinsic/0xf6b2dbc5eb2a19b345064543f172d0b555722b9be44b15af88054b9f282ef5ed)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
