### PR TITLE
fix: Disable RMRK/KSM

### LINKED ISSUE #9937: Disable RMRK/KSM
### What happened?

Context is here - https://github.com/kodadot/rubick/issues/283

### Please reproduce in steps

1. Do any operation on ksm/rmrk
2. Changes are not reflected

### Expected Behavior

1. Make sure that minting is disabled on rmrk / ksm
2. Make sure that any operations (buy, list, send) are disabled 

### What browsers are you seeing the problem on?

_No response_

### At which address did you encounter bug?

_No response_

### Are you logged in?

None

### Which wallet you are using?

_No response_

### Screenshots

```
sqd:processorHttpError: Got 404 from https://kusama.archive.subsquid.io/graphql
```

### Relevant log output

_No response_

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #9937

- Display warning toast and prevent the transaction for all operations on  rmrk\ksm, expect for balance transfer
- hide/disabled button for actions on rmrk\ksm

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed UI

image

### CODE REVIEW

File: components/common/IdentityForm.vue
Comment (vikiival) [inline components/common/IdentityForm.vue:1]: Identity has nothing to do With our indexer

File: components/migrate/steps/SignLoader1.vue [hunk 1]
```diff
@@ -114,6 +115,11 @@ const fromCollection = collections.value.find(
 )
 
 const startStep1 = async () => {
+  if (disabledOperationPrefixes(from)) {
```
Comment (vikiival) [inline components/migrate/steps/SignLoader1.vue:118]: What is step 1

**Review by vikiival — CHANGES_REQUESTED** [review]
Identity has nothing to do with indexer.

The error is confusing, prefer to hide / disable buttons

File: components/migrate/steps/SignLoader1.vue (hunk 1 above)
Comment (Jarsen136) [reply components/migrate/steps/SignLoader1.vue:118]: step1
image

I'm thinking about whether we should disable the `/migrate` page as they are only for `rmrk/ksm`

Comment (vikiival) [reply components/migrate/steps/SignLoader1.vue:118]: > I'm thinking about whether we should disable the /migrate page

yup

File: components/common/IdentityForm.vue
Comment (Jarsen136) [reply components/common/IdentityForm.vue:1]: updated

**Comment by Jarsen136** [comment]
> Identity has nothing to do with indexer.
> 
> The error is confusing, prefer to hide / disable buttons

✅ Done

File: utils/prefix.ts [hunk 2]
```diff
@@ -20,3 +20,6 @@ export function isRemark(prefix: string): boolean {
 
 export const hasMarketplace = (prefix: string): boolean =>
   ['rmrk', 'ksm', 'ahp', 'ahk'].includes(prefix)
+
+export const disabledOperationPrefixes = (prefix: string): boolean =>
```
Comment (hassnian) [inline utils/prefix.ts:24]: since it returns a boolean I would rather do`hasOperationsDisabled = (prefix: string): boolean`  or `hasPrefixOperationsDisabled`

Comment (Jarsen136) [reply utils/prefix.ts]: updated

**Review by hassnian — APPROVED** [review]

File: components/migrate/steps/SignLoader1.vue (hunk 1 above)
Comment (hassnian) [reply components/migrate/steps/SignLoader1.vue]: @Jarsen136 is this implemented ?

**Review by hassnian — APPROVED** [review]

**Comment by prury** [comment]
with firesquid gone, it means migration also will not be possible?

**Comment by Jarsen136** [comment]
> with firesquid gone, it means migration also will not be possible?

Yes https://github.com/kodadot/nft-gallery/pull/9944#discussion_r1545372754

**Review by daiagi — APPROVED** [review]

**Review by vikiival — APPROVED** [review]
Not best, but doable

**Comment by prury** [comment]
@Jarsen136 please resolve conversations

**Comment by prury** [comment]
@yangwao payment

**Comment by prury** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 8.63 USD/DOT ~ 3.476 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x0b6a35c9dff47be1721242a535899f391f1ac73e08910e3677abb3c6891213df](https://polkadot.subscan.io/extrinsic/0x0b6a35c9dff47be1721242a535899f391f1ac73e08910e3677abb3c6891213df)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
