### PR TITLE
fix: Missing NFT #serial numbers when listing

### LINKED ISSUE #9734: Missing NFT #serial numbers when listing
should show name followed by serial number(also happens to NFTs that are not genart)

312108020-5954e467-8f97-4f6e-958a-256ac651279f

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #9734

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image

  ## Copilot Summary
  copilot:summary

  copilot:poem

### CODE REVIEW

File: components/common/shoppingCart/types.ts [hunk 1]
```diff
@@ -17,4 +17,5 @@ export type ShoppingCartItem = {
   addedAt: number
   meta?: NFTMetadata
   metadata: string
+  sn: string
```
Comment (daiagi) [inline components/common/shoppingCart/types.ts:20]: are we sure nothing breaks by adding this non optional field?

**Review by daiagi — APPROVED** [review]

**Comment by yangwao** [comment]
thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 11.75 USD/DOT ~ 1.702 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0xc35b60c6774906a4c9309e84c7b8d57397a1f7fda474124c77109f2153f5fbfe](https://polkadot.subscan.io/extrinsic/0xc35b60c6774906a4c9309e84c7b8d57397a1f7fda474124c77109f2153f5fbfe)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
