### PR TITLE
fix(drop): nft overlap for same user

### LINKED ISSUE #8961: Stacked cards with and without generative art tag
https://kodadot.xyz/ahp/u/1KxzJHoRJHi8EgWVhrGDueeyzg8PyihAvSL3NP6QMcxEve6

What's the difference between left and right

image

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #8961

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [ ] My fix has changed **something** on UI;

### CODE REVIEW

File: components/collection/drop/GenerativePreview.vue [hunk 1]
```diff
@@ -60,10 +61,17 @@ const emit = defineEmits(['select'])
...
+const entropyRange = computed<[number, number]>(() => [
+  STEP * props.minted,
+  STEP * (props.minted + 1),
+])
+
 const getHash = (isDefault?: boolean) => {
   const ss58Format = isDefault
     ? chainProperties.value?.ss58Format
-    : getRandomInt(15000)
+    : getRandomIntFromRange(entropyRange.value[0], entropyRange.value[1])
```
Comment (Jarsen136) [inline components/collection/drop/GenerativePreview.vue:73]: `chainProperties.value?.ss58Format` How about the default one? It should be also in the available range.

Comment (hassnian) [reply components/collection/drop/GenerativePreview.vue:73]: CleanShot 2024-01-13 at 08 17 50@2x

first entropyRange `[ 0, 64 ]` includes 0 and 2 which are the default ones for `ahp` and `ahk`

Comment (Jarsen136) [reply components/collection/drop/GenerativePreview.vue:73]: I would use `entropyRange.value[0]` as the default value to avoid duplicate items minted by a user.

Comment (hassnian) [reply components/collection/drop/GenerativePreview.vue:73]: but isn't it the same ?

ahp drop -> ss58Format is 0  and the first range is `[ 0, 64 ]` which has 0 , second range will not have 0 anymore, how do you get a duplicate by the same user ?

ahk same here it's 2 part of the first range after that you can't get 2 anymore 

I have no issue with making the change, but I don't see how you can get a duplicate with this code

Comment (Jarsen136) [reply components/collection/drop/GenerativePreview.vue:73]: > ahp drop -> ss58Format is 0 and the first range is [ 0, 64 ] which has 0 , second range will not have 0 anymore, how do you get a duplicate by the same user ?

There is a case that a user could make the same drops.
If the user does not click the "Generative New" button, he will always get the drop with the default ss58Format value, which is zero. That means he could get the same drops as much as he wants. wdyt ?

Comment (hassnian) [reply components/collection/drop/GenerativePreview.vue]: yep, absolulty 

updated the code https://github.com/kodadot/nft-gallery/pull/8967/commits/e37f3364bd7dda5b7bbd76b50fac0129750c9750

**Review by Jarsen136 — APPROVED** [review]

**Review by preschian — APPROVED** [review]

**Comment by vikiival** [comment]
@yangwao yolo or after drop?

**Comment by yangwao** [comment]
> olo or after drop?

@vikiival what can go wrong

**Comment by vikiival** [comment]
> @vikiival what can go wrong, not urgent, however important

depends if the calculation is done correctly :)
Because currently calculation works very bad.

**Comment by vikiival** [comment]
Good but it still does not prevent @yangwao to mint 0 / same pieces

```ts
const getHash = (isDefault?: boolean) => {
// rest could be ok
  const initialValue = accountId.value ? encodeAddress(accountId.value, ss58Format) : Date.now() << ss58Format // I do not have better entropy rn 
  return blake2AsHex(initialValue, 256, null, true)
}
```

**Comment by vikiival** [comment]
Guess @prury is OOO, 
@yangwao can you try ?

**Comment by vikiival** [comment]
Yolo hope this wont break anything
