### PR TITLE
fix: Unlockable change text in How unlockable item works

### LINKED ISSUE #6171: Unlockable: change text in How unlockable item works
I think we should change text, will make follow up issue

@justluu can drop some text

**Learn more** button can go to the 
- https://hello.kodadot.xyz/fandom-toolbox/audience-growth/unlockables

image

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/6165#issuecomment-1578464318_

### PR DESCRIPTION
**Pull request by Jarsen136**
closed #6171 

image

### CODE REVIEW

File: components/collection/unlockable/UnlockableContainer.vue [hunk 1]
```diff
@@ -131,12 +131,22 @@
...
+            you don't miss this!
           </div>
-          <NeoButton variant="unlockable" class="mt-2"> Learn More </NeoButton>
+          <a
+            href="https://hello.kodadot.xyz/fandom-toolbox/audience-growth/unlockables"
+            target="_blank">
+            <NeoButton variant="unlockable" class="mt-2">
+              Learn More
+            </NeoButton>
+          </a>
```
Comment (roiLeo) [inline components/collection/unlockable/UnlockableContainer.vue:149]: maybe use `tag="nuxt-link"` & `to="https://hello.kodadot.xyz/fandom-toolbox/audience-growth/unlockables"` on `<NeoButton />`

**Review by roiLeo — APPROVED** [review]

File: components/collection/unlockable/UnlockableContainer.vue (hunk 1 above)
Comment (yangwao) [reply components/collection/unlockable/UnlockableContainer.vue:149]: continue to 
- https://github.com/kodadot/nft-gallery/issues/6163
- speedrun MODE ON
