### PR TITLE
fix: listing cart

### LINKED ISSUE #7484: listing cart bug
1. add some item to listing cart

image

2. click clear all 
image

3. again , add some item to listing cart
4. click select all

Nothing is added to listing cart!!

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #7484

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

### <samp>🤖 Generated by Copilot at 001d62e</samp>

Renamed `listingCartStore.clear` method to `listingCartStore.clearListedItems` and updated its references in `ListingCartMini.vue` and `ListingCartModal.vue`. The new method removes all items from the listing cart state and local storage.

### <samp>🤖 Generated by Copilot at 001d62e</samp>

> _`clearListedItems`_
> _A new name for the method_
> _Cart is empty now_

### CODE REVIEW

File: stores/listingCart.ts [hunk 1]
```diff
@@ -86,6 +86,11 @@ export const useListingCartStore = defineStore('listingCart', {
         localStorage.value = this.items
       }
     },
+
```
Comment (roiLeo) [inline stores/listingCart.ts:89]:
```suggestion
```

File: components/common/listingCart/ListingCartMini.vue [hunk 2]
```diff
@@ -14,7 +14,7 @@
               class="has-text-grey selection-button"
               variant="text"
               no-shadow
-              @click.native="listingCartStore.clear">
+              @click.native="listingCartStore.clearListedItems">
```
Comment (roiLeo) [inline components/common/listingCart/ListingCartMini.vue:17]:
```suggestion
              @click="listingCartStore.clearListedItems">
```

**Review by roiLeo — APPROVED** [review]

**Review by preschian — APPROVED** [review]

**Review by roiLeo — APPROVED** [review]
