### PR TITLE
Fix nft details in carousel

### LINKED ISSUE #4169: Item/Video on landing doesn't show but it does shows on item detail
This is quite weird that it shows on item but not on carousel? 

https://user-images.githubusercontent.com/5887929/197585609-3ab1e33d-8237-4ed1-9f82-253fe1679e48.mov

### PR DESCRIPTION
**Pull request by shashkovdanil**
**Important!**

This fix works well, but it's temporary. The backend developers need to figure out why the metadata is empty for some NFTs.

## PR Type

Bugfix

## Context

- [x] Related #4169 

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer?target=bXn3ExwLs8rpcpknp9wNqnNVgEYVLnTtFPDrJtaPHYds7Vfjv&usdamount=0&donation=true)

## Screenshot 📸
https://monosnap.com/file/jNQh60q7PLkfXgzjKY3JPLiPF5Zsjb

### CODE REVIEW

**Comment by yangwao** [comment]
> The backend developers need to figure out why the metadata is empty for some NFTs.

I would check here?
- https://github.com/kodadot/snek/issues/102

**Comment by shashkovdanil** [comment]
> > The backend developers need to figure out why the metadata is empty for some NFTs.
> 
> 
> 
> I would check here?
> 
> - https://github.com/kodadot/snek/issues/102

Yep, that's it. I would look at it myself, but I'm afraid I don't have enough experience to figure it out on my own in a normal amount of time.

**Review by roiLeo — COMMENTED** [review]
> Here's the issue category breakdown:
> Category 	Count
> Complexity 	1

Could you find a way to reduce numbers of line for `formatNFT` method?

**Comment by shashkovdanil** [comment]
@roiLeo think I can, but it will make the code unreadable. GitHub shows that I made many changes because I wrapped `data.map` in `Promise.all(data.map)`. In fact my changes are:

```js
if (metaImage === null) {
  const cachedMeta = await get(nft.metadata)
  const meta = !isEmpty(cachedMeta)
    ? cachedMeta
    : await fetchNFTMetadata(
        nft,
        getSanitizer(nft.metadata, 'pinata', 'permafrost')
      )
  const imageSanitizer = getSanitizer(meta.image, 'pinata')

  return {
    ...result,
    name: meta.name,
    image: imageSanitizer(meta.image),
    animation_url: sanitizeIpfsUrl(
      meta.animation_url || meta.image,
      'pinata'
    ),
  }
}
```

File: utils/carousel.ts [hunk 1]
```diff
@@ -1,4 +1,6 @@
 import { formatDistanceToNow } from 'date-fns'
+import { get } from 'idb-keyval'
```
[the remark this answers is not in the document]
Comment (shashkovdanil) [reply utils/carousel.ts:2]: We will send more unnecessary requests instead of taking data from cache. So it doesn't make any sense (only to reduce count of changed lines)

**Comment by shashkovdanil** [comment]
@roiLeo any updates?

File: utils/carousel.ts [hunk 2]
```diff
@@ -25,24 +31,49 @@ export const formatNFT = async (
...
+          name: meta.name,
+          image: imageSanitizer(meta.image),
+          animation_url: sanitizeIpfsUrl(
+            meta.animation_url || meta.image,
+            'pinata'
+          ),
+        }
+      }
+
+      return result
```
[the remark this answers is not in the document]
Comment (shashkovdanil) [reply utils/carousel.ts:74]: Hey, yes, I can

**Review by roiLeo — COMMENTED** [review]
> set in idb new meta val if present

missing setter for idb storage
```js
if (!cachedMeta) {
  set(nft.metadata, meta)
}
```

**Comment by shashkovdanil** [comment]
> > set in idb new meta val if present
> 
> missing setter for idb storage
> 
> ```js
> if (!cachedMeta) {
>   set(nft.metadata, meta)
> }
> ```

Done

File: utils/carousel.ts [hunk 3]
```diff
@@ -45,6 +51,36 @@ export const formatNFT = async (
   })
 }
 
+export const setNftMetaFromCache = async (nfts): Promise<CarouselNFT[]> => {
+  return await Promise.all(
```
Comment (roiLeo) [inline utils/carousel.ts:55]: do we still need to keep Promise.all?

File: components/carousel/utils/useCarousel.ts [hunk 4]
```diff
@@ -140,7 +144,10 @@ export const useCarouselRelated = ({ collectionId }) => {
 
   watch(data, async () => {
     if (data.value) {
-      nfts.value = await formatNFT((data.value as Collections).collection?.nfts)
+      const collection = await formatNFT(
```
Comment (roiLeo) [inline components/carousel/utils/useCarousel.ts:147]: I would replace "const collection" with something more meaningful as it does not contain the collection data but rather the nfts.

**Review by roiLeo — COMMENTED** [review]
rest looks good to me

File: utils/carousel.ts (hunk 3 above)
Comment (shashkovdanil) [reply utils/carousel.ts:55]: Yes, because we need array of NFT in `useCarousel`. It will be array of promises without `Promise.all`

File: components/carousel/utils/useCarousel.ts (hunk 4 above)
Comment (shashkovdanil) [reply components/carousel/utils/useCarousel.ts:147]: Yep, you're right, it's not collection, it's list of relation NFTs for carousel

**Review by roiLeo — APPROVED** [review]
✅ code lgtm

**Comment by shashkovdanil** [comment]
Can it be merged?

**Comment by shashkovdanil** [comment]
cc @roiLeo @preschian

**Comment by roiLeo** [comment]
It need 2nd approval to merge this, Team is currently busy with ongoing event.
In the meantime feel free to take another issue

**Comment by yangwao** [comment]
> Team is currently busy with ongoing event.

**Comment by yangwao** [comment]
pay 60 usd 

> Team is currently busy with ongoing event.

Yes, we are again in Lisbon. 
If you want to come over to Polkadot barcamp today/tmrw, you are welcome! 
- https://incongruous-riverbed-10f.notion.site/Polkadot-Summit-Barcamp-ffbadaef52574e4db8bab53d9e9d50b4
