### PR TITLE
fix: Button size in create new profile

### LINKED ISSUE #10216: Button size in create new profile
there are two options:
- start fresh, edit 
- farcaster auth 

image

this buttons should look a bit different 

image
- main thing is size large 

added hover state for the farcaster button: 

image

hover is easy, just put the background color there

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #10216

goes after #10195
#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Review by daiagi — APPROVED** [review]

File: components/profile/create/stages/Select.vue [hunk 1]
```diff
@@ -23,8 +24,8 @@
     <NeoButton
       expanded
       no-shadow
-      :label="hasProfile ? 'Edit Profile' : 'Start Fresh'"
-      class="h-14"
+      size="large"
+      :label="hasProfile ? $t('profile.editProfile') : 'Start Fresh'"
```
Comment (hassnian) [inline components/profile/create/stages/Select.vue:28]: translation key for `Start Fresh`

Comment (Jarsen136) [reply components/profile/create/stages/Select.vue]: updated

**Review by hassnian — APPROVED** [review]
