### PR TITLE
fix: Ux friendly cookie popup mobile

### LINKED ISSUE #9963: Ux friendly cookie popup mobile
image

lets make it more user friendly with bigger touchpoints (especially on mobile) 
- the popup is bigger on mobile

image

Design updated in handoff - small things 

https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=1287-18959&mode=design&t=JTxokJYTnjv14c3Z-11

utilizing our secondary rounded button from component page https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=5311-18771&mode=design&t=JTxokJYTnjv14c3Z-11

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [x] Refactoring

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #9963

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

image

### CODE REVIEW

File: components/CookieBanner.vue [hunk 1]
```diff
@@ -5,23 +5,25 @@
...
             {{ $t('cookies.notice') }}, see
             <nuxt-link to="/cookie-notice" target="_blank" class="is-underlined"
               >Cookie Policy</nuxt-link
             >
             for details.
           </div>
-          <div class="bar ml-4 mr-4" />
-          <div class="action is-success">
+          <div
+            class="bg-separator-line-color ml-4 mr-4 my-4 md:!my-0 !w-full !h-[1px] md:!w-[1px] md:!h-[13px]" />
```
Comment (hassnian) [inline components/CookieBanner.vue:17]: `ml-4 mr-4 my-4` m-4 ?

checked and  the important here`md:!my-0` seems to be needed.

but the others `w-full h-[1px] md:w-[1px] md:!h-[13px]` seem to work as expect without `!` 

pls remove any important if they are not needed.

Comment (Jarsen136) [reply components/CookieBanner.vue]: > `ml-4 mr-4 my-4` m-4 ?
> 
updated


> checked and the important here`md:!my-0` seems to be needed.
> 
> but the others `w-full h-[1px] md:w-[1px] md:h-[13px]` seem to work as expect without `!`
> 
> pls remove any important if they are not needed.

It's not needed if there is only tailwind, but now there are some side effects from Bulma styles..

Comment (hassnian) [reply components/CookieBanner.vue]: > > `ml-4 mr-4 my-4` m-4 ?
> 
> updated
> 
> > checked and the important here`md:!my-0` seems to be needed.
> > but the others `w-full h-[1px] md:w-[1px] md:h-[13px]` seem to work as expect without `!`
> > pls remove any important if they are not needed.
> 
> It's not needed if there is only tailwind, but now there are some side effects from Bulma styles.. It dose not work as expected without `!`

yep I'm aware of that, it's pretty annoying, I've encountered those pretty often when adding any  `margin` or `padding`   classes , it forces you to use `!` otherwise it ends up using the bulma class.

**Review by hassnian — APPROVED** [review]

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 8.53 USD/DOT ~ 3.517 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x62a1a3a8e6c291ba0bab464f82d90968ce88332b93a9a1650bdcd5948e19f35a](https://polkadot.subscan.io/extrinsic/0x62a1a3a8e6c291ba0bab464f82d90968ce88332b93a9a1650bdcd5948e19f35a)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
