### PR TITLE
fix: preheat wrong file

### LINKED ISSUE #8052: missing image after minting
image

recently I've seen a few times that the image is missing after minting

refreshing usually (but not always) solves it
yet is a bad minting experience

## Reproduce:

Mint anything 
seen on AHK

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #8052

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)

## Screenshot 📸

- [ ] My fix has changed UI

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 081436e</samp>

Fixed IPFS preheating bug and improved logging in `utils/ipfs.ts`. Used `ipfsUrlPrefix` variable to build IPFS URLs and changed log level to error for failures.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 081436e</samp>

> _`preheatFileFromIPFS`_
> _uses `ipfsUrlPrefix` now_
> _bug is fixed - autumn_

### CODE REVIEW

**Comment by preschian** [comment]
@daiagi After some checking, it was preheat the wrong file. Previously, it would always throw 500 on the preheat session

If it still doesn't work, we need to find another alternative.

**Review by daiagi — APPROVED** [review]

File: utils/ipfs.ts [hunk 1]
```diff
@@ -155,16 +155,14 @@ export const fetchCollectionMetadata = (
...
-  api(url)
-    .then(async () => {
-      consola.log(`[PREHEAT] ${hash}`)
+  const url = sanitizeIpfsUrl(`${ipfsUrlPrefix}${ipfsUrl}`)
 
-      // preheat to r2/cfi
-      await $fetch(hash)
-    })
-    .catch((err) => consola.warn(`[PREHEAT] ${hash} ${err.message}`))
+  console.log('start preheatFileFromIPFS', url, ipfsUrl)
```
Comment (roiLeo) [inline utils/ipfs.ts:160]:
```suggestion
```

**Review by roiLeo — APPROVED** [review]

**Comment by prury** [comment]
its super fast now

https://github.com/kodadot/nft-gallery/assets/36627808/ad4a2d3e-051e-430f-af23-b9b4fff7fa8c

**Comment by yangwao** [comment]
thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 5.14 USD/DOT ~ 3.891 $DOT
🧗 [1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p](https://polkadot.subscan.io/account/1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)
🔗 [0xc4aaf5a2069fc4ab9499c594bc52aae3f0949a01ffb9c71b36f94ad698158a8a](https://polkadot.subscan.io/extrinsic/0xc4aaf5a2069fc4ab9499c594bc52aae3f0949a01ffb9c71b36f94ad698158a8a)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
