### PR TITLE
fix: 4956 move by 3 slides

### LINKED ISSUE #4956: Scrolling carousel by whole page
Right now when we are showing carousel, user needs press arrow each time need to do one scroll. 

Where we are having more from this collection and user don't want to open page with collection it's bit unusable if you are going through something bigger. 

https://user-images.githubusercontent.com/5887929/217860030-0e3cdcce-89bc-4c3d-9af6-d8dd99f98362.mov

Opensea has when you click scrolls through whole cards "page" 

https://user-images.githubusercontent.com/5887929/217860957-112718f7-0b38-49c5-bcca-cf262a465152.mov

Right now at Desktop we have 4 cards 

image

So I would try to see scroll through 3 cards on click. 
I.e, on pic above, Urban #12 is on the very right, after click will be on very left where is Urban #17 now.

Now I would suggest try it just at gallery item for now. 
Later we can put in on landing page.

### PR DESCRIPTION
**Pull request by maderi21**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #4956 
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [x] I've tested it at </bsx/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

https://user-images.githubusercontent.com/102800574/218132570-e741b768-4be0-4bdd-802d-33bb45516856.mp4

### CODE REVIEW

**Comment by exezbcz** [comment]
hey hey, good job

Lets remove the carousel indicator, now its misleading on which stage of the carousel you are and it does not even work on dark mode :D 

Next thing are the arrows.
- hide them when you reach the end

I suppose we'll apply this behavior to all carousels.

**Comment by maderi21** [comment]
@exezbcz arrows are hiding now at the end, I'm only not sure about the last sentence

> I suppose we'll apply this behavior to all carousels.

I've applied the arrow hiding to all carousels, however the `slideIndex` is set to 3 only for gallery item, quote from the issue spec:

> Now I would suggest try it just at gallery item for now.

One note, maybe it would be good idea to set the sliding not based on an arbitrary number (3) but on the `perView` setting based on the breakpoints:

```
breakpoints: {
      '(min-width: 640px)': {
        slides: { perView: 1.5, spacing: 32 },
      },
      '(min-width: 768px)': {
        slides: { perView: 2.5, spacing: 32 },
      },
      '(min-width: 1024px)': {
        slides: { perView: 3, spacing: 32 },
      },
      '(min-width: 1280px)': {
        slides: { perView: 4, spacing: 32 },
      },
    },
```

set at 3 for now though, let me know if more adjustments are needed.

**Comment by exezbcz** [comment]
> @exezbcz arrows are hiding now at the end, I'm only not sure about the last sentence
> 
> > I suppose we'll apply this behavior to all carousels.
> 
> I've applied the arrow hiding to all carousels, however the `slideIndex` is set to 3 only for gallery item, quote from the issue spec:
> 
> > Now I would suggest try it just at gallery item for now.
> 
> One note, maybe it would be good idea to set the sliding not based on an arbitrary number (3) but on the `perView` setting based on the breakpoints:
> 
> ```
> breakpoints: {
>       '(min-width: 640px)': {
>         slides: { perView: 1.5, spacing: 32 },
>       },
>       '(min-width: 768px)': {
>         slides: { perView: 2.5, spacing: 32 },
>       },
>       '(min-width: 1024px)': {
>         slides: { perView: 3, spacing: 32 },
>       },
>       '(min-width: 1280px)': {
>         slides: { perView: 4, spacing: 32 },
>       },
>     },
> ```
> 
> set at 3 for now though, let me know if more adjustments are needed.

yup, correct, looks ok

We will put it on the landing page as well. The spec was restricted to gallery so we can decide whether its better :D 



Changes: 
- Can we add an opacity animation to the arrow so it doesn't disappear instantly?

otherwise good, nice job!

**Comment by maderi21** [comment]
> Can we add an opacity animation to the arrow so it doesn't disappear instantly?

added 👍

File: components/carousel/module/CarouselAgnostic.vue [hunk 1]
```diff
@@ -108,4 +161,8 @@ const dotHelper = computed(() =>
     }
   }
 }
+.fade-leave-active,
+.fade-enter-active {
+  transition: all 1s ease;
+}
```
Comment (roiLeo) [inline components/carousel/module/CarouselAgnostic.vue:167]: This will be global

File: components/carousel/module/CarouselAgnostic.vue [hunk 2]
```diff
@@ -95,6 +122,32 @@ const totalDots = computed(() => {
...
+
+    return {
+      leftArrowValid,
+      rightArrowValid,
+      leftCarouselIndex,
+      rightCarouselIndex,
+    }
+  } else {
+    return {}
+  }
```
Comment (roiLeo) [inline components/carousel/module/CarouselAgnostic.vue:149]: do we need this empty return?

File: components/carousel/module/CarouselAgnostic.vue [hunk 3]
```diff
@@ -95,6 +122,32 @@ const totalDots = computed(() => {
 const dotHelper = computed(() =>
   slider.value && totalDots.value > 0 ? [...Array(totalDots.value).keys()] : []
 )
+
+const slideIndex = ref(3)
+
+const sliderSettings = computed(() => {
+  if (slider.value) {
+    const { track, options, slides } = slider.value
+    const abs = track.details.abs
```
Comment (roiLeo) [inline components/carousel/module/CarouselAgnostic.vue:131]: is this a number?

**Review by roiLeo — COMMENTED** [review]
Wouldn't it be better to create a `step` prop for `CarouselIndex`?
So that we can easily change the value

File: components/carousel/module/CarouselAgnostic.vue (hunk 1 above)
Comment (maderi21) [reply components/carousel/module/CarouselAgnostic.vue:150]: added `scoped`

File: components/carousel/module/CarouselAgnostic.vue (hunk 2 above)
Comment (maderi21) [reply components/carousel/module/CarouselAgnostic.vue:132]: yes, otherwise it's sometimes undefined (slider check is needed, because it loads slowly)

File: components/carousel/module/CarouselAgnostic.vue (hunk 3 above)
Comment (maderi21) [reply components/carousel/module/CarouselAgnostic.vue:114]: not sure what are you hinting at here, are there some types missing?

Comment (roiLeo) [reply components/carousel/module/CarouselAgnostic.vue:114]: `track.details.abs` has any type, afterward you use it in a `Math.min` & `Math.max` do you know if there could be side effects?

Comment (maderi21) [reply components/carousel/module/CarouselAgnostic.vue]: you're right, sorry, added Number constructor to abs and perView to hopefully avoid some of the unintended sideffects

**Review by roiLeo — APPROVED** [review]
✅ wfm

**Comment by yangwao** [comment]
pay 60 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $60 @ 30.69 USD/KSM ~ 1.955 $KSM
🧗 [JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa](https://kusama.subscan.io/account/JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa)
🔗 [0x377309e03da58dca69f07bd9e0358102b73d61ae19bb0d06bfb5810626b6cb01](https://kusama.subscan.io/extrinsic/0x377309e03da58dca69f07bd9e0358102b73d61ae19bb0d06bfb5810626b6cb01)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
