### PR TITLE
fix: videos in collection are not loading

### LINKED ISSUE #8641: Videos in collection are not loading
This collection: https://kodadot.xyz/ahk/collection/315
On production/AHK
Video previews are not loading at all. 

Screenshot 2023-12-17 at 13 13 29

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #8641

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

## no fix 
https://github.com/kodadot/nft-gallery/assets/44554284/b22c63d9-650e-4e3a-92c0-c592fca5cca1

## with fix 
https://github.com/kodadot/nft-gallery/assets/44554284/323201d4-45f4-4f9b-8aac-b0194e19bc2a

## Copilot Summary
copilot:summary

copilot:poem

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]

**Comment by prury** [comment]
@hassnian 
this one still won't load here for me nor inside or outside gallery item

image

https://deploy-preview-8729--koda-canary.netlify.app/ahk/gallery/315-9

**Comment by hassnian** [comment]
> @hassnian this one still won't load here for me nor inside or outside gallery item
> 
> image
> 
> https://deploy-preview-8729--koda-canary.netlify.app/ahk/gallery/315-9

@prury  it's working , wait some time it'll load eventually. 

CleanShot 2023-12-23 at 07 58 36@2x

CleanShot 2023-12-23 at 07 59 42@2x

File: libs/ui/src/components/MediaItem/type/VideoMedia.vue [hunk 1]
```diff
@@ -34,8 +37,17 @@ const props = withDefaults(
...
+const video = ref()
+
 const autoPlay = computed(() =>
   props.autoplay === undefined ? props.preview : props.autoplay,
 )
 const controls = computed(() => !props.preview)
+
+if (!autoPlay.value && props.src) {
+  useEventListener(video, 'loadeddata', () => {
+    video.value.play()
```
Comment (preschian) [inline libs/ui/src/components/MediaItem/type/VideoMedia.vue:49]: Because it will play video in milliseconds to show the thumbnail, the transferred size in the network will be higher than the canary, no?

**Review by preschian — COMMENTED** [review]
Interesting. What is the root cause anyway?

Because if you see metadata for this item, https://kodadot.xyz/ahk/gallery/315-8 is using the Koda image placeholder as a poster

- metadata: https://[image.w.kodadot.xyz/ipfs/bafkreidvztvbqfddfdoywlam755mg74ce6mgjavnbwzygbyq45dt6audjy](https://image.w.kodadot.xyz/ipfs/bafkreidvztvbqfddfdoywlam755mg74ce6mgjavnbwzygbyq45dt6audjy)
- image: https://image.w.kodadot.xyz/ipfs/bafkreidchqftqyioy6q776xmtwj62wk3qdgrqlsdsl7gv27qkecgzfbe2i
- animation_url: https://image.w.kodadot.xyz/ipfs/bafybeidknymqcfn5s4s2sa4sdzsacn6qkorkecf4ms4hczpv7bkldldiwu

File: libs/ui/src/components/MediaItem/type/VideoMedia.vue (hunk 1 above)
Comment (hassnian) [reply libs/ui/src/components/MediaItem/type/VideoMedia.vue:49]: > the transferred size in the network will be higher than the canary, no?

yes, just tested it to make sure 

@preschian do you got any better solution

**Comment by prury** [comment]
> 
> @prury it's working for me , wait a bit it will load eventually. that one takes some time
> 

after waiting 20m: 

image

image

it does load when i go straight to the URL: 
https://image-beta.w.kodadot.xyz/ipfs/bafybeihwql6baf5t45hz7bruyfl4xqah7ei2fua6vx2g5medw5wj32lf6e
(i think this is the right image)

**Comment by vikiival** [comment]
@JustLuuuu does this work for u?

**Comment by JustLuuuu** [comment]
> @JustLuuuu does this work for u?

wfm

File: libs/ui/src/components/MediaItem/type/VideoMedia.vue (hunk 1 above)
Comment (preschian) [reply libs/ui/src/components/MediaItem/type/VideoMedia.vue:49]: Ideally, capture it on `metadata` workers: https://github.com/kodadot/workers/blob/main/image/src/routes/metadata.ts#L74-L76. And then store it on our indexer

**Review by preschian — COMMENTED** [review]
I don't have a strong opinion on this one. I don't think this is an issue. Because the item uses a placeholder on the metadata, since this is on Assethub, I think it's better for the creator to update the metadata with a proper thumbnail/image instead.

But feel free to merge it

> Because if you see metadata for this item, [kodadot.xyz/ahk/gallery/315-8](https://kodadot.xyz/ahk/gallery/315-8) is using the Koda image placeholder as a poster
> 
> * metadata: [image.w.kodadot.xyz/ipfs/bafkreidvztvbqfddfdoywlam755mg74ce6mgjavnbwzygbyq45dt6audjy](https://image.w.kodadot.xyz/ipfs/bafkreidvztvbqfddfdoywlam755mg74ce6mgjavnbwzygbyq45dt6audjy)
> * image: [image.w.kodadot.xyz/ipfs/bafkreidchqftqyioy6q776xmtwj62wk3qdgrqlsdsl7gv27qkecgzfbe2i](https://image.w.kodadot.xyz/ipfs/bafkreidchqftqyioy6q776xmtwj62wk3qdgrqlsdsl7gv27qkecgzfbe2i)
> * animation_url: [image.w.kodadot.xyz/ipfs/bafybeidknymqcfn5s4s2sa4sdzsacn6qkorkecf4ms4hczpv7bkldldiwu](https://image.w.kodadot.xyz/ipfs/bafybeidknymqcfn5s4s2sa4sdzsacn6qkorkecf4ms4hczpv7bkldldiwu)

**Review by roiLeo — COMMENTED** [review]
this doesn't fix apple iOS/Safari issue

Capture d’écran 2024-01-02 à 10 41 50 AM
Capture d’écran 2024-01-02 à 10 41 31 AM

- https://deploy-preview-8729--koda-canary.netlify.app/ahk/collection/329

**Comment by hassnian** [comment]
indeed this pr is only about the preview issue

File: libs/ui/src/components/MediaItem/type/VideoMedia.vue (hunk 1 above)
Comment (yangwao) [reply libs/ui/src/components/MediaItem/type/VideoMedia.vue:49]: like first frame of video? That could be good I guess

Comment (vikiival) [reply libs/ui/src/components/MediaItem/type/VideoMedia.vue:49]: Sounds like a good Idea!

**Comment by yangwao** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 7.7 USD/DOT ~ 2.597 $DOT
🧗 [13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh](https://polkadot.subscan.io/account/13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)
🔗 [0xc1763598a53d7ed40eb9eca7abee2575514a3a93d83d6e5a47ac8c5ef359bc2b](https://polkadot.subscan.io/extrinsic/0xc1763598a53d7ed40eb9eca7abee2575514a3a93d83d6e5a47ac8c5ef359bc2b)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
