### PR TITLE
fix: Got into infinite loop with EVM

### LINKED ISSUE #10559: Got into infinite loop with EVM
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

I have logged in to Koda with [Phantom](https://phantom.app/) and I cannot relogin

### Please reproduce in steps

1. Login with Phantom wallet
2. Disconnect
3. Try to log in with something else
4. You cannot

### Expected Behavior

I expect that when I log out, I am logged out

### What browsers are you seeing the problem on?

Desktop Chrome

### At which address did you encounter bug?

canary.kodadot.xyz

### Are you logged in?

None

### Which wallet you are using?

Other

### At which chain did you encounter bug?

_No response_

### Screenshots

https://github.com/kodadot/nft-gallery/assets/22471030/f74353f7-6f9f-460a-8ba7-32a5f6843060

### Wallet Address & Transaction hash

_No response_

### Relevant log output

_No response_

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #10559

## Needs QA check

- @kodadot/qa-guild please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

https://github.com/kodadot/nft-gallery/assets/44554284/c28a22d6-0ca5-4902-9a8e-0162edb29b41

### CODE REVIEW

File: composables/useWeb3Modal.ts [hunk 1]
```diff
@@ -4,10 +4,12 @@ const modal = ref()
 
 export default () => {
   const { config } = useWagmi()
+  const { urlPrefix } = usePrefix()
 
   createWeb3Modal({
     wagmiConfig: config,
     projectId: useRuntimeConfig().public.walletConnectProjectId,
+    defaultChain: PREFIX_TO_CHAIN[urlPrefix.value] ?? undefined,
```
Comment (Jarsen136) [inline composables/useWeb3Modal.ts:12]:
```suggestion
    defaultChain: PREFIX_TO_CHAIN[urlPrefix.value],
```

It should be the same

**Review by Jarsen136 — APPROVED** [review]

**Review by preschian — APPROVED** [review]

File: composables/useWeb3Modal.ts (hunk 1 above)
Comment (vikiival) [reply composables/useWeb3Modal.ts:12]: cc @hassnian

Comment (hassnian) [reply composables/useWeb3Modal.ts]: > It should be the same

thanks fixed
