### PR TITLE
fix: adjust imageSrc on carousel component

### LINKED ISSUE #5498: Unknown media on landing
### What happened?

not showing media on landing

### Please reproduce in steps

go on https://rmrk2.kodadot.xyz

### Expected Behavior

show pics

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

No

### Which wallet you are using?

_No response_

### Screenshots

image

### Relevant log output

_No response_

### Payment link for reward

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #6597: VIdeo doesn't work on Statemine
### What happened?

this video nft doesn't show:

https://kodadot.xyz/stmn/gallery/u-117-382

compare with 
https://singular.app/collectibles/statemine/117/3111

### Please reproduce in steps

go to https://kodadot.xyz/stmn/gallery/u-117-382

### Expected Behavior

expect to see video

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

None

### Which wallet you are using?

Talisman

### Screenshots

image

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #5498
- [x] Closes #6597

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)

## Screenshot 📸

1. fetch the original mime type in the carousel component

Screenshot 2023-08-07 165437

2. add `mediaUri` to fetch metadata

Screenshot 2023-08-07 171425

3. add "Animated Media" to the item description section and link to the public gateway to see original content

image

### CODE REVIEW

**Comment by vikiival** [comment]
Hope this would work

File: components/carousel/module/CarouselMedia.vue [hunk 1]
```diff
@@ -5,23 +5,17 @@
...
-      <PreviewMediaResolver
-        v-if="item.animationUrl"
-        :src="item.animationUrl"
-        :poster="imageSrc || ''"
-        :metadata="item.metadata" />
-      <BasicImage
-        v-else
-        :src="imageSrc"
-        :alt="item.name"
-        custom-class="carousel__image-wrapper" />
```
Comment (vikiival) [inline components/carousel/module/CarouselMedia.vue:17]: How is 3D handled then?

File: components/gallery/GalleryItemDescription.vue [hunk 2]
```diff
@@ -218,10 +222,11 @@ const propertiesTabDisabled = computed(() => {
 
 const metadataMimeType = ref('application/json')
 const metadataURL = ref('')
+const animationMediaMimeType = ref('')
 
 watchEffect(async () => {
   if (nft.value?.metadata) {
-    const sanitizeMetadata = sanitizeIpfsUrl(nft.value?.metadata)
+    const sanitizeMetadata = sanitizeIpfsUrl(nft.value?.metadata, 'cloudflare')
```
Comment (vikiival) [inline components/gallery/GalleryItemDescription.vue:229]: Doesn't this always return json? Why not using our R2 ?

File: components/gallery/GalleryItemDescription.vue [hunk 3]
```diff
@@ -230,5 +235,13 @@ watchEffect(async () => {
       response.headers.get('content-type') || 'application/json'
     metadataURL.value = sanitizeMetadata
   }
+
+  if (nftAnimation.value) {
+    animationMediaMimeType.value = await getMimeType(nftAnimation.value)
```
Comment (vikiival) [inline components/gallery/GalleryItemDescription.vue:240]: import { obtainMimeType } from '@kodadot1/minipfs'

File: libs/ui/src/components/MediaItem/MediaItem.vue [hunk 4]
```diff
@@ -110,7 +106,7 @@ export default {
   },
   methods: {
     async updateComponent() {
-      if (this.animationSrc && !this.mimeType) {
+      if (this.animationSrc) {
```
Comment (vikiival) [inline libs/ui/src/components/MediaItem/MediaItem.vue:109]: This will overfetch on `HEAD` request

File: components/carousel/module/CarouselMedia.vue (hunk 1 above)
Comment (preschian) [reply components/carousel/module/CarouselMedia.vue:17]: `<MediaItem />` component
https://github.com/kodadot/nft-gallery/blob/6d4cf92216089b2798410690d2d0e7ba3c2fd3b9/libs/ui/src/components/MediaItem/MediaItem.vue#L91-L94

File: libs/ui/src/components/MediaItem/MediaItem.vue (hunk 4 above)
Comment (preschian) [reply libs/ui/src/components/MediaItem/MediaItem.vue:109]: Do you have any idea for an alternative fix?

Except, we can store that mime-type stuff from the indexer side to pass that mime-type as a prop. At the moment, we can't rely on `meta.type`

Comment (roiLeo) [reply libs/ui/src/components/MediaItem/MediaItem.vue:109]: +1 to store it on indexer so we can query different mime type

Comment (vikiival) [reply libs/ui/src/components/MediaItem/MediaItem.vue:109]: > Do you have any idea for an alternative fix?


1.
- https://github.com/kodadot/loligo/issues/44

2.
- https://github.com/kodadot/research/issues/103

> we can't rely on meta.type

Why so? 
80% of content (except rmrk2) was minted via kodadot. 
So a root isssue can be also hidden in UI

Comment (preschian) [reply libs/ui/src/components/MediaItem/MediaItem.vue:109]: > * [Fetch mime-type of animation_url loligo#44](https://github.com/kodadot/loligo/issues/44)

> Why so?

Need mime type for both media and animated media. in this [item](https://deploy-preview-6599--koda-canary.netlify.app/bsx/gallery/3030053998-2), both media and animated media mime type is `image/jpeg`. but, in metadata is `application/octet-stream`
image


> So a root isssue can be also hidden in UI

then, how do we check that the item mime type is correct or wrong in the current state in our UI?

can someone invite me to this repo? https://github.com/kodadot/research/issues/103 I can't open the link

Comment (preschian) [reply libs/ui/src/components/MediaItem/MediaItem.vue:109]: > Question Is why don't we fetch that directly from subsquid?

afaik, mostly this is what we already do now
1. check `mime.type` from subsquid
2. if not exists, fetch mime type from `image` or `animationUrl`

for example, that item is currently `null` from subsquid

image

I found out that this is similar case on rmrk2 https://github.com/kodadot/workers/issues/95. that's why I said can't rely on `metadata` or `meta.type`. and, if we want to address overfetch issue, put the "correct" mimetype to indexer

> Basically make D1 with metadata table (name, description, attributes, image ...)

if your concern is overfetch, for this case is overkill, imo. because we can solve it by request with HEAD method. and the different with this is only endpoint change

for now, I will update it to default render image component. but, if this case possible https://github.com/kodadot/nft-gallery/issues/5498#issuecomment-1669515097 it will render incorrectly

Comment (preschian) [reply libs/ui/src/components/MediaItem/MediaItem.vue:109]: One more edge case https://github.com/kodadot/nft-gallery/issues/6618. the creator puts `image` and `metadata` on the s3 bucket. Usually, the other creator uses IPFS.

`metadata` stuff is user define so that the output can be anything. Based on that, I assume that I am more convinced that we can't rely on the `type` attribute from metadata and even the `image` attribute.

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 5.05 USD/DOT ~ 9.901 $DOT
🧗 [1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p](https://polkadot.subscan.io/account/1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)
🔗 [0x25dc29064185aeb416a4d824e5161039f489cd182228ca184161166dbb1b8480](https://polkadot.subscan.io/extrinsic/0x25dc29064185aeb416a4d824e5161039f489cd182228ca184161166dbb1b8480)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

File: libs/ui/src/components/MediaItem/MediaItem.vue (hunk 4 above)
Comment (preschian) [reply libs/ui/src/components/MediaItem/MediaItem.vue]: updated, render image by default

notes: nft creator can put other than a static image in their `image` or `mediaUri` attributes on metadata

**Review by Jarsen136 — APPROVED** [review]

**Comment by preschian** [comment]
> can you check? [deploy-preview-6599--koda-canary.netlify.app/ksm/gallery/15635794-54bbd380dc3baaa27b-EVRLOOT-ADVANCED_FISHINGROD-2](https://deploy-preview-6599--koda-canary.netlify.app/ksm/gallery/15635794-54bbd380dc3baaa27b-EVRLOOT-ADVANCED_FISHINGROD-2)

oohh I will check

I though that one is related to https://github.com/kodadot/nft-gallery/issues/5530 and https://github.com/kodadot/nft-gallery/pull/6051

**Comment by preschian** [comment]
> can you check? [deploy-preview-6599--koda-canary.netlify.app/ksm/gallery/15635794-54bbd380dc3baaa27b-EVRLOOT-ADVANCED_FISHINGROD-2](https://deploy-preview-6599--koda-canary.netlify.app/ksm/gallery/15635794-54bbd380dc3baaa27b-EVRLOOT-ADVANCED_FISHINGROD-2)

I can only fix the "More from this collection" section

for this specific nft seems like from the indexer side. on rmrk2 at least need some `resources`. this nft `meta.image` and `resources` was empty
image

**Comment by prury** [comment]
> > can you check? [deploy-preview-6599--koda-canary.netlify.app/ksm/gallery/15635794-54bbd380dc3baaa27b-EVRLOOT-ADVANCED_FISHINGROD-2](https://deploy-preview-6599--koda-canary.netlify.app/ksm/gallery/15635794-54bbd380dc3baaa27b-EVRLOOT-ADVANCED_FISHINGROD-2)
> 
> I can only fix the "More from this collection" section
> 
> for this specific nft seems like from the indexer side. on rmrk2 at least need some `resources`. this nft `meta.image` and `resources` was empty image

its a rabbit hole! well, thanks for going trough this journey @preschian
