### PR TITLE
fix: Drop calendar: Collection with price that is not set should be TBA

### LINKED ISSUE #11034: Drop calendar: Collection with price that is not set should be TBA
When I don't set the price in the Cloudfare - the price in the calendar shows TBA. Which is good. But this TBA should be on both - the card and when you open the card (check pic). If its not possible to add it to card - let me know and I will try to set the price in all cases. Just sometimes we dont agree on it earlier

You can see that on collection **Alpinista**.

Screenshot 2024-09-23 at 12 44 09

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #11034

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

File: components/drops/calendar/DropPreviewModal.vue [hunk 1]
```diff
@@ -210,5 +210,5 @@ const formattedDate = computed(() =>
 )
 
 const withPlaceholder = (nullableValue: unknown, or: unknown) =>
-  nullableValue === null ? placeholder : or
+  nullableValue === null || nullableValue === '' ? placeholder : or
```
Comment (hassnian) [inline components/drops/calendar/DropPreviewModal.vue:213]:
```suggestion
  isTBA(nullableValue) ? placeholder : or
```

File: components/drops/BasicDropCard.vue [hunk 2]
```diff
@@ -59,8 +59,11 @@
                   </span>
                 </div>
               </slot>
+              <div v-if="dropPrice === null || dropPrice === ''">
```
Comment (hassnian) [inline components/drops/BasicDropCard.vue:62]:
```suggestion
              <div v-if="isTBA(dropPrice)">
```

**Review by hassnian — APPROVED** [review]

**Review by vikiival — APPROVED** [review]
