### PR TITLE
fix: hide other language

### LINKED ISSUE #11454: Other languages on Koda
Do we really need them?

Image

The translations are not good, not everything is translated. half of the stuff is missing. Idk, do we really need these? 

Image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs Design check

- @exezbcz please review

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #11454

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image
image

## Summary by CodeRabbit

- **Refactor**
  - Removed language selection features from mobile navigation, wallet, and profile menus to streamline the interface.
  - Enforced a fixed English locale across the application.
- **Bug Fixes**
  - Eliminated potential confusion by removing unused language components and functionality.
- **Tests**
  - Removed end-to-end tests related to language selection.
- **Chores**
  - Cleaned up unused language management code and associated dependencies.

### CODE REVIEW

**Review by preschian — APPROVED** [review]

File: stores/preferences.ts [hunk 1]
```diff
@@ -268,6 +268,8 @@ export const usePreferencesStore = defineStore('preferences', {
     },
     setUserLocale(locale: string) {
       const { $i18n } = useNuxtApp()
+      // only supports en for now
+      locale = 'en'
       $i18n.locale.value = locale
       this.userLocale = locale
```
Comment (preschian) [inline stores/preferences.ts:274]: oh, I missed this one. based on sonar, should we set like this?
```suggestion
      $i18n.locale.value = 'en'
      this.userLocale = 'en'
```

**Comment by hassnian** [comment]
should we also remove the other translation files ?

**Comment by Jarsen136** [comment]
> shouldn't we also remove the other translation files ?

It's doable to delete the other translation files, but we may need them in the future. wdyt

**Comment by hassnian** [comment]
> > shouldn't we also remove the other translation files ?
> 
> It's doable to delete the other translation files, but we may need them in the future. wdyt

I'd delete them we can always go back to this pr and recover them, @preschian wdyt

**Comment by preschian** [comment]
> > > shouldn't we also remove the other translation files ?
> > 
> > 
> > It's doable to delete the other translation files, but we may need them in the future. wdyt
> 
> I'd delete them we can always go back to this pr and recover them, @preschian wdyt

Oh, this one is okay for me. We can revert it once we need to in the future

**Comment by Jarsen136** [comment]
Updated

**Review by hassnian — APPROVED** [review]

**Comment by roiLeo** [comment]
smh..
