### PR TITLE
fix: Top collections on base

### LINKED ISSUE #10126: Top collections on base
image
- lets probably remove the option to filter out base

you will get there by changing to base in the network switch - leave this one still possible 

image

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

`imx` hidden
`base` working (can't sort by volume) it's better than not having it on the landing 

- [x] Closes #10126

## Needs QA check

- @kodadot/qa-guild please review

## Needs Design check

- @exezbcz please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2024-04-23 at 16 02 34@2x

### CODE REVIEW

File: components/collection/CollectionCard.vue [hunk 1]
```diff
@@ -51,9 +51,7 @@ onMounted(async () => {
   const metadata = (await processSingleMetadata(
     props.collection.metadata,
   )) as Metadata
-  image.value = sanitizeIpfsUrl(
-    metadata.image || metadata.thumbnailUri || metadata.mediaUri || '',
-  )
+  image.value = sanitizeIpfsUrl(getCollectionImage(metadata) || '')
```
Comment (vikiival) [inline components/collection/CollectionCard.vue:54]: why?

File: components/landing/topCollections/utils/useTopCollections.ts [hunk 2]
```diff
@@ -24,30 +24,40 @@ const proccessData = (
...
-      weeklyrangeVolume: weeklyrangeVolume(saleEvents),
-      monthlyrangeVolume: monthlyrangeVolume(saleEvents),
-      threeMonthlyrangeVolume: threeMonthRangeVolume(saleEvents),
-    }
-  })
+      const image = e.image
+        ? sanitizeIpfsUrl(e.image)
+        : sanitizeIpfsUrl(
+            getCollectionImage(await processSingleMetadata(e.metadata)) || '',
+          )
```
Comment (vikiival) [inline components/landing/topCollections/utils/useTopCollections.ts:40]: why?

**Review by vikiival — COMMENTED** [review]
~

File: components/landing/topCollections/utils/useTopCollections.ts (hunk 2 above)
Comment (hassnian) [reply components/landing/topCollections/utils/useTopCollections.ts:40]: image is null

File: components/collection/CollectionCard.vue (hunk 1 above)
Comment (hassnian) [reply components/collection/CollectionCard.vue:54]: Didn't want to duplicate that code , that's the  why of the util function

**Comment by exezbcz** [comment]
thanks for this one!

File: utils/collections.ts [hunk 3]
```diff
@@ -0,0 +1,4 @@
+import type { Metadata } from '@/components/rmrk/service/scheme'
```
Comment (preschian) [inline utils/collections.ts:1]: Since we are dropping rmrk support, it would be better if we are not reusing from that

File: components/landing/topCollections/utils/useTopCollections.ts [hunk 4]
```diff
@@ -24,30 +24,40 @@ const proccessData = (
   collectionsList: CollectionEntity[],
   collectionsSales: CollectionSales[],
 ) => {
-  return collectionsList.map((e): CollectionEntityWithVolumes => {
-    const thisCollectionSales = collectionsSales.find(
-      ({ id }) => id === e.id,
-    ) as CollectionSales
-    const saleEvents = thisCollectionSales.sales.map((nft) => nft.events).flat()
+  return Promise.all(
+    collectionsList.map(async (e): Promise<CollectionEntityWithVolumes> => {
```
Comment (preschian) [inline components/landing/topCollections/utils/useTopCollections.ts:28]: nitpick

```suggestion
    collectionsList.map(async (collection): Promise<CollectionEntityWithVolumes> => {
```

**Review by preschian — APPROVED** [review]

File: components/landing/topCollections/utils/useTopCollections.ts (hunk 2 above)
Comment (vikiival) [reply components/landing/topCollections/utils/useTopCollections.ts:40]: If it is because non-koda collections i will remove them.

File: utils/collections.ts (hunk 3 above)
Comment (hassnian) [reply utils/collections.ts:1]: just using the type that is already used inside `CollectionCard.vue`

CleanShot 2024-04-25 at 15 02 41@2x

can't find another type that matches this one

File: components/landing/topCollections/utils/useTopCollections.ts (hunk 4 above)
Comment (hassnian) [reply components/landing/topCollections/utils/useTopCollections.ts]: fixed

File: components/landing/topCollections/utils/useTopCollections.ts (hunk 2 above)
Comment (hassnian) [reply components/landing/topCollections/utils/useTopCollections.ts]: as you can see `image` is null , `TopCollectionsCard` gets the images from the metadata

query 

`````
query topCollections($limit: Int, $orderBy: CollectionEntityOrderByInput = volume_DESC, $where: CollectionEntityWhereInput = {volume_gt: "0"}) {
  collectionEntities(orderBy: [$orderBy], limit: $limit, where: $where) {
    id
    name
    image
    media
    volume
    metadata
    floor
    nftCount
    ownerCount: distribution
    __typename
  }
}


{
  "orderBy": "volume_DESC",
  "where": {
    "issuer_not_in": []
  },
  "limit": 12
}
`````
results

`````
{
  "data": {
    "collectionEntities": [
      {
        "id": "0x3c93690bbe585475fdfadab3f59b4604008c7ac4",
        "name": "Bloquinhos",
        "image": null,
        "media": null,
        "volume": "0",
        "metadata": "https://arweave.net/brcg0wOzdEIjwBswDdt2nTjsl0-8FJNtQaiKCwaOMqQ ",
        "floor": "0",
        "nftCount": 0,
        "ownerCount": 0,
        "__typename": "CollectionEntity"
      },
      {
        "id": "0x25194dfc7981d8a13367fe19b5b1c5fc010d535f",
        "name": "Conjunto",
        "image": null,
        "media": null,
        "volume": "0",
        "metadata": "https://arweave.net/btZcKjV2qZ5OGxQm02h6rCcK1MY6bV6JYKV30Vr1ipM",
        "floor": "0",
        "nftCount": 0,
        "ownerCount": 0,
        "__typename": "CollectionEntity"
      },
      {
        "id": "0x3c549c45588fb42a94ca7b84081df43d95952c01",
        "name": "Memories",
        "image": null,
        "media": null,
        "volume": "0",
        "metadata": "https://arweave.net/UIV7b488550HzoAdpwRO7laTUDq9VPOD0YEP8sQfkaU",
        "floor": "0",
        "nftCount": 0,
        "ownerCount": 0,
        "__typename": "CollectionEntity"
      },
      {
        "id": "0x1b60a7ee6bba284a6aafa1eca0a1f7ea42099373",
        "name": "Vortices",
        "image": null,
        "media": null,
        "volume": "0",
        "metadata": "ipfs://bafkreicthpidyo3gznp3uuezvweiur7xcbo5qcwgw3x4teui2psoqxxbgq",
        "floor": "0",
        "nftCount": 0,
        "ownerCount": 0,
        "__typename": "CollectionEntity"
      },
      {
        "id": "0x0b6504d95f9d550d274468fb6de5d13b7e64aa6a",
        "name": "Higher",
        "image": null,
        "media": null,
        "volume": "0",
        "metadata": "ipfs://bafkreickjpqtqulirvugyqupeogbvum2uqsrp5focif5427fd2fzgywo4u",
        "floor": "0",
        "nftCount": 0,
        "ownerCount": 0,
        "__typename": "CollectionEntity"
      },
      {
        "id": "0xc029b380f8a451cfd9e5124fa9fcad4397b8c119",
        "name": "Unfoldings",
        "image": null,
        "media": null,
        "volume": "0",
        "metadata": "ipfs://bafkreib5pt53graj4wexhpgj3qrl37m3bsgjf3hz5muogqccdtutaq2huq",
        "floor": "0",
        "nftCount": 0,
        "ownerCount": 0,
        "__typename": "CollectionEntity"
      }
    ]
  }
}

`````

File: utils/collections.ts (hunk 3 above)
Comment (vikiival) [reply utils/collections.ts:1]: > can't find another type that matches this one

https://github.com/kodadot/packages/blob/c1ccad8b6b6d42f642fa884784e19e4bd24155a9/hyperdata/src/types.ts#L7

**Review by vikiival — CHANGES_REQUESTED** [review]

**Comment by prury** [comment]
@vikiival we good here?

**Comment by vikiival** [comment]
Well @hassnian did best he could, once we will have proper indexer will revert this

**Review by prury — APPROVED** [review]

**Comment by prury** [comment]
@vikiival github won't let me merge this without your approval

image

**Review by vikiival — APPROVED** [review]
