### PR TITLE
fix: Not possible to play with variations on drops that are minted out

### LINKED ISSUE #10050: Not possible to play with variations on drops that are minted out
Its not possible to play with generate button once the collection is minted out? It's generating the same picture. I think it should still work so people can play with the code. Right?

https://github.com/kodadot/nft-gallery/assets/104380776/89925e5c-a3ec-4ecf-bcd0-ad405798df2b

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

`mintedAmountForCurrentUser` value was wrong

- [x] Closes #10050

## Needs QA check

- @kodadot/qa-guild please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2024-04-13 at 12 21 22

### CODE REVIEW

File: composables/drop/useGenerativeDropMint.ts [hunk 1]
```diff
@@ -26,6 +26,7 @@ export type UnlockableCollectionById = {
 export function useCollectionEntity(collectionId?: string) {
   const { drop } = useDrop()
   const { client } = usePrefix()
+  const { accountId } = useAuth()
```
Comment (vikiival) [inline composables/drop/useGenerativeDropMint.ts:29]: Why do you need account? 

What if account is undefined / user not logged in

Comment (hassnian) [reply composables/drop/useGenerativeDropMint.ts:29]: > Why do you need account?

from this query we get the data that we later use  for `mintedAmountForCurrentUser` and that's why need the accountId


CleanShot 2024-04-15 at 11 59 17@2x


CleanShot 2024-04-15 at 11 58 42@2x


> What if account is undefined / user not logged in

accountId will be '' and 0 will be returned. 

CleanShot 2024-04-15 at 12 01 00@2x

**Review by vikiival — APPROVED** [review]

**Review by daiagi — APPROVED** [review]
