### PR TITLE
fix: activity tab did not refresh after buy

### LINKED ISSUE #5318: After buy activity tab did not refreshed
https://beta.kodadot.xyz/rmrk/gallery/16967859-62DB09E2F7FAA81C5F-FLOW-NIGHT_MAGIC_SPELLS-0000000000000001

image

### PR DESCRIPTION
**Pull request by leo-anderson-x**
## Changes
- Apollo defaults to using cache first strategy, which prevents getting the latest data even after refreshing after a purchase. Here, network first strategy is used during refresh to ensure getting the latest data.
- use graphql subscription to refresh events data

---

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5318

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DzUbHCk3Fr3XdCPNKo7uCJvtBH7YfgiFbn4Gr3VmCMiFy1C)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

https://user-images.githubusercontent.com/128157824/227688338-a7ba8032-27c3-4d1f-9fdb-93cac870971c.mp4

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Tested on `/snek/gallery/807893860-6` and it didn't work right away, I had to click on Activity tab multiple times.
 
**video**

https://user-images.githubusercontent.com/9987732/227222034-bef0068f-074b-4e08-867f-31867ac07f10.mov

File: components/gallery/GalleryItem.vue [hunk 1]
```diff
@@ -137,7 +138,9 @@ const showCongratsMessage = ref(false)
 const onNFTBought = () => {
   activeTab.value = tabs.activity
   showCongratsMessage.value = true
+  tabsRef.value?.refreshActivityTab()
```
Comment (Jarsen136) [inline components/gallery/GalleryItem.vue:141]: Do refetch after buying action may be not the best solution. It's still possible to fetch the old events data.

**Review by Jarsen136 — CHANGES_REQUESTED** [review]
We use graphql subscription to listen the changes on chain, so that all the changes like LIST BUY SEND would be known.  So, pls figure out why it does not work as expected.

Pls check the `useSubscriptionGraphql` method at `components/gallery/useGalleryItem.ts` line63

File: composables/useGraphql.ts [hunk 2]
```diff
@@ -43,16 +48,24 @@ export default function ({
...
+    await doFetch({
+      options: {
+        fetchPolicy: 'network-only',
+      },
+    })
+  }
+
   if (isRef(variables)) {
-    watchEffect(doFetch)
+    watchEffect(() => doFetch())
```
Comment (leo-anderson-x) [inline composables/useGraphql.ts:60]: This is to solve the TS error. Because `watchEffect` passes onCleanup to effect, which is inconsistent with the newly added parameter type of `doFetch`.

File: components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue [hunk 3]
```diff
@@ -99,19 +100,42 @@ const dprops = defineProps<{
...
+  ) {
+    id
+    interaction
+    timestamp
+    meta
+  }`,
+  onChange: () => {
+    refetch({
+      options: {
+        fetchPolicy: 'network-only',
```
[the remark this answers is not in the document]
Comment (leo-anderson-x) [reply components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue]: updated: [`9fa5e12`](https://github.com/kodadot/nft-gallery/pull/5327/commits/9fa5e121b12da72ca4baf96166a854b5d31b1f9b)

**Comment by leo-anderson-x** [comment]
@roiLeo fixed, I uploaded the demo video to the PR description.

**Review by Jarsen136 — APPROVED** [review]
code lgtm

**Review by roiLeo — APPROVED** [review]

File: composables/useGraphql.ts (hunk 2 above)
Comment (vikiival) [reply composables/useGraphql.ts:60]: Nice I learned something today ❤️

https://vuejs.org/api/reactivity-core.html#watcheffect

File: components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue [hunk 4]
```diff
@@ -99,19 +100,36 @@ const dprops = defineProps<{
...
+  events (
+    where: { nft: { id_eq: "${dprops.nftId}" }, interaction_in: [${interaction}] }
+    orderBy: timestamp_DESC
+    limit: 5
+  ) {
+    id
+    interaction
+    timestamp
+    meta
+  }`,
```
Comment (vikiival) [inline components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue:129]: can this use a `.graphql` file pls?

it is very easy to introduce bug if it passed like a string

**Review by vikiival — APPROVED** [review]
Otherwise oki 🤗

**Comment by vikiival** [comment]
pay 20 usd

**Comment by vikiival** [comment]
Thanks for the contribution!

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 32.68 USD/KSM ~ 0.612 $KSM
🧗 [DzUbHCk3Fr3XdCPNKo7uCJvtBH7YfgiFbn4Gr3VmCMiFy1C](https://kusama.subscan.io/account/DzUbHCk3Fr3XdCPNKo7uCJvtBH7YfgiFbn4Gr3VmCMiFy1C)
🔗 [0x57dc1d487f95711a3f65e806f4fae83fb7fc3036b07d988c910190a6c1b5762b](https://kusama.subscan.io/extrinsic/0x57dc1d487f95711a3f65e806f4fae83fb7fc3036b07d988c910190a6c1b5762b)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
