### PR TITLE
fix: Cant list items on AHK - for Uniques pallet

### LINKED ISSUE #6820: Cant list items on AHK - for Uniques pallet
I tried list my items on AHK 

related ? 
- #6778 

- https://kodadot.xyz/ahk/gallery/u-2024-10857

image

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #6820
  - [ ] Requires deployment <snek/rubick/worker>

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [ ] My fix has changed UI

  ## Copilot Summary
  
### <samp>🤖 Generated by Copilot at 62210ab</samp>

This pull request fixes a bug in the NFT listing logic, refactors some code for clarity, and enables a temporary workaround to test the relisting feature on the staging environment. The changes affect the `composables/transaction/transactionList.ts` and `components/gallery/GalleryItemAction/GalleryItemAction.vue` files.

  
### <samp>🤖 Generated by Copilot at 62210ab</samp>

> _`v-if` workaround_
> _testing relisting feature_
> _snow melts, price changes_

### CODE REVIEW

File: components/gallery/GalleryItemAction/GalleryItemAction.vue [hunk 1]
```diff
@@ -16,9 +16,9 @@
     <!-- change price as an owner -->
     <GalleryItemPriceRelist
       v-if="isOwner && nft?.id && nft?.price && nft?.collection.id"
-      :collection-id="nft.collection.id"
-      :nft-id="nft.id"
-      :nft-price="nft.price"
+      :collection-id="nft?.collection.id"
```
Comment (preschian) [inline components/gallery/GalleryItemAction/GalleryItemAction.vue:19]: Do we still need this? since we already had `v-if="isOwner && nft?.id && nft?.price && nft?.collection.id"` on line 18

**Review by preschian — APPROVED** [review]
otherwise lgtm

File: components/gallery/GalleryItemAction/GalleryItemAction.vue [hunk 2]
```diff
@@ -16,9 +16,9 @@
...
+      :nft-id="nft?.id"
+      :nft-price="nft?.price"
```
Comment (Jarsen136) [inline components/gallery/GalleryItemAction/GalleryItemAction.vue:21]:
```suggestion
      :collection-id="nft.collection.id"
      :nft-id="nft.id"
      :nft-price="nft.price"
```

File: components/gallery/GalleryItemAction/GalleryItemAction.vue (hunk 1 above)
Comment (Jarsen136) [reply components/gallery/GalleryItemAction/GalleryItemAction.vue]: You are right. It's just for testing.

**Comment by yangwao** [comment]
wfm!

https://deploy-preview-6850--koda-canary.netlify.app/ahk/gallery/u-2024-11154?page=1

image

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 4.48 USD/DOT ~ 11.161 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x77ada8bd138409262fe1fc0fe983402e692cbe7b8bccac1e65bdcf85dbcd9346](https://polkadot.subscan.io/extrinsic/0x77ada8bd138409262fe1fc0fe983402e692cbe7b8bccac1e65bdcf85dbcd9346)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Review by vikiival — APPROVED** [review]
