### PR TITLE
fix(mint): ToS switch

### LINKED ISSUE #477: Add basic ToS to mint
- [ ] checkbox with text condition for `I confirm that I hold full copyright ownership of the submitted digital asset (or have sufficient permission by the owner to use the asset).
`
- [ ] should not be allowed to mint without a ticked checkbox

### PR DESCRIPTION
**Pull request by roiLeo**
closes #477 

Button "CLICK TO CREATE NFT(s)" is disabled when ToS is unchecked.
Maybe it need something to tell user which are required fields.

### Before submitting this PR, please make sure:
- [x] Code builds clean without any erros or warnings
- [x] Merged recent default branch -- **main** and I've no conflicts
- [x] Didn't break any original functionality

### Optional
- [ ] I've tested it on mobile and everything works

### PR type
- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### Screenshot

Screenshot 2021-06-28 at 15-20-24 KodaDot Low fees and low carbon minting

### CODE REVIEW

File: src/components/rmrk/Create/SimpleMint.vue [hunk 1]
```diff
@@ -147,6 +147,12 @@
             />
           </b-field>
           <ArweaveUploadSwitch  v-model="arweaveUpload" />
+          <b-field>
+            <b-switch v-model="hasToS"
+              :rounded="false">
+              I confirm that I hold full copyright ownership of the submitted digital asset (or have sufficient permission by the owner to use the asset)
```
Comment (vikiival) [inline src/components/rmrk/Create/SimpleMint.vue:153]: Add this to the translation file `en.json`
```json
"termOfService" : {
  "accept": ""
}
```

**Review by vikiival — CHANGES_REQUESTED** [review]
