### PR TITLE
fix: close sidebar on network change

### LINKED ISSUE #5942: close sidebar on network change
> * if i select the BSX network, check my balances and then change to RMRK without closing the modal it still shows my BSX balances:

I would propose to close sidebar on network change till now

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/5400#issuecomment-1546203706_

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5942
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at dd02484</samp>

Improved network switching in `ConnectWalletModal.vue` by using URL prefix from store and closing modal on change.

### <samp>🤖 Generated by Copilot at dd02484</samp>

> _Oh, we're the brave developers of the Nuxt app_
> _We import the instance and we get the prefix from the store_
> _We close the modal when the network switches, that's a fact_
> _And we heave away and code some more_

### CODE REVIEW

File: components/common/ConnectWallet/ConnectWalletModal.vue [hunk 1]
```diff
@@ -91,8 +91,12 @@ const { $i18n } = useNuxtApp()
 const selectedWalletProvider = ref<BaseDotsamaWallet>()
 const hasSelectedWalletProvider = ref(false)
 const forceWalletSelect = ref(false)
+const { $store } = useNuxtApp()
 const identityStore = useIdentityStore()
 
+// urlPrefix from usePrefix() would not update inside modal component
+const urlPrefix = computed(() => $store.getters.currentUrlPrefix)
```
Comment (roiLeo) [inline components/common/ConnectWallet/ConnectWalletModal.vue:98]: hmmm... this is strange prefix should be based on this value too

**Review by roiLeo — APPROVED** [review]
✅ wfm

File: components/common/ConnectWallet/ConnectWalletModal.vue (hunk 1 above)
Comment (roiLeo) [reply components/common/ConnectWallet/ConnectWalletModal.vue:98]: #5984, time to update?

Comment (Jarsen136) [reply components/common/ConnectWallet/ConnectWalletModal.vue:98]: Not sure why urlPrefix does not update using `usePrefix`in the modal component. Maybe leave it to https://github.com/kodadot/nft-gallery/issues/5984 for deeper invigorate.

**Comment by yangwao** [comment]
yes, it's better, there is still glitch missing bug on balance on initial but we are getting there
- #5838 

https://github.com/kodadot/nft-gallery/assets/5887929/7531a695-108b-4fd4-8663-efd54fc8508e

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 25.59 USD/KSM ~ 1.172 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x801ed6c1ab8ba41cafa662e31769859613ee4ceaaa55a76b8121f8a6568df119](https://kusama.subscan.io/extrinsic/0x801ed6c1ab8ba41cafa662e31769859613ee4ceaaa55a76b8121f8a6568df119)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
