### PR TITLE
fix: drops max count

### LINKED ISSUE #10706: Drops max count mismatch for a moment
### What happened?

seems like we are getting the collection max from different places

CleanShot 2024-07-30 at 14 37 04@2x

it goes from loading to -> see listing -> mint

ideally that `see listing` should not appear 

https://github.com/user-attachments/assets/ba5ca125-a32b-4405-a5d7-997cdfa90430

### LINKED ISSUE #10804: All Base drop shows only 1 minted NFT
Screenshot 2024-08-13 at 12 56 30

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #10706
- [x] Closes #10804
- [x] adjust flaky tests

### CODE REVIEW

**Comment by preschian** [comment]
Hmm, I think the limited specs of the current runner cause flaky tests from e2e. Since running e2e tests is quite heavy, we need to increase the specs: https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners

**Comment by vikiival** [comment]
Please can you do the test fixes and and max count in two separated prs?

File: composables/drop/useGenerativeDropMint.ts [hunk 1]
```diff
@@ -28,47 +26,38 @@ export type DropCollectionById = {
...
+  const collectionName = ref()
+
+  watchEffect(async () => {
+    if (drop.value.collection) {
+      const api = await useApi().apiInstance.value
+      const [queryCollectionConfig, queryCollection, queryCollectionMetadata] = await Promise.all([
+        api.query.nfts.collectionConfigOf(drop.value.collection),
+        api.query.nfts.collection(drop.value.collection),
+        api.query.nfts.collectionMetadataOf(drop.value.collection),
+      ])
```
Comment (Jarsen136) [inline composables/drop/useGenerativeDropMint.ts:43]: How about the drops on base (EVM) network? IMO it does not work with the RPC interface.

Comment (preschian) [reply composables/drop/useGenerativeDropMint.ts:43]: good question 👍🏻
it also works on evm, let me show it to you

Comment (preschian) [reply composables/drop/useGenerativeDropMint.ts:43]: - https://ogi-feat--evm-api-for-item-d.workers-ogi.pages.dev/api/evm/item/0xa0e2bca2145b692670125dab579d5075f6a10473-16
- https://ogi-feat--evm-api-for-item-d.workers-ogi.pages.dev/api/evm/item/0x61fa91bc4df01c199f2c9576a2fe10ea206a55e1-33

code: https://github.com/kodadot/workers/pull/324/files

**Comment by preschian** [comment]
> Please can you do the test fixes and and max count in two separated prs?

sure, let me revert first

File: composables/drop/useGenerativeDropMint.ts (hunk 1 above)
Comment (Jarsen136) [reply composables/drop/useGenerativeDropMint.ts:43]: However, it does not work when I open the drop page on base, due to the API endpoint.
image


https://deploy-preview-10713--koda-canary.netlify.app/base/drops/quadz


> code: https://github.com/kodadot/workers/pull/324/files

It fetches the data directly from the contract on chain instead of API though 👀

Comment (preschian) [reply composables/drop/useGenerativeDropMint.ts:43]: Aah, I see. Sorry, I misunderstood your question before. Noted, I will add that also for evm based, either using sdk or api on ogi. then adjust it to something like this:

```
if (drop.value.collection) {
	if (substrate) {}
	if (evm) {}
}
```

Comment (preschian) [reply composables/drop/useGenerativeDropMint.ts:43]: wdyt?

Comment (Jarsen136) [reply composables/drop/useGenerativeDropMint.ts:43]: > Aah, I see. Sorry, I misunderstood your question before. Noted, I will add that also for evm based, either using sdk or api on ogi. then adjust it to something like this:
> 
> ```
> if (drop.value.collection) {
> 	if (substrate) {}
> 	if (evm) {}
> }
> ```

Yeah that's a good idea 👍

**Review by hassnian — APPROVED** [review]
code LGTM

cc @vikiival since he posted https://github.com/kodadot/ops-internal/discussions/1745#discussioncomment-9892060

**Comment by vikiival** [comment]
> sure, let me revert first

waiting for 
> the test fixes

File: composables/drop/useGenerativeDropMint.ts (hunk 1 above)
Comment (preschian) [reply composables/drop/useGenerativeDropMint.ts]: updated, requires this deployment: https://github.com/kodadot/workers/pull/324

Comment (Jarsen136) [reply composables/drop/useGenerativeDropMint.ts]: Nice! Let me know when I can test it.

**Comment by preschian** [comment]
Updates: I refactored some stuff on composable for drops. and, I just found out that this composable prevents the user from closing the modal `composables/useModalIsOpenTracker.ts`

**Comment by Jarsen136** [comment]
> Updates: I refactored some stuff on composable for drops. and, I just found out that this composable prevents the user from closing the modal `composables/useModalIsOpenTracker.ts`

I also find this error when I'm working on another issue. Here is how I solved it. WDYT https://github.com/kodadot/nft-gallery/pull/10772/commits/643eb8e5f8e6deeb9771ea4c3ac6a4b233885095

**Review by Jarsen136 — APPROVED** [review]

File: components/drops/useDrops.ts [hunk 2]
```diff
@@ -11,6 +10,8 @@ import type { DropItem } from '@/params/types'
 import { prefixToToken } from '@/components/common/shoppingCart/utils'
 import { useDropStore } from '@/stores/drop'
 import { getChainName } from '@/utils/chain'
+import { subCollection } from '~/utils/onchain/sub'
+import { evmCollection } from '~/utils/onchain/evm'
```
Comment (hassnian) [inline components/drops/useDrops.ts:14]:
```suggestion
import { subCollection } from '@/utils/onchain/sub'
import { evmCollection } from '@/utils/onchain/evm'
```

File: components/drops/useDrops.ts [hunk 3]
```diff
@@ -181,6 +183,28 @@ export function useDrop(alias?: string) {
...
+        const { urlPrefix } = usePrefix()
+        const address = drop.value.collection as `0x${string}`
+        const { maxSupply: supply, metadata, minted } = await evmCollection(address, urlPrefix.value)
+
+        drop.value.max = supply
+        drop.value.minted = minted
+        drop.value.collectionName = metadata.name
+        drop.value.collectionDescription = metadata.description
+      }
+    }
```
Comment (hassnian) [inline components/drops/useDrops.ts:207]: I would avoid nesting ifs were posible

```suggestion
    if (!drop.value.collection) {
       return
    }
    
     if (isSub.value) {
      const { maxSupply: supply, minted, metadata } = await subCollection(drop.value.collection)

      drop.value.max = supply
      drop.value.minted = minted
      drop.value.collectionName = metadata.name
      drop.value.collectionDescription = metadata.description
    }

    if (isEvm.value) {
      const { urlPrefix } = usePrefix()
      const address = drop.value.collection as `0x${string}`
      const { maxSupply: supply, metadata, minted } = await evmCollection(address, urlPrefix.value)

      drop.value.max = supply
      drop.value.minted = minted
      drop.value.collectionName = metadata.name
      drop.value.collectionDescription = metadata.description
    }
```

File: composables/useModalIsOpenTracker.ts [hunk 4]
```diff
@@ -17,8 +17,13 @@ export default ({
   onClose?: boolean
 }) => {
   watch([isOpen, () => and], ([isOpen, and]) => {
-    if (!isOpen === onClose && and.every(Boolean)) {
-      ;(onClose ? onModalAnimation(onChange) : onChange)()
+    try {
```
Comment (hassnian) [inline composables/useModalIsOpenTracker.ts:20]: I like jersen's solution

File: utils/onchain/evm.ts [hunk 5]
```diff
@@ -0,0 +1,51 @@
...
+import { getEvmCollection } from '@/services/ogi'
+
+export const wagmiConfig = createConfig({
+  chains: [base, immutableZkEvm],
+  transports: {
+    [base.id]: http(),
+    [immutableZkEvm.id]: http(),
+  },
+})
+
```
Comment (hassnian) [inline utils/onchain/evm.ts:14]: can we use the same wagmi config? useWagmi()

**Review by hassnian — APPROVED** [review]
small, otherwise LGTM

**Comment by preschian** [comment]
> I also find this error when I'm working on another issue. Here is how I solved it. WDYT [643eb8e](https://github.com/kodadot/nft-gallery/commit/643eb8e5f8e6deeb9771ea4c3ac6a4b233885095)

oh, I like yours

File: components/drops/useDrops.ts (hunk 3 above)
Comment (preschian) [reply components/drops/useDrops.ts:207]: oh, agree, that's a better one. let me update

File: utils/onchain/evm.ts (hunk 5 above)
Comment (preschian) [reply utils/onchain/evm.ts:14]: any idea why I can't use config from useWagmi()? it throw error on readContract

Comment (preschian) [reply utils/onchain/evm.ts:14]: Oh, I just saw this PR: https://github.com/kodadot/nft-gallery/pull/10762/files
. It will probably work once that one is merged. Since there is wagmi config in the plugin

**Comment by hassnian** [comment]
added #10804 see [context](https://github.com/kodadot/nft-gallery/issues/10804#issuecomment-2288445755)

@preschian you've got some conflicts
@vikiival  can we merge,

**Comment by vikiival** [comment]
> @vikiival can we merge,
Y

**Comment by preschian** [comment]
merging this~
