### PR TITLE
fix: default select on bsx and missing i18 on select option

### LINKED ISSUE #3542: BSX profile page does not default selected
### What happened?

as title mentioned.

### Please reproduce in steps

On bsx chain, go to profile page.

### Expected Behavior

Should be selected as first one or from url query params.

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### At which chain did you encounter bug?

_No response_

### Screenshots

image

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by KngZhi**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3542 #3557
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [x] I found edge cases
- [x] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer?target=DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

#### On BSX
image
#### On KSM
image

### CODE REVIEW

File: components/rmrk/Gallery/PaginatedCardList.vue [hunk 1]
```diff
@@ -136,6 +136,9 @@ export default class PaginatedCardList extends mixins(
 
   created() {
     this.fetchPageData(this.startPage)
+    if (this.client === 'bsx') {
+      this.searchQuery.sortBy = this.remapSortBy
+    }
```
Comment (kkukelka) [inline components/rmrk/Gallery/PaginatedCardList.vue:141]: 1. please check if `this.urlPrefix` is available and use it instead

2. we should add a `@Watch` for when user changes client.

**Review by kkukelka — CHANGES_REQUESTED** [review]

**Review by JustLuuuu — APPROVED** [review]
wfm

File: components/rmrk/Gallery/PaginatedCardList.vue (hunk 1 above)
Comment (KngZhi) [reply components/rmrk/Gallery/PaginatedCardList.vue:141]: for 2. maybe we don't need to. Since after the user change client, it would redirect to homepage.

**Review by kkukelka — APPROVED** [review]
works for me

File: components/rmrk/Gallery/PaginatedCardList.vue (hunk 1 above)
Comment (kkukelka) [reply components/rmrk/Gallery/PaginatedCardList.vue]: gotcha!

**Comment by kkukelka** [comment]
pay 100

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 62.51 USD/KSM ~ 1.6 $KSM
🧗 [DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc](https://kusama.subscan.io/account/DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)
🔗 [0xeee88a52a68aa202318ae9475358ef60e108ce177983518a40735578a29da52f](https://kusama.subscan.io/extrinsic/0xeee88a52a68aa202318ae9475358ef60e108ce177983518a40735578a29da52f)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
pay 100

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 62.74 USD/KSM ~ 1.594 $KSM
🧗 [DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc](https://kusama.subscan.io/account/DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)
🔗 [0x6831eca9b485b429a1eadc8f7fe9a870eb364257e1a9a04011169a8815c1b8fb](https://kusama.subscan.io/extrinsic/0x6831eca9b485b429a1eadc8f7fe9a870eb364257e1a9a04011169a8815c1b8fb)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
