### PR TITLE
#5116 search fix

### LINKED ISSUE #5116: Nft and Collection search is not working, gives error
### What happened?

https://www.loom.com/share/61fadc939b2d43dcadf67e0db0de83cf

nft search is taking to the wrong url
collection search does nothing, notice the url, it doesnt change 

### Please reproduce in steps

.

### Expected Behavior

.

### What browsers are you seeing the problem on?

_No response_

### At which address did you encounter bug?

_No response_

### Are you logged in?

Yes

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

.

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5116
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

File: components/search/Search.vue [hunk 1]
```diff
@@ -176,6 +183,13 @@ export default class Search extends mixins(
     this.updateSearch(value)
   }
 
+  @Watch('name', { deep: true })
+  protected onSearchQueryChange(value) {
+    if (value) {
+      this.updateSearch(value)
+    }
+  }
```
Comment (Jarsen136) [inline components/search/Search.vue:191]: Which problem do these codes solve? I guess it's not that necessary.

Comment (prachi00) [reply components/search/Search.vue:191]: so currently, if you just write something, the url doesn't get updated and then you click on see all, nothing happens
this will update the url, so that when you click on see all, you see the correct results

Comment (Jarsen136) [reply components/search/Search.vue:191]: However, these changes would bring an extra problem. Whenever I type a single character, the search page would flush. We prefer the search page update when there is a `enter` or `blur` event. 
Kapture 2023-02-26 at 10 49 47

So I guess the better approach is to update the url query when you click see all. ( check `SearchSuggestion.vue`)

Comment (prachi00) [reply components/search/Search.vue:191]: okay yeah makes sense, I'll update on see all then

Comment (prachi00) [reply components/search/Search.vue]: updated

File: components/search/Search.vue [hunk 2]
```diff
@@ -176,6 +183,13 @@ export default class Search extends mixins(
     this.updateSearch(value)
   }
 
+  // @Watch('name', { deep: true })
+  // protected onSearchQueryChange(value) {
+  //   if (value) {
+  //     this.updateSearch(value)
+  //   }
+  // }
```
Comment (Jarsen136) [inline components/search/Search.vue:191]: Let's remove some unused changes

File: components/search/SearchSuggestion.vue [hunk 3]
```diff
@@ -37,9 +37,8 @@
           :to="{
             path: `/${urlPrefix}/explore/collectibles`,
             query: { ...$route.query },
-          }"
-          @click.native="$emit('close')">
-          <div :class="loadMoreItemClassName">
+          }">
+          <div :class="loadMoreItemClassName" @click="seeAllCollection">
```
Comment (Jarsen136) [inline components/search/SearchSuggestion.vue:41]: There is another `see all` button for the gallery items. Pls also add the click handler to it and rename `seeAllCollection` to `seeAllButtonHandler`

**Review by Jarsen136 — COMMENTED** [review]
otherwise lgtm

**Review by vikiival — CHANGES_REQUESTED** [review]
Agree with @Jarsen136

File: components/search/SearchSuggestion.vue (hunk 3 above)
Comment (roiLeo) [reply components/search/SearchSuggestion.vue]: @click event on `<div>` ?

File: components/search/SearchSuggestion.vue [hunk 4]
```diff
@@ -299,6 +298,20 @@ export default class SearchSuggestion extends mixins(PrefixMixin) {
...
   }
 
+  public updateSearchUrl() {
+    if (this.name) {
+      this.$router
+        .replace({
+          path: String(this.$route.path),
+          query: {
+            page: '1',
+            search: this.name || undefined,
```
Comment (roiLeo) [inline components/search/SearchSuggestion.vue:307]:
```suggestion
            search: this.name,
```
I don't think it would be undefined if we check `this.name` beforehand

File: components/search/Search.vue [hunk 5]
```diff
@@ -68,7 +68,14 @@
 </template>
 
 <script lang="ts">
-import { Component, Emit, Prop, Ref, mixins } from 'nuxt-property-decorator'
+import {
+  Component,
+  Emit,
+  Prop,
+  Ref,
+  Watch,
```
Comment (Jarsen136) [inline components/search/Search.vue:76]:
```suggestion
```

**Review by Jarsen136 — APPROVED** [review]

**Comment by Jarsen136** [comment]
@prachi00 Let's resolve the code conflicts.

**Review by vikiival — APPROVED** [review]

**Review by roiLeo — APPROVED** [review]
IMO `@click` event should be done on `<a />` or `<button />` for better accessibility

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 37.27 USD/KSM ~ 0.805 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x705143d1f36614b2490b1a0a585b4ec77111569e60246f33bbbd45537b6bac55](https://kusama.subscan.io/extrinsic/0x705143d1f36614b2490b1a0a585b4ec77111569e60246f33bbbd45537b6bac55)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
