### PR TITLE
fix: Drop page announcement on landing

### LINKED ISSUE #6490: Drop page announcement on landing
image

this is not ideal 
- from 502px width to lower 

- let's change it on the lower widths to different layout 
image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #6490

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed UI

image

### <samp>🤖 Generated by Copilot at 9bad4bc</samp>

Refactored `UnlockableLandingTag` component to improve responsiveness and added translation key for smaller screens.

### <samp>🤖 Generated by Copilot at 9bad4bc</samp>

> _`UnlockableLandingTag`_
> _Refactored for small screens_
> _A fresh mint in spring_

### CODE REVIEW

**Comment by exezbcz** [comment]
nice! 
can you please make the separator k-hovergrey in dark mode?

**Review by preschian — APPROVED** [review]

File: components/collection/unlockable/UnlockableLandingTag.vue [hunk 1]
```diff
@@ -35,25 +36,32 @@
...
 </template>
 
 <script lang="ts" setup>
-import { NeoIcon } from '@kodadot1/brick'
 const isUnlockableLandingTagVisible = true
+const { $i18n } = useNuxtApp()
+
+const { width } = useWindowSize()
+
+const isSmallSize = computed(() => width.value < 502)
```
Comment (daiagi) [inline components/collection/unlockable/UnlockableLandingTag.vue:56]: very specific number... 502
plus I find the name confusing
maybe something like ` smallWidth` or something?

File: styles/abstracts/_theme.scss [hunk 2]
```diff
@@ -37,6 +37,7 @@ $themes: (
     'blue-accent-bg-color': #b6cbff,
     'blue-light-hover-color': #e8edfb,
     'card-hover-opacity': 0.85,
+    'separator-line-color': #cccccc,
```
Comment (daiagi) [inline styles/abstracts/_theme.scss:40]: can't reuse an existing color?

**Review by daiagi — CHANGES_REQUESTED** [review]

File: components/collection/unlockable/UnlockableLandingTag.vue (hunk 1 above)
Comment (Jarsen136) [reply components/collection/unlockable/UnlockableLandingTag.vue:56]: Number `502` is from the description of the original issue.

As for the naming, it's ok to change.

File: styles/abstracts/_theme.scss (hunk 2 above)
Comment (Jarsen136) [reply styles/abstracts/_theme.scss:40]: #cccccc in white mode and #6b6b6b in dark mode. There is no existing colour to be used.

**Review by daiagi — APPROVED** [review]

File: components/collection/unlockable/UnlockableLandingTag.vue (hunk 1 above)
Comment (exezbcz) [reply components/collection/unlockable/UnlockableLandingTag.vue]: Yup, that's where the pill shape announcement changes its layout to the two-row

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $10 @ 5.13 USD/DOT ~ 1.949 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x32c9062ee3720625ab7815c9e41282232cf13d46a96d207a0bad30ba3be03426](https://polkadot.subscan.io/extrinsic/0x32c9062ee3720625ab7815c9e41282232cf13d46a96d207a0bad30ba3be03426)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
