### PR TITLE
fix: paid mint modal stuck on loading

### LINKED ISSUE #10783: super long loading of the first modal for drop mint
image

what is taking the longest for the modal to load? balances? 
- it seems like it could have the data already but is stuck

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #10783

## QA check

- @exezbcz please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

https://github.com/user-attachments/assets/8e8133c0-749b-44be-bfc7-4df9b261d1f0

### CODE REVIEW

File: stores/identity.ts [hunk 1]
```diff
@@ -142,14 +143,19 @@ export const useIdentityStore = defineStore('identity', {
       const { isTestnet } = usePrefix()
       const { multiBalanceAssets, multiBalanceAssetsTestnet }
         = storeToRefs(useIdentityStore())
-      const { availableChainsByVm } = useChain()
+      const { vm } = useChain()
+
+      // useChain().availableChainsByVm excludes disabled chains like dot
+      const vmChains = chainList().filter(
```
Comment (vikiival) [inline stores/identity.ts:149]: Should be computed or?

**Review by vikiival — COMMENTED** [review]
just claryfying

File: stores/identity.ts (hunk 1 above)
Comment (hassnian) [reply stores/identity.ts:149]: `vm` is a computed 

CleanShot 2024-08-13 at 09 53 42@2x

**Review by vikiival — APPROVED** [review]
