### PR TITLE
bug fix in explore sort

### LINKED ISSUE #5222: it is possible to select contradicting options in explore sort
image
 introduced in PR #5158

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5222 
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by daiagi** [comment]
> why was this section removed anyway?
> 
> https://github.com/kodadot/nft-gallery/blob/6d8b9fc2d59f5f95080ffcf6f2ab5934bf4a7dc6/components/explore/ExploreSort.vue#L68-L86
> 
> update: I miss this section when reviewing #5158 just revert that section should be fixed right?

I removed it and i shouldn't have
I just rewrote the same functionality in different code style 

if you prefer, i can restore it to how it was

**Review by vikiival — COMMENTED** [review]
.

**Comment by daiagi** [comment]
OK. I'll restore it to how it was before

File: components/explore/ExploreSort.vue [hunk 1]
```diff
@@ -71,16 +71,23 @@ const options = computed(() => {
...
+    const opt = option.split('_')
+    const identifier = opt[0]
+    const sort = opt[1]
+
+    uniqueOptions[identifier] = sort
+  })
+
+  return Object.keys(uniqueOptions).map((identifier) => {
+    return `${identifier}_${uniqueOptions[identifier]}`
+  })
```
Comment (Jarsen136) [inline components/explore/ExploreSort.vue:90]:
```suggestion

  return Array.from(new Set(options))
```

How about removing duplicate item in this way? It would be more simple and easy to read I guess

Comment (daiagi) [reply components/explore/ExploreSort.vue:90]: no. that will not do...
for example, sorting by recently created is ```blockNumber_DESC``` and sort by oldest is ```blockNumber_ASC```
the unique bit is ```blockNumber``` and only one option should be allowed
by mapping the array into object, we keep only the latest selected sort option, which makes sense

image

Comment (Jarsen136) [reply components/explore/ExploreSort.vue:90]: oh, nvm. I should have read the original issue description : )

**Review by Jarsen136 — APPROVED** [review]
wfm

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
pay 25 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $25 @ 31.96 USD/KSM ~ 0.782 $KSM
🧗 [EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L](https://kusama.subscan.io/account/EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L)
🔗 [0x4c44bb5d9b53fb19b92ce99503e720c3b65a1e3bf58412ab64fedbe5e52ed75e](https://kusama.subscan.io/extrinsic/0x4c44bb5d9b53fb19b92ce99503e720c3b65a1e3bf58412ab64fedbe5e52ed75e)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
