### PR TITLE
After minting, user does not get redirect to NFT and Error when trying to massmint on RMRK2

### LINKED ISSUE #6508: Error when trying to massmint on RMRK2
### What happened?

image

### Please reproduce in steps

RMRK2 -> Create -> Massmint

### Expected Behavior

should massmint

### What browsers are you seeing the problem on?

Desktop Firefox

### At which address did you encounter bug?

canary.kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

^

### Relevant log output

```shell
Error: createType(Call):: Call: failed decoding utility.batchAll:: Struct: failed on args: {"calls":"Vec"}:: Struct: failed on calls: Vec:: Call: Cannot decode value 'RMRK::MINT::2.0.0::%7B%22name%22%3A%22Land%201%22%2C%22sn%22%3A%2200000006%22%2C%22transferable%22%3A1%2C%22collection%22%3A%227EA1DCF47E98A25067-RPG%22%2C%22metadata%22%3A%22ipfs%3A%2F%2Fipfs%2Fbafkreibmty2xvlwntxiwbirbtt3ap437orasiqqve5fk5z6oc57b7vrjri%22%2C%22symbol%22%3A%22LAND_1%22%2C%22properties%22%3A%7B%7D%2C%22currentOwner%22%3A%22FSMdmCLv5gFZ87YerB3M8ZSQ58BGHdSnreC4J6znWpqPQK9%22%7D' of type string
```

### Payment link for reward

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #6526: After minting, user does not get redirect to NFT
### What happened?

Happening on RMRK1 and 2 and also massmint: 

https://github.com/kodadot/nft-gallery/assets/36627808/b1a5c533-8b27-4fd0-bcc4-de33c37a33b8

### Please reproduce in steps

RMRK1 or 2 -> mint NFT

### Expected Behavior

it should redirect to the minted NFT

### What browsers are you seeing the problem on?

Firefox

### At which address did you encounter bug?

canary.kodadot.xyz

### PR DESCRIPTION
**Pull request by hassnian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #6526 
  - Now it redirects when creating a NFT using the classic UI
  - Redirect inside massmint worked for me 
- [x] Closes #6508
  - I also fixed this , since I couldn't mint tokens via massmint

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; 

### <samp>🤖 Generated by Copilot at d0045a1</samp>

This pull request enables minting NFTs without listing them for sale, and improves the compatibility and validity of the arguments for the batched minting transactions. It refactors the `CreateToken` component and the `transactionMintRmrk` composable.

### <samp>🤖 Generated by Copilot at d0045a1</samp>

> _Sing, O Muse, of the crafty code that the heroes wrought_
> _To mint new tokens of their art, with skill and cunning fraught_
> _They filtered out the false and wrapped the args in `system.remark`_
> _To execute a batch of transactions, swift and smooth as a shark_

### CODE REVIEW

File: composables/transaction/mintToken/transactionMintRmrk.ts [hunk 1]
```diff
@@ -157,7 +157,14 @@ export async function execMintRmrk({
 
   const isSingle = args.length === 1
   const cb = isSingle ? api.tx.system.remark : api.tx.utility.batchAll
-  const arg = isSingle ? args : [args]
+
+  const arg = isSingle
+    ? args
+    : [
+        args
+          .filter((arg) => arg)
```
Comment (vikiival) [inline composables/transaction/mintToken/transactionMintRmrk.ts:165]: filter(Boolean)

Comment (hassnian) [reply composables/transaction/mintToken/transactionMintRmrk.ts]: fixed

**Comment by prury** [comment]
**RMRK2**
Classic minting redirection - ✔️ 
Massmint redirection - ✔️ 
Massmint process: ✔️ 
https://kusama.subscan.io/tx/0x89e4c54c91b3704f553ac4900153787080a4f221374ec4f9245869a01d49fd02 
massminted NFTs: https://deploy-preview-6570--koda-canary.netlify.app/ksm/collection/7EA1DCF47E98A25067-RPG 

**RMRK1**
Classic minting redirection - ✔️ 
Simple minting redirection - ✔️
Massmint redirection - ✔️ 

Tester account: 
https://kusama.subscan.io/account/FSMdmCLv5gFZ87YerB3M8ZSQ58BGHdSnreC4J6znWpqPQK9

**Comment by yangwao** [comment]
pay 70 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $70 @ 4.98 USD/DOT ~ 14.056 $DOT
🧗 [16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD](https://polkadot.subscan.io/account/16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)
🔗 [0x89b242924559dc53209c2fdf872b0ff4b1ee0a9b3edf2e5626cac82ae86097a7](https://polkadot.subscan.io/extrinsic/0x89b242924559dc53209c2fdf872b0ff4b1ee0a9b3edf2e5626cac82ae86097a7)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
