### PR TITLE
fix: massmint not checking balance when minting

### LINKED ISSUE #11189: Massmint not checking balance
a couple of weeks ago patricia was having issues mass-minting a large amount of NFTs 

apparently she had enough funds on-chain but she could not mint (transaction would fail), after checking her address she did not have funds on `AHP` after transferring funds to her wallet everything worked.   

that's how I found that the **massmint does not check the user balance at all** 

it should 

1. take minting cost (**itemDeposit** and a **base transaction fee**) into consideration
2. ideally support auto-teleport  

_Originally posted by @hassnian in https://github.com/kodadot/nft-gallery/issues/11188#issuecomment-2502633458_

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

> take minting cost (itemDeposit and a base transaction fee) into consideration

- [x] Closes #11189

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2024-11-27 at 11 01 49@2x

### CODE REVIEW

**Comment by hassnian** [comment]
a couple of weeks ago patricia was having issues mass-minting a large amount of NFTs 

apparently she had enough funds on-chain bet she could not mint (transaction would fail), after checking her address she did not have funds on `AHP` after transferring funds to her wallet everything worked.   

that's how I found that the **massmint does not check the user balance at all** 

it should 

1. take minting cost (**itemDeposit** and a **base transaction fee**) into consideration
2. ideally support auto-teleport

File: components/massmint/Massmint.vue [hunk 1]
```diff
@@ -146,9 +149,13 @@ const mintModalOpen = ref(false)
 const MobileDisclaimerModalOpen = ref(false)
 const smallerThenDesktop = computed(() => width.value < 1024)
 
+const transactionFee = ref(0)
 const isMinting = ref(false)
 const mintStatus = ref('')
 
+const neededAmount = computed(() => (itemDeposit.value * Object.keys(NFTS.value).length) + transactionFee.value)
```
Comment (vikiival) [inline components/massmint/Massmint.vue:156]: Either add metada deposit into calculation or 10% premium 
(neededAmount * 1.1)

**Review by vikiival — APPROVED** [review]
Otherwise amaziiiing!
