### PR TITLE
Mobile menu not opening/closing well #932

### LINKED ISSUE #932: Mobile menu not opening/closing well
**Describe the bug**
When on mobile, menu is not closing when you click on page link or outside dropdown.

**To Reproduce**
1. Go to mobile version of website
2. Click on menu
3. Click outside menu or click a link

**Expected behavior**
Menu should close

**Smartphone (please complete the following information):**
 - OS: Android
 - Browser:  Firefox (menu not working), Chrome (menu not closing)

### PR DESCRIPTION
**Pull request by TK-Development**
**Thank you for your contribution** to the KodaDot NFT gallery.
Let's do a quick check before the merge.
Your contribution will be an eternal part of the community codebase.

### PR type
- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### Before submitting this PR, please make sure:
- [x] Code builds clean without any errors or warnings
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've didn't break any original functionality
- [ ] I've posted screenshot of demonstrated change in this PR

### Optional
- [x] I've tested it on mobile and everything works
- [ ] I found edge cases

### What's new? (may be part of changelog)
- This PR closes #932 - :close-on-click option wasn't true so I set it true.

### If issue had bounty label ($,$$,$$$)
- Fill up your KSM address: https://kodadot.xyz/transfer/?target=<Kusama_Address> 

### Community participation
- [x] Are you at KodaDot Discord? If not yet, [let's join us - https://discord.gg/35hzy2dXXh](https://discord.gg/35hzy2dXXh)

### Screenshot
- [x] Whenever my fix has changed **something** on UI, a screenshot for others, is more than welcome

### CODE REVIEW

File: src/components/Navbar.vue [hunk 1]
```diff
@@ -3,7 +3,7 @@
     fixed-top
     spaced
     wrapper-class="container"
-    :close-on-click="false"
+    :close-on-click="true"
```
Comment (roiLeo) [inline src/components/Navbar.vue:6]: I would personally use
```suggestion
    close-on-click
```

**Review by roiLeo — APPROVED** [review]
LGTM

File: src/components/Navbar.vue (hunk 1 above)
Comment (TK-Development) [reply src/components/Navbar.vue:6]: Great
It also works fine.
Thanks, roiLeo
