### PR TITLE
fix: component files resolving to the same name

### LINKED ISSUE #6182: Warn: Two component files resolving to the same name
continue #6137, step to reproduce:

run `pnpm dev` 

```bash
 WARN  Two component files resolving to the same name CollectionBanner: 
 WARN  Two component files resolving to the same name CollectionInfo:
```

### PR DESCRIPTION
**Pull request by Jarsen136**
closed #6182

### CODE REVIEW

File: components/collection/unlockable/UnlockableContainer.vue [hunk 1]
```diff
@@ -157,7 +157,7 @@
 </template>
 
 <script setup lang="ts">
-import UnlockableCollectionInfo from '@/components/collection/unlockable/CollectionInfo.vue'
+import UnlockableCollectionInfo from '~~/components/collection/unlockable/UnlockableCollectionInfo.vue'
```
Comment (roiLeo) [inline components/collection/unlockable/UnlockableContainer.vue:160]:
```suggestion
import UnlockableCollectionInfo from '@/components/collection/unlockable/UnlockableCollectionInfo.vue'
```

File: layouts/unlockable-mint-layout.vue [hunk 2]
```diff
@@ -13,7 +13,7 @@
 </template>
 
 <script lang="ts" setup>
-import UnlockableCollectionBanner from '@/components/collection/unlockable/CollectionBanner.vue'
+import UnlockableCollectionBanner from '~~/components/collection/unlockable/UnlockableCollectionBanner.vue'
```
Comment (roiLeo) [inline layouts/unlockable-mint-layout.vue:16]:
```suggestion
import UnlockableCollectionBanner from '@/components/collection/unlockable/UnlockableCollectionBanner.vue'
```

**Review by roiLeo — APPROVED** [review]

**Review by vikiival — APPROVED** [review]
