### PR TITLE
fix: Collection incomplete text

### LINKED ISSUE #9351: Collection incomplete text
Im asking for a small cosmetic change
---

As we are not able to always show whole description of collection in collection preview, it would be nice if we can make look this bit better:

Screenshot 2024-02-10 at 12 38 43

1) Is it possible to set in case of a longer description that we will not be cutting words in the middle like in the picture? The "cut" will be only between words?
2) Is it possible to add three dots after the text?

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix
  
  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #9351

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI
image

  ## Copilot Summary
  copilot:summary

  copilot:poem

### CODE REVIEW

File: utils/parse.ts [hunk 1]
```diff
@@ -9,3 +9,9 @@ export const extractTwitterIdFromDescription = (desc: string = '') => {
 
   return ''
 }
+
+export const removeSuffixFromString = (content: string = '') => {
+  const words = content.split(' ')
```
Comment (roiLeo) [inline utils/parse.ts:14]: Imo it possible to chain fonction (string.split().pop()....)

**Review by roiLeo — APPROVED** [review]

File: utils/parse.ts (hunk 1 above)
Comment (Jarsen136) [reply utils/parse.ts:14]: image
It could not be that because the pop function only return the last element.

**Comment by prury** [comment]
https://deploy-preview-9356--koda-canary.netlify.app/ahp/collection/82

image

on the alchemy collection, it cuts on `elegan` and does not show the three dots

**Comment by Jarsen136** [comment]
> /ahp/collection/82 on the alchemy collection, it cuts on elegan and does not show the three dots

✅ Fixed

**Review by preschian — APPROVED** [review]

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 7.64 USD/DOT ~ 3.927 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x40123267ab9398cf069a9e80bc1342917cd6bf885f4b17dac9620623e1e049c8](https://polkadot.subscan.io/extrinsic/0x40123267ab9398cf069a9e80bc1342917cd6bf885f4b17dac9620623e1e049c8)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
