### PR TITLE
fix: `koda.art` is using beta workers

### LINKED ISSUE #10486: Profiles: Issue with profile creation
Artist Buitrago had issue:
- https://koda.art/ahp/u/15GcteQcQbLtWQA1zEJyUpGk3Ehjqod4R9zwLJvxbLgLo7wm

Message from him: I clicked "Create Profile", then I clicked "Import from Farcaster", then I filled all the data, and then clicked "Finish customization" and the error appears.

### LINKED ISSUE #10495: `koda.art` is using beta workers
### What happened?

CleanShot 2024-06-19 at 12 27 20@2x

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #10495
- [x] Closes #10486

## Needs QA check

- @kodadot/qa-guild please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [ ] My fix has changed **something** on UI;

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]

File: utils/env.ts [hunk 1]
```diff
@@ -0,0 +1,4 @@
+export const isProduction = ['kodadot.xyz', 'koda.art'].includes(
+  window.location.hostname,
+)
+export const isBeta = window.location.hostname === 'beta.kodadot.xyz'
```
Comment (preschian) [inline utils/env.ts:4]: `beta.koda.art`, just in case we have that one later

**Review by preschian — APPROVED** [review]

File: utils/env.ts (hunk 1 above)
Comment (vikiival) [reply utils/env.ts:4]: cc @hassnian

Comment (hassnian) [reply utils/env.ts]: done

**Review by vikiival — APPROVED** [review]
