### PR TITLE
Fix/multiple-reloads

### LINKED ISSUE #9648: Monotif Test drop generating various previews on refresh
https://canary.kodadot.xyz/ahk/drops/monotifs

https://github.com/kodadot/nft-gallery/assets/36627808/8386401f-86a2-489d-9630-61155125f3a6

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #9648

## Links
[monotifs](https://deploy-preview-9655--koda-canary.netlify.app/ahk/drops/monotifs)
[alteration](https://deploy-preview-9655--koda-canary.netlify.app/ahk/drops/alteration)

## Notes
1. Usually it is better to use css to toggle visibilty, but not in this case. `GenerativePreview` is emitting messages, having 2 instances in the page is causing unexpcted behviours
2. yes, it is ugly to use `setTimeout` but in makes the first variation of the art to load consistently, i guess the code in the iframe needs a moment to load

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

## Screenshot 📸

- [ ] My fix has changed UI

### CODE REVIEW

File: components/collection/drop/GenerativeLayout.vue [hunk 1]
```diff
@@ -127,6 +130,9 @@ const props = withDefaults(
   },
 )
 
+const { width } = useWindowSize()
```
Comment (preschian) [inline components/collection/drop/GenerativeLayout.vue:133]: why do we introduce this again? unrelated changes?

ref: https://github.com/kodadot/nft-gallery/issues/8767

File: components/collection/drop/GenerativePreview.vue [hunk 2]
```diff
@@ -180,15 +180,11 @@ watch(imageDataLoaded, () => {
...
-  () => {
-    generateNft()
-  },
-  {
-    immediate: true,
-  },
-)
+watch(accountId, generateNft)
+
+onMounted(() => {
```
Comment (preschian) [inline components/collection/drop/GenerativePreview.vue:185]: do these changes fix the issue? it was reloaded because of this line right? https://github.com/kodadot/nft-gallery/blob/684296e5550708088f24ef1863f8c26b0169ce73/components/collection/drop/GenerativePreview.vue#L192-L194

File: components/collection/drop/GenerativeLayout.vue (hunk 1 above)
Comment (daiagi) [reply components/collection/drop/GenerativeLayout.vue:133]: not unrelated at all

see my notes above in PR description

File: components/collection/drop/GenerativePreview.vue (hunk 2 above)
Comment (daiagi) [reply components/collection/drop/GenerativePreview.vue:185]: >do these changes fix the issue?

yes, that's why i made them

please, try for yourself 

>it was reloaded because of this line right

yes, but simple removal of it introduces the problem you solved by adding it

addition of the timeout causes your watcher to never trigger as far as i could tell while playing with it

if you wanna YOLO we can remove the watcher

Comment (preschian) [reply components/collection/drop/GenerativePreview.vue:185]: I think it was fixed with your changes on `components/collection/drop/GenerativeLayout.vue`, right? so, no need this changes?

Comment (preschian) [reply components/collection/drop/GenerativePreview.vue:185]: > addition of the timeout causes your watcher to never trigger as far as i could tell while playing with it

I couldn't see any difference in this. It seems like both still trigger the watcher. Or is there a code example I can test?

Comment (daiagi) [reply components/collection/drop/GenerativePreview.vue:185]: 1. without it, first image shown is always same (not a unique variation)
image

2.  with `immediate: true`, this happens often (not always)
```js
watch(accountId, generateNft, { immediate: true })

// onMounted(() => {
//   setTimeout(generateNft, 1000)
// })
```

image


**3. with setTimeout, first image is unique and loads well**

Comment (preschian) [reply components/collection/drop/GenerativePreview.vue:185]: Oh, maybe it's way harder to reproduce? It already looks good on my local if I revert this file. But, let's proceed with this anyway

Comment (daiagi) [reply components/collection/drop/GenerativePreview.vue:185]: i get why you don't like the `setTimeout`
I'm not too big on it either

but it produces better end result in this case

**Review by preschian — APPROVED** [review]
> Usually it is better to use css to toggle visibilty, but not in this case. GenerativePreview is emitting messages, having 2 instances in the page is causing unexpcted behviours

nice finding, this one quite important issue tho 👍🏻

File: components/collection/drop/GenerativePreview.vue (hunk 2 above)
Comment (preschian) [reply components/collection/drop/GenerativePreview.vue:185]: > i get why you don't like the setTimeout
> without it, first image shown is always same (not a unique variation)

nah, I'm good as long it can fix the issue. I think it's because you already fixed the important issue with the race condition on emit, seems like it's quite harder to reproduce (good thing). It looks good on my local, even though I always get a unique variant if I revert this file. 🤣

> but it produces better end result in this case

yes, I don't want to take a risk. Let's continue with it.

**Review by Jarsen136 — APPROVED** [review]

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 10.31 USD/DOT ~ 2.91 $DOT
🧗 [1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8](https://polkadot.subscan.io/account/1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)
🔗 [0x95f8d068e744eee9109cb496b284800a58e37bef7a84803d751d731b031353fe](https://polkadot.subscan.io/extrinsic/0x95f8d068e744eee9109cb496b284800a58e37bef7a84803d751d731b031353fe)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
