### PR TITLE
fix: Can't change chain from profile page

### LINKED ISSUE #11192: Can't change chain from profile page
### What happened?

CleanShot 2024-11-28 at 11 48 49

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

remove once we have multi-vm profiles working

- [x] Closes #11192

### changing prefix from  chain selector

- fix: going from `EVM` to `SUB` or the other way will redirect to `/` 

### changing prefix from wallet connect

- fix: connecting a new wallet not prefix change, no redirect **(still the same)**
   -  ❗️ 6842ba7e7aa7759dfd63a0376e662ae3d3152d60 has been removed. cc @Jarsen136 

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

https://github.com/user-attachments/assets/2a0f9af1-a505-406b-a5ed-3a141cec9717

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]

File: components/common/ConnectWallet/ConnectWalletModal.vue [hunk 1]
```diff
@@ -56,10 +56,14 @@ import WalletAsset from '@/components/common/ConnectWallet/WalletAsset.vue'
 import { ModalCloseType } from '@/components/navbar/types'
 import { arePrefixesOfSameVm } from '@/utils/config/chain.config'
 
+const NO_PREFIX_CHNAGE_ROUTES_NAMES = [
```
Comment (preschian) [inline components/common/ConnectWallet/ConnectWalletModal.vue:59]: small typo

**Review by preschian — APPROVED** [review]

File: components/common/ConnectWallet/ConnectWalletModal.vue (hunk 1 above)
Comment (hassnian) [reply components/common/ConnectWallet/ConnectWalletModal.vue]: fixed [ce72171](https://github.com/kodadot/nft-gallery/pull/11193/commits/ce7217124b982494aae452a68318777c2061f0f0)
