### PR TITLE
🐛 broken explorer link

### LINKED ISSUE #7684: Seems gallery item doesn't load?
https://canary.kodadot.xyz/ahk/gallery/169-4e5d739e2fad9295b1edd6f2197eac08

image

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #7684
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

## Screenshot 📸

- [ ] My fix has changed UI

### <samp>🤖 Generated by Copilot at fcce151</samp>

This pull request enhances the `NeoNftCard` component and its subcomponents to support custom card link URLs and stacked NFTs. It also introduces a new type `NeoNFT` to unify the token data structure and simplify the code. It affects the files `NeoNftCard.vue`, `NFTMediaInfo.vue`, `NFTMediaInfoStacked.vue`, `types.ts`, and `ItemsGridImageTokenEntity.vue`.

### <samp>🤖 Generated by Copilot at fcce151</samp>

> _Sing, O Muse, of the skillful coder who wrought_
> _Many a change to the `NeoNftCard` component,_
> _Adding new props and types to shape the token data,_
> _And customizing the link to each NFT's content._

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
https://github.com/kodadot/nft-gallery/issues/7684#issuecomment-1764759481

Capture d’écran 2023-10-17 à 8 40 22 AM

**Review by roiLeo — APPROVED** [review]

File: libs/ui/src/components/NeoNftCard/NFTMediaInfo.vue [hunk 1]
```diff
@@ -12,11 +12,12 @@
       <CollectionDetailsPopover
         v-if="nft.collection.name || nft.collection.id"
         :show-delay="collectionPopoverShowDelay"
+        class="is-size-7 nft-info-collection-name is-ellipsis"
         :nft="nft">
         <template #content>
           <nuxt-link
```
Comment (roiLeo) [inline libs/ui/src/components/NeoNftCard/NFTMediaInfo.vue:18]: nuxt-link in `libs/ui` 😢

Comment (roiLeo) [reply libs/ui/src/components/NeoNftCard/NFTMediaInfo.vue:18]: this clearly need rework as it depend on some stuff that is not inside libs/ui

Comment (daiagi) [reply libs/ui/src/components/NeoNftCard/NFTMediaInfo.vue:18]: 1. agree
2. CollectionDetailsPopover isn't new, it's been there since February : https://github.com/kodadot/nft-gallery/commit/5b59514de9baf102a929b0a0f187592ff4b15e58
3. ill change nuxt-link to `<a/>`

**Comment by yangwao** [comment]
@daiagi this alignment was solved in the past ?

image

**Comment by daiagi** [comment]
>this alignment was solved in the past ?

Not thoroughly enough.no 

I thought I did but the regular cards change height with screen size
