### PR TITLE
Changing network in navbar always redirects to Landing page

### LINKED ISSUE #6416: Changing network in navbar always redirects to Landing page
When I change network in navbar I am always redirected to Landing page. 

Actual behaviour:
So when I am scrolling through explore and want to check different network (i know we have network in filters) but even so, it takes me to Landing page. 

https://github.com/kodadot/nft-gallery/assets/95911767/38ce346f-302d-4196-82af-f89c60094735

Expected: when I change network in navbar, stay on current page.

### LINKED ISSUE #6659: Tables(content) are not refreshing when user changes chain
### What happened?

Part of #6613 
@hassnian implemented the global network change, but those pages do not get refreshed when the network changes, thus, showing the incorrect chain info. 
/series-insight/
/hot/
/sales/

https://github.com/kodadot/nft-gallery/assets/36627808/4130e05d-806d-466f-8b7d-f06fcf683c80

### Expected Behavior

it should show the correct information table of each chain

### PR DESCRIPTION
**Pull request by hassnian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [x] Feature
- [ ] Refactoring

## Context
- [x] Closes #6416
- [x] Closes #6659

Go to 
 - /prefix/create 
 - /blog/xxx 
 - /blog 
 - /_prefix/massmint 
 - /_prefix/massmint/onboarding
 - /sales
 - /hot
 - /series-insight
 - /chain/explore/collectibles
 - /chain/explore/items

and check what if the page is redirected to / or stays 

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

CleanShot 2023-08-08 at 14 19 29

### <samp>🤖 Generated by Copilot at f71db16</samp>

This pull request improves the user experience of switching chains on the navbar by adding logic to the `ChainSelectDropdown` component and moving the `usePrefix` composable to the component file.

### <samp>🤖 Generated by Copilot at f71db16</samp>

> _Sing, O Muse, of the skillful coder who devised_
> _A clever composable, `usePrefix`, and moved it with care_
> _To the `ChainSelectDropdown`, where it fit well and thrived_
> _And helped the user navigate the chains with flair._

### CODE REVIEW

File: components/navbar/ChainSelectDropdown.vue [hunk 1]
```diff
@@ -25,17 +25,29 @@
...
+
 const selected = computed({
   get: () => urlPrefix.value,
   set: (value) => {
     prefrencesStore.setNotificationBoxCollapse(false)
     setUrlPrefix(value)
-    navigateTo(`/${value}`)
+
+    let newPath = `/${value}`
+    if (isExplorePage.value && isExplorePageAvailable(value)) {
```
[the remark this answers is not in the document]
Comment (hassnian) [reply components/navbar/ChainSelectDropdown.vue:46]: oh I didn't know about those , fixing now 

so /explore /hot /sales /series-insight would these be all of them ?

[the remark this answers is not in the document]
Comment (roiLeo) [reply components/navbar/ChainSelectDropdown.vue:46]: don't add them now as these pages are currently hidden.
in the case where we are likely to add them, are we going to add a check in this `if` case? or is there no better solution?

[the remark this answers is not in the document]
Comment (hassnian) [reply components/navbar/ChainSelectDropdown.vue:46]: maybe using some sort of map for each chain and each of these pages but that's also the same as an if else cleaner maybe not sure , I can do it if you want

File: utils/config/permision.config.ts [hunk 2]
```diff
@@ -24,10 +24,74 @@ const hasExplorer: Config<boolean> = {
...
+  ksm: true,
+  bsx: true,
+  stmn: true,
+  movr: true,
+  glmr: true,
+  snek: true,
+  dot: true,
+  stt: true,
+}
+
```
Comment (hassnian) [inline utils/config/permision.config.ts:62]: pls confirm these ones

**Comment by hassnian** [comment]
@prury pls check , both of them issues should work

**Comment by prury** [comment]
> @prury pls check , both issues should be fixed

Blog:

https://github.com/kodadot/nft-gallery/assets/36627808/eff5e419-3dc4-425c-8950-1bd099e9b9c9

/series-insight/

https://github.com/kodadot/nft-gallery/assets/36627808/902131b8-07da-49a8-ac1a-8e835cdeca34

File: composables/useChainRedirect.ts [hunk 3]
```diff
@@ -0,0 +1,163 @@
...
+  [PageType.PREFIX_MASSMINT]: (chain: Prefix) => massmintCreateVisible(chain),
+  [PageType.PREFIX_MASSMINT_ONBOARDING]: (chain: Prefix) =>
+    massmintCreateVisible(chain),
+  [PageType.SALES]: (chain: Prefix) => salesVisible(chain),
+  [PageType.HOT]: (chain: Prefix) => hotVisible(chain),
+}
+
+const getPagaType = (routeName: string): PageType => {
+  const matchingKey = Object.keys(PageType).find((key) => {
+    const pattern = PageType[key].replace(/\{.*\}/, '.+').replace('-', '\\-')
```
Comment (roiLeo) [inline composables/useChainRedirect.ts:76]: What does this regex do? I would use a proper naming

File: composables/useChainRedirect.ts [hunk 4]
```diff
@@ -0,0 +1,163 @@
...
+  [PageType.SERIES_INSIGHT]: (chain: Prefix) => seriesInsightVisible(chain),
+  [PageType.PREFIX_CLASSIC_CREATE]: (chain: Prefix) => createVisible(chain),
+  [PageType.PREFIX_MASSMINT]: (chain: Prefix) => massmintCreateVisible(chain),
+  [PageType.PREFIX_MASSMINT_ONBOARDING]: (chain: Prefix) =>
+    massmintCreateVisible(chain),
+  [PageType.SALES]: (chain: Prefix) => salesVisible(chain),
+  [PageType.HOT]: (chain: Prefix) => hotVisible(chain),
+}
+
+const getPagaType = (routeName: string): PageType => {
```
Comment (roiLeo) [inline composables/useChainRedirect.ts:74]: typo?

File: utils/config/permision.config.ts [hunk 5]
```diff
@@ -24,10 +24,74 @@ const hasExplorer: Config<boolean> = {
...
+const hasInsight: Config<boolean> = {
+  rmrk: true,
+  ksm: false,
+  bsx: true,
+  ahk: false,
+  movr: false,
+  glmr: false,
+  snek: false,
+  dot: false,
+  stt: false,
```
Comment (roiLeo) [inline utils/config/permision.config.ts:36]: `stt` has been replaced by `ahp` see #6631

File: utils/config/permision.config.ts [hunk 6]
```diff
@@ -24,10 +24,74 @@ const hasExplorer: Config<boolean> = {
...
 }
 
+const hasInsight: Config<boolean> = {
+  rmrk: true,
+  ksm: false,
+  bsx: true,
+  ahk: false,
+  movr: false,
+  glmr: false,
+  snek: false,
```
Comment (roiLeo) [inline utils/config/permision.config.ts:34]:
```suggestion
  snek: true,
```

File: utils/config/permision.config.ts [hunk 7]
```diff
@@ -24,10 +24,74 @@ const hasExplorer: Config<boolean> = {
...
+}
+
+const hasSales: Config<boolean> = {
+  rmrk: true,
+  ksm: true,
+  bsx: false,
+  ahk: false,
+  movr: false,
+  glmr: false,
+  snek: false,
```
Comment (roiLeo) [inline utils/config/permision.config.ts:46]: if `bsx` has it, `snek` should have it (bsx testnet)

File: composables/useChainRedirect.ts [hunk 8]
```diff
@@ -0,0 +1,163 @@
...
+  PREFIX_EXPLORE_ITEMS = '{prefix}-explore-items',
+  PREFIX_EXPLORE_COLLECTIBLES = '{prefix}-explore-collectibles',
+  SALES = 'sales',
+  HOT = 'hot',
+  SERIES_INSIGHT = 'series-insight',
+  BLOG = 'blog',
+  BLOG_SLUG = 'blog-slug',
+  PREFIX_MASSMINT = '{prefix}-massmint',
+  PREFIX_MASSMINT_ONBOARDING = '{prefix}-massmint-onboarding',
+  PREFIX_CLASSIC_CREATE = '{prefix}-create',
```
[the remark this answers is not in the document]
Comment (hassnian) [reply composables/useChainRedirect.ts:26]: so for some routes we do have the name prefix as a dynamic variable hence it uses `prefix` prefix
CleanShot 2023-08-10 at 07 24 59@2x

 but for the `{chain}-create` ones the prefix is not dynamic, when getting the name we get this

CleanShot 2023-08-10 at 07 23 15@2x


  `{prefix}` inside `PageType` its creating a "variable" part and then with the regex we can check if it matches or not

**Comment by hassnian** [comment]
@prury pls check , both issues should be fixed

**Comment by prury** [comment]
> @prury pls check , both issues should be fixed

thank you so much! 

i know i said i'll open a issue for both /hot and /sales, but i failed at explaining that they were not showing the correct information on that page(unrelated to this PR), but i still need you to redirect those pages when there is a network change if you could.

**Comment by hassnian** [comment]
> > @prury pls check , both issues should be fixed
> 
> 
> 
> thank you so much! 
> 
> 
> 
> i know i said i'll open a issue for both /hot and /sales, but i failed at explaining that they were not showing the correct information on that page(unrelated to this PR), but i still need you to redirect those pages when there is a network change if you could. We can make a followup issue for this if the PR is getting to big, lmk.
> 
> 
> 
> also, on mobile, when you change the network, the menu sidebar should close when choosing an option

what do you mean by by `but i still need you to redirect those pages when there is a network change if you could` , you mean refresh the content?

**Comment by prury** [comment]
> what do you mean by by `but i still need you to redirect those pages when there is a network change if you could` , you mean refresh the content?

yup

https://github.com/kodadot/nft-gallery/assets/36627808/f764646e-5c41-4814-abc3-025ae6085158

**Comment by prury** [comment]
> 



> 



> > > @prury pls check , both issues should be fixed
> > 
> > 
> > thank you so much!
> > i know i said i'll open a issue for both /hot and /sales, but i failed at explaining that they were not showing the correct information on that page(unrelated to this PR), but i still need you to redirect those pages when there is a network change if you could. We can make a followup issue for this if the PR is getting to big, lmk.
> > also, on mobile, when you change the network, the menu sidebar should close when choosing an option
> 
> I think they should be separate issues since the feature/bugfix it's already done and it's changing the chain globally those pages are not listening to chain changes , same issue as series-insights had, i can still fix it here if you want
> 
> what do you mean by by `but i still need you to redirect those pages when there is a network change if you could` , you mean refresh the content?



> > > what do you mean by by `but i still need you to redirect those pages when there is a network change if you could` , you mean refresh the content?
> > 
> > 
> > yup
> > 
> >   
> >     
> >     
> > 
> >     content.mp4
> 
> ok will fix it here

sorry for the trouble and thanks!

File: composables/useChainRedirect.ts [hunk 9]
```diff
@@ -0,0 +1,181 @@
...
+  [PageType.PREFIX_MASSMINT]: (chain: Prefix) => massmintCreateVisible(chain),
+  [PageType.PREFIX_MASSMINT_ONBOARDING]: (chain: Prefix) =>
+    massmintCreateVisible(chain),
+  [PageType.SALES]: (chain: Prefix) => salesVisible(chain),
+  [PageType.HOT]: (chain: Prefix) => hotVisible(chain),
+  [PageType.BLOG]: () => true,
+}
+
+const generateRouteRegexPattern = (pattern: string): string => {
+  const patternWithPlaceholderReplaced = pattern.replace(/\{.*\}/, '.+')
```
Comment (Jarsen136) [inline composables/useChainRedirect.ts:82]: Could you pls fix this warning?
image

File: composables/useChainRedirect.ts [hunk 10]
```diff
@@ -0,0 +1,181 @@
...
+      isPageAvailableForChain = pageAvailabilityCheck(newChain)
+    }
+
+    if (isStayRedirect && isPageAvailableForChain) {
+      return null
+    }
+
+    if (!isPageAvailableForChain || isStayRedirect) {
+      return defaultRedirect
+    }
```
Comment (Jarsen136) [inline composables/useChainRedirect.ts:151]: It would be easier to read.
```suggestion
    if (isStayRedirect) {
       if (isPageAvailableForChain) {
           return null
       } else {
           return defaultRedirect
       }
    }
   
```

**Review by Jarsen136 — COMMENTED** [review]
otherwise lgtm

**Comment by prury** [comment]
Checking everything again: 

    /prefix/create - ✔️ 
    /blog/xxx : ❌ 
    /blog ✔️ 
    /_prefix/massmint ✔️ 
    /_prefix/massmint/onboarding ✔️ 
    /sales ❌ (snek,basilisk and both assethubs redirects to homepage) 
    /hot ✔️ 
    /series-insight ✔️ (Ahp and Ahk prob left out intentionally, since prob not yet implemented)
    /chain/explore/collectibles ✔️ 
    /chain/explore/items ✔️ 

@hassnian we are almost there! i appreciate that you took this issue, its not an easy one and is a huge enhancement, keep it going! 

will make a followup issue for:
profile page
transfer page

**Comment by hassnian** [comment]
> both assethubs

what do you mean by both assethubs

**Comment by hassnian** [comment]
@Jarsen136 I think we should be good now , @prury made some small changes , changed the regex a bit , I tested it on my end and everything worked as expected , pls check just to make sure that everything works fine 

thanks :D

**Review by Jarsen136 — APPROVED** [review]
lgtm

**Comment by yangwao** [comment]
pay 70 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $70 @ 5.03 USD/DOT ~ 13.917 $DOT
🧗 [16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD](https://polkadot.subscan.io/account/16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)
🔗 [0xc9b53ca189ef0255d594513a24a69af96ee07c53742df826325cfa590a9a51b5](https://polkadot.subscan.io/extrinsic/0xc9b53ca189ef0255d594513a24a69af96ee07c53742df826325cfa590a9a51b5)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
