### PR TITLE
fix: check balance before creating swap

### LINKED ISSUE #11479: Swaps logic?
I created a swap on one account and received it on another. Also added 1 DOT. 

Image

I tried to accept it:

Image

Looks like I don't have enough funds on the initial account. It's kind of sad that I have a swap offer I cannot accept. Why was I allowed to create swap in the first place? 😄

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs Design check

- @exezbcz please review

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #11479
Display current balance and check if he has enough balance to add additional fund

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image
image

## Summary by CodeRabbit

- **New Features**
  - Improved the preview for swap transactions by displaying the current balance and chain symbol during the process.
  - Enhanced action button behavior by automatically disabling it when your balance is insufficient, with visual cues (red text) to indicate low funds.

### CODE REVIEW

File: components/swap/Preview.vue [hunk 1]
```diff
@@ -178,6 +192,8 @@ const stepHasSurcharge = computed(() => swap.value.surcharge?.direction === step
 const count = computed(() => stepItems.value.length + (stepHasSurcharge.value ? 1 : 0))
 const isOverOneToOneSwap = computed(() => swap.value.offered.length > swap.value.desired.length && props.step === SwapStep.OFFERED)
 const isCollectionSwapDesired = computed(() => isCollectionSwap.value && props.step === SwapStep.DESIRED)
+const isOfferedSwapStep = computed(() => props.step === SwapStep.OFFERED)
+const insufficientBalance = computed(() => isOfferedSwapStep.value && balance.value <= Number(amount.value))
```
Comment (hassnian) [inline components/swap/Preview.vue:196]:
```suggestion
const insufficientBalance = computed(() => isOfferedSwapStep.value && (balance.value - ED) <= Number(amount.value))
```

**Review by hassnian — CHANGES_REQUESTED** [review]

File: components/swap/Preview.vue (hunk 1 above)
Comment (Jarsen136) [reply components/swap/Preview.vue]: fixed

**Review by hassnian — APPROVED** [review]
