### PR TITLE
fix: Invalid Promise-like handling.

### LINKED ISSUE #2301: (JS-0328) Invalid `Promise-like` handling
## Description
Usage of `Promise-like` values in statements without handling their errors appropriately is dangerous. Unhandled promises can cause several issues, such as improperly sequenced operations, ignored Promise rejections and more.

## Occurrences
There are 4 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/kodadot/nft-gallery/issue/JS-0328/occurrences/](https://deepsource.io/gh/kodadot/nft-gallery/issue/JS-0328/occurrences/)

image

### PR DESCRIPTION
**Pull request by zhyd1997**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2301 
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=H7Z4NAt8zMDr1uGWXUHSi2xT1JTuTMSPgdetcervvtsd3EJ)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

File: plugins/globalVariables.ts [hunk 1]
```diff
@@ -14,6 +14,11 @@ useOperators(OperatorType.ACCUMULATOR, {
...
   $avg,
 } as OperatorMap)
+
+/**
+ * skipcq
+ * no-floating-promises: ignoreIIFE
+ */
 ;(async () => {
   await enableExtension()
 })()
```
Comment (zhyd1997) [inline plugins/globalVariables.ts:24]: For more details, see here: [ignoreIIFE](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-floating-promises.md#ignoreiife).

Comment (roiLeo) [reply plugins/globalVariables.ts:24]: Instead of hiding the error, isn't there another solution?
I would see something more like
```js
export default async () => {
  await enableExtension()
}
```

Comment (zhyd1997) [reply plugins/globalVariables.ts:24]: I will try it, thank you!

**Comment by zhyd1997** [comment]
@roiLeo LGTM 👍🏿 : a7aff592a8e95b19734bbf3a753bdbe519921fc7

File: plugins/globalVariables.ts [hunk 2]
```diff
@@ -6,16 +6,21 @@ import { $group, $match, $project } from 'mingo/operators/pipeline'
...
+    $first,
+    $push,
+    $avg,
+  } as OperatorMap)
+
   await enableExtension()
-})()
 
-Vue.config.productionTip = false
+  Vue.config.productionTip = false
```
Comment (roiLeo) [inline plugins/globalVariables.ts:25]: Oh sorry about that one but this should be moved to `.nuxt.config.js`
```js
vue: {
  config: {
    productionTip: false
  }
}
```

**Review by roiLeo — COMMENTED** [review]
3 fixes (1 remaining?)
I'm not sure about the other changes but they lgtm

**Comment by zhyd1997** [comment]
Done: 5dfd725ed3736361d8b92c3955b8660e47667b08

**Comment by zhyd1997** [comment]
@roiLeo If you have any other questions, please let me know.

**Review by roiLeo — APPROVED** [review]

**Comment by yangwao** [comment]
Pay 100 usd

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 186.79 USD/KSM ~ 0.535 $KSM
🧗 [H7Z4NAt8zMDr1uGWXUHSi2xT1JTuTMSPgdetcervvtsd3EJ](https://kusama.subscan.io/account/H7Z4NAt8zMDr1uGWXUHSi2xT1JTuTMSPgdetcervvtsd3EJ)
🔗 [0xeb3f0efb42bea11c033357ecca2fb0f75be8c1baa97d0ccc870a533b4d505d33](https://kusama.subscan.io/extrinsic/0xeb3f0efb42bea11c033357ecca2fb0f75be8c1baa97d0ccc870a533b4d505d33)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
