### PR TITLE
fix: Drop page card hover and default state

### LINKED ISSUE #9248: Drop page card hover and default state
image

image
from figma: 

- there should be one stroke between the bottom section and the img
- stroke default is grey, active black 
- no change of font color 

link: https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=394-6126&mode=design&t=TUfbyfRyvQIpdXlD-11

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Needs Design check

  - @exezbcz please review

  ## Context

  - [x] Closes #9248

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image

image

  ## Copilot Summary
  copilot:summary

  copilot:poem

### CODE REVIEW

**Review by preschian — APPROVED** [review]

**Comment by exezbcz** [comment]
default state correct, have a please look at the active once again 

image


text color should not change plus only the outer stroke should change to black

**Comment by Jarsen136** [comment]
will check

**Comment by Jarsen136** [comment]
> default state correct, have a please look at the active once again
> 
> image
> 
> text color should not change plus only the outer stroke should change to black

✅ Fixed

File: components/drops/DropCard.vue [hunk 1]
```diff
@@ -130,10 +131,7 @@ onMounted(async () => {
 .drop-card {
   &:hover {
     .drop-card-banner {
```
Comment (roiLeo) [inline components/drops/DropCard.vue:133]: this does not look good as `&-banner` is defined underneath, I would add `&:hover` inside it or use class group hover

otherwise ok

**Review by roiLeo — APPROVED** [review]

File: components/drops/DropCard.vue (hunk 1 above)
Comment (Jarsen136) [reply components/drops/DropCard.vue:133]: There is detail that when hovering on the whole card `drop-card`,  the style should change. That's why I could not add `&:hover` inside only the banner `drop-card-banner`.  wdyt?

Comment (roiLeo) [reply components/drops/DropCard.vue:133]: I would consider refactoring to something cleaner since I find it kinda hard to read

Comment (Jarsen136) [reply components/drops/DropCard.vue:133]: lmk if you have any idea to make it with a better solution.

**Comment by exezbcz** [comment]
this card will be replaced after: 
- #9277

we can merge this one IMO
