### PR TITLE
fix: user column widths

### LINKED ISSUE #2956: Table is moving it's columns width on row expand
When you are at holders & flippers at collections and want to expand the row, columns should be fixed
Seems at users -> holdings & gains it's ok

https://deploy-preview-2945--koda-nuxt.netlify.app/rmrk/collection/0a8ce195286c168f19-DONKEY?tab=holders

Noticed bug at
- #2945

https://user-images.githubusercontent.com/5887929/167093230-9c183c91-42a6-482a-9379-215a731fc705.mov

### PR DESCRIPTION
**Pull request by GabrielBuragev**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2956 
- [x] Changed css styles for user column

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/0a8ce195286c168f19-DONKEY?tab=holders&page=1>
- [x] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer?target=GyZf4szj5ZeC4WQza4CjZzsE1u27uJKL77QL4kH1JzGB6bg)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

File: components/rmrk/Gallery/Holder/Holder.vue [hunk 1]
```diff
@@ -557,6 +557,8 @@ export default class CommonHolderTable extends mixins(
 }
 </script>
 <style lang="scss">
+@import '@/styles/variables.scss';
```
Comment (vikiival) [inline components/rmrk/Gallery/Holder/Holder.vue:560]: You dont use any variable :)

**Review by vikiival — COMMENTED** [review]
Looks like it works YOLO

File: components/rmrk/Gallery/Holder/Holder.vue (hunk 1 above)
Comment (roiLeo) [reply components/rmrk/Gallery/Holder/Holder.vue:560]: @vikiival `$tablet` is imported from variables

but I would use instead of media query
```css
@include tablet {
  ...
}
```
Bulma ref [here](https://bulma.io/documentation/utilities/responsive-mixins/#named-mixins)

**Review by roiLeo — APPROVED** [review]
✅ lgtm

**Comment by roiLeo** [comment]
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 103.83 USD/KSM ~ 0.482 $KSM
🧗 [GyZf4szj5ZeC4WQza4CjZzsE1u27uJKL77QL4kH1JzGB6bg](https://kusama.subscan.io/account/GyZf4szj5ZeC4WQza4CjZzsE1u27uJKL77QL4kH1JzGB6bg)
🔗 [0x311b0c84dbd68277c4d74c1d8d8500d9a5ebdf313eb9c1e3364f3aca161695f4](https://kusama.subscan.io/extrinsic/0x311b0c84dbd68277c4d74c1d8d8500d9a5ebdf313eb9c1e3364f3aca161695f4)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
