### PR TITLE
#4478 spacing issue fix

### LINKED ISSUE #4478: Galery item prelaunch feedback v1
Hi, i will add here my feedback from on the gallery item just to keep it on one place. 🚀 

# Layout

<details>
<summary>Grid</summary>

grid:
- the grid does not have even spacing
image
image

- gap between the img and the right section is to small
- can we make it like 40px everywhere? 
- and also the gap here is too big 
image

</details>

<details>
<summary>Right Section</summary>

- the price section is too low, then the gaps between creator/owner, divider are too large and it does not look good.
image
image
- same thing here, too packed. 
image
- on the other hand, gap between buttons is bigger than needed. 

</details>

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Closes #4478
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2023-01-14 at 4 00 20 PM

### CODE REVIEW

File: components/gallery/GalleryItem.vue [hunk 1]
```diff
@@ -161,6 +165,11 @@ useNuxt2Meta({
   font-size: 2.4375em;
 }
 
+hr {
+  height: 1px;
+  margin: 60px 0;
```
Comment (Jarsen136) [inline components/gallery/GalleryItem.vue:170]: classname`my-x` may help

File: components/gallery/GalleryItemAction/GalleryItemActionSection.vue [hunk 2]
```diff
@@ -3,7 +3,7 @@
     <div>
       <p class="has-text-grey">{{ title }}</p>
       <div class="is-flex is-align-items-center">
-        <div v-if="Number(price)" class="has-text-weight-bold is-size-3 mr-5">
+        <div v-if="Number(price)" class="has-text-weight-bold is-size-3 mr-6">
```
Comment (Jarsen136) [inline components/gallery/GalleryItemAction/GalleryItemActionSection.vue:6]: I'm about to remove `mr-5` here because it's incompatible with mobile

File: components/gallery/GalleryItem.vue [hunk 3]
```diff
@@ -56,17 +57,20 @@
           <hr />
 
           <!-- price section -->
-          <GalleryItemAction :nft="nft" @buy-success="onNFTBought" />
+          <GalleryItemAction
+            class="is-flex is-flex-direction-column is-flex-grow-1 is-justify-content-start"
```
Comment (Jarsen136) [inline components/gallery/GalleryItem.vue:61]: I would like to put these styles inner the `GalleryItemAction` component.

**Review by Jarsen136 — COMMENTED** [review]
I guess there are a little style conflict between this PR and #4697. May wait for #4697 to merged first, and then we could do some small adjustment here, to check spacing on mobile and pc.

**Comment by exezbcz** [comment]
what about this gap? 
image
should be same as the gap between cards i think.

**Comment by prachi00** [comment]
> what about this gap? image should be same as the gap between cards i think.

it is the same

File: components/gallery/GalleryItemAction/GalleryItemActionSection.vue (hunk 2 above)
Comment (prachi00) [reply components/gallery/GalleryItemAction/GalleryItemActionSection.vue:6]: wouldnt it break the web version then?

File: components/gallery/GalleryItem.vue (hunk 1 above)
Comment (prachi00) [reply components/gallery/GalleryItem.vue:170]: I dont think my-x is a class?

**Comment by exezbcz** [comment]
> > what about this gap? image should be same as the gap between cards i think.
> 
> 
> 
> it is the same 

I mean the gap between the top and bottom part

File: components/gallery/GalleryItem.vue (hunk 1 above)
Comment (roiLeo) [reply components/gallery/GalleryItem.vue:170]: > I dont think my-x is a class?

cf Bulma [doc](https://bulma.io/documentation/helpers/spacing-helpers/) example: `my-5`
please don't overload `hr` elements

File: components/gallery/GalleryItemAction/GalleryItemActionSection.vue (hunk 2 above)
Comment (Jarsen136) [reply components/gallery/GalleryItemAction/GalleryItemActionSection.vue:6]: No, I would put the margin style in the custom css accordingly.

**Review by vikiival — DISMISSED** [review]
All Issues were pointed out by @Jarsen136.

File: components/gallery/GalleryItem.vue (hunk 1 above)
Comment (prachi00) [reply components/gallery/GalleryItem.vue:170]: @roiLeo my-5 is still not enough spacing to match what we have in figma

Comment (roiLeo) [reply components/gallery/GalleryItem.vue:167]: What are you trying to fix here?
Instead of adding margin to `hr` try to add spacing on element around the component

**Comment by roiLeo** [comment]
> image Still does not look like its the same.

Can you show us the desired outcome?

**Comment by exezbcz** [comment]
> > Still does not look like its the same.
> 
> Can you show us the desired outcome?

yesss, sorry for that
image
should look like this, its not symetrical, thats what is the issue :D 
the red box is square.

**Review by roiLeo — DISMISSED** [review]
could you please don't add spacing directly on column `div`? (bad pratice)

you may need to use [variable-gap](https://bulma.io/documentation/columns/gap/#variable-gap) or change spacing inside column content

**Comment by Jarsen136** [comment]
> I guess there are a little style conflict between this PR and #4697. May wait for #4697 to merged first, and then we could do some small adjustment here, to check spacing on mobile and pc.

Merged. Let's resolve some code conflicts.

**Comment by prachi00** [comment]
@exezbcz 
Screen Shot 2023-01-17 at 10 32 33 AM

**Comment by exezbcz** [comment]
good job

**Comment by yangwao** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 34.66 USD/KSM ~ 0.577 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x03ce0bc481ea0f9bf87283d902a9f042f40e6588b2a4f4446fe9edcd5de1239a](https://kusama.subscan.io/extrinsic/0x03ce0bc481ea0f9bf87283d902a9f042f40e6588b2a4f4446fe9edcd5de1239a)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
