### PR TITLE
fix: inputting zero should default to 1

### LINKED ISSUE #10450: inputting zero should default to 1
image

it has still few holes - when you manually input zero, it should change to 1

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #10450

## Needs QA check

- @kodadot/qa-guild please review

## Needs Design check

- @exezbcz please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2024-06-12 at 13 27 26

### CODE REVIEW

File: components/collection/drop/MintStepper.vue [hunk 1]
```diff
@@ -4,6 +4,7 @@
     v-model="amountToMint"
     data-testid="drop-stepper-container"
     :max="max"
+    :min="1"
```
Comment (Jarsen136) [inline components/collection/drop/MintStepper.vue:7]: What happens if it's the`HolderOf` drop? The amount may be zero.

Comment (hassnian) [reply components/collection/drop/MintStepper.vue]: update it

**Review by Jarsen136 — APPROVED** [review]

**Review by preschian — APPROVED** [review]
