### PR TITLE
fix(coingecko): move api call to Transfer page

### LINKED ISSUE #1194: Remove Coingecko API where is not needed
Let's remove coingecko where is not needed.
Probably we need it only on `/transfer` and that's it.

### PR DESCRIPTION
**Pull request by roiLeo**
in the future we could move coingecko api calls to a new vuex module

### PR type
- [x] Refactoring

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality

### What's new?
- [x] PR closes #1194 
- [x] move coingecko api call from all routes to only Transfer route where it's needed

### Screenshot
- refactoring code

### CODE REVIEW

File: src/components/transfer/Transfer.vue [hunk 1]
```diff
@@ -154,7 +155,23 @@ export default class Transfer extends Mixins(
     return this.hasAddress ? encodeAddress(this.destinationAddress, correctFormat(this.ss58Format)) : ''
   }
 
+  public async getKsmPrice(): Promise<void> {
```
Comment (vikiival) [inline src/components/transfer/Transfer.vue:158]: I would put this whole func into the `@coingecko`

**Review by vikiival — CHANGES_REQUESTED** [review]
👀

**Comment by yangwao** [comment]
Amazing, looking forward for merging this!
