### PR TITLE
✨ Insufficient Funds in Offer Making

### LINKED ISSUE #4831: Please add "Insufficient funds" notification in offer making
### What happened?

Took me a few minutes till my brain realized where is the issue.

After setting the offer price it was not possible to click on confirm - _I was persuaded that offers are not working at all_ - but the issue was that I was logged in to an account with 0 funds.. so there were not enough funds in my acc - Please add an "Insufficient funds" notification in offer making for brainless people like me. 🥲

Screenshot 2023-01-25 at 20 32 18

### Please reproduce in steps

BSX - offer making - place an offer - not possible to confirm (I did not know why)

### Expected Behavior

Add notification: if you don't have enough funds please add an "Insufficient funds" notification.  Thanks!

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz, kodadot.xyz

### Are you logged in?

None

### Which wallet you are using?

PolkadotJS

### Screenshots

already attached

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by petersopko**
## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #4831 
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [x] I've tested it at </bsx/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Comment by Jarsen136** [comment]
@exezbcz Could you pls check this display? I'm not sure if need a tooltip above the confirm button or a notification toast.

**Comment by petersopko** [comment]
> @exezbcz Could you pls check this display? I'm not sure if need a tooltip above the confirm button or a notification toast.

I'm also not sure about the "notification" part of the solution, maybe @roiLeo can check and provide some UX/UI opinion, I remember having a "disabled buttons and tooltips" conversation before

**Comment by petersopko** [comment]
It's currently set only to warn users if there are 0 funds in the wallet when toggling the offer button.

Not optimal, but I don't think every change in offer price should toggle notif. either. 

lmk what should be done here.

**Review by roiLeo — COMMENTED** [review]
When not logged it throw the warning.
Screenshot 2023-01-26 at 11-20-02 TroyDX KodaDot - NFT Market Explorer

Queue?
Screenshot 2023-01-26 at 11-20-32 TroyDX KodaDot - NFT Market Explorer


> I'm also not sure about the "notification" part of the solution, maybe @roiLeo can check and provide some UX/UI opinion, I remember having a "disabled buttons and tooltips" conversation before

possible solution:
- tooltip on disabled button 
- or use [error-message](https://buefy.org/documentation/input/#types-and-states) in input

**Comment by petersopko** [comment]
> - or use [error-message](https://buefy.org/documentation/input/#types-and-states) in input

iirc, you preferred the error message, however, you've linked to buefy; maybe I should create a simple `NeoInput` with Oruga since we're going to use it in multiple places anyway?

**Comment by roiLeo** [comment]
> iirc, you preferred the error message, however, you've linked to buefy; maybe I should create a simple `NeoInput` with Oruga since we're going to use it in multiple places anyway?

Yes or create a new issue with `NeoInput` component.

IMO, these `GalleryItemActionlides` should be a component placed in `lib/ui`

**Comment by exezbcz** [comment]
Let's add a tooltip if it doesn't break anything else; I mean, it's not a solution when the notification pops up even if you don't type anything:D
How I think it works: the confirm button should become active after the amount you entered is available. Is that right?

**Comment by petersopko** [comment]
scraped the notification and added tooltip for insufficient funds case on confirm button

**Comment by Jarsen136** [comment]
I found a bug while inputting zero price.

Kapture 2023-01-27 at 17 53 36

**Comment by petersopko** [comment]
> I found a bug while inputting zero price.

yep also on main, should be fixed now.

**Comment by petersopko** [comment]
to sum it up:

- no notification after all
- added tooltip for disabled button if the case is insufficient funds, as per @exezbcz's request
- 0 offer bug fixed
- possible `NeoInput` or adding of `GalleryItemActionSlides` into lib/ui mentioned in issues above

**Comment by Jarsen136** [comment]
> I found a bug while inputting zero price.
> 
> Kapture 2023-01-27 at 17 53 36 

Seems that the bug is still there. Could you pls check?
Tested at https://deploy-preview-4834--koda-nuxt.netlify.app/snek/gallery/3033790537-1
image

**Comment by petersopko** [comment]
> when I input a non-zero value

@Jarsen136 maybe I'm missing something, but aren't you inputting zero value on the video? Also, the displayed behaviour is strange, I can't reproduce it on local or the deployed version 🤔

**Comment by petersopko** [comment]
https://user-images.githubusercontent.com/73316633/215279692-34fbc0ab-1382-4668-86c6-bcd33633c82a.mp4

**Comment by Jarsen136** [comment]
> > when I input a non-zero value
> 
> @Jarsen136 maybe I'm missing something, but aren't you inputting zero value on the video? Also, the displayed behaviour is strange, I can't reproduce it on local or the deployed version 🤔


emm. I could reproduce this strange bug on the preview env but not on the beta env. Here is the video.

 https://deploy-preview-4834--koda-nuxt.netlify.app/snek/gallery/3033790537-1
Kapture 2023-01-29 at 09 09 22

**Comment by petersopko** [comment]
> emm. I could reproduce this strange bug on the preview env but not on the beta env. Here is the video.

just now I realized there was a second confirm button missing, I didn't know what you mean 😆 fixed now.

File: components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue [hunk 1]
```diff
@@ -124,13 +128,21 @@ const confirm = ref(false)
...
 
+const insufficientBalance = computed(
+  () => Number(offerPrice.value) > simpleDivision(balance.value, decimals.value)
+)
+
+const offerPriceInvalid = computed(() => {
+  if (offerPrice.value) {
+    return Math.sign(offerPrice.value) !== 1
+  }
+  return true
```
Comment (Jarsen136) [inline components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue:139]: Is it different from `const offerPriceInvalid = computed(() => offerPrice.value && offerPrice.value>0)`
I guess it would be easier to read.

File: components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue [hunk 2]
```diff
@@ -124,13 +128,21 @@ const confirm = ref(false)
...
+})
+
 const disabledConfirmBtn = computed(
-  () =>
-    !(
-      offerPrice.value &&
-      Number(offerPrice.value) < simpleDivision(balance.value, decimals.value)
-    )
+  () => !(!offerPriceInvalid.value && !insufficientBalance.value)
```
Comment (Jarsen136) [inline components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue:143]:
```suggestion
  () => offerPriceInvalid.value || insufficientBalance.value
```

File: components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue (hunk 1 above)
Comment (petersopko) [reply components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue:139]: yes it's different, the result of your suggested change returns undefined if there's no price (the beginning state) and the button is therefore enabled

File: components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue (hunk 2 above)
Comment (petersopko) [reply components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue]: done, thank you

File: components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue (hunk 1 above)
Comment (Jarsen136) [reply components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue:139]: Oh, I got it. 👍

**Review by Jarsen136 — APPROVED** [review]
code lgtm

**Comment by yangwao** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 35.16 USD/KSM ~ 0.569 $KSM
🧗 [FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y](https://kusama.subscan.io/account/FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)
🔗 [0x008ee7d4ba7f86e0142247678a3273e433ae2858397124cd6d8db8e8322c04a7](https://kusama.subscan.io/extrinsic/0x008ee7d4ba7f86e0142247678a3273e433ae2858397124cd6d8db8e8322c04a7)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
