### PR TITLE
fix: Base collections: Not showing minting live - link to collection

### LINKED ISSUE #10802: Base collections: Not showing minting live - link to collection
There are few Base collections are not showing link to go to drop page in the collection. Some of the Base collection has it, some of them no. Open Specific Base collections and search for link on the top. 

This link I mean
Screenshot 2024-08-13 at 12 43 56

All collections that are missing this
---

Screenshot 2024-08-13 at 12 42 06

- https://kodadot.xyz/base/collection/0xd9a2c93ba2e9fae10fe762a42ee807bbf95764cc
- https://canary.kodadot.xyz/base/collection/0xc029b380f8a451cfd9e5124fa9fcad4397b8c119
- https://kodadot.xyz/base/collection/0x2cc76e51c4ae3ed7b0dcada34c1ea4fe059d5881
- https://kodadot.xyz/base/collection/0xc815823d86715fc9355c79252711f61087b39b39
- https://kodadot.xyz/base/collection/0x0b6504d95f9d550d274468fb6de5d13b7e64aa6a

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #10802

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

works:
https://kodadot.xyz/base/collection/0xd9a2c93ba2e9fae10fe762a42ee807bbf95764cc
https://canary.kodadot.xyz/base/collection/0xc029b380f8a451cfd9e5124fa9fcad4397b8c119
https://kodadot.xyz/base/collection/0x2cc76e51c4ae3ed7b0dcada34c1ea4fe059d5881
https://kodadot.xyz/base/collection/0xc815823d86715fc9355c79252711f61087b39b39

does not work:
https://kodadot.xyz/base/collection/0x0b6504d95f9d550d274468fb6de5d13b7e64aa6a (This drop does not exist in our database and needs to be added manually)

image

### CODE REVIEW

File: components/drops/useDrops.ts [hunk 1]
```diff
@@ -377,6 +377,7 @@ export const useHolderOfCollectionDrop = () => {
 export const useRelatedActiveDrop = (collectionId: string, chain: Prefix) => {
   const { drops } = useDrops({
     chain: [chain],
+    limit: 1000,
```
Comment (hassnian) [inline components/drops/useDrops.ts:380]: I'd rather filter in the worker side

```suggestion
    collections: [collectionId],
```

**Review by hassnian — COMMENTED** [review]
.

File: components/drops/useDrops.ts (hunk 1 above)
Comment (Jarsen136) [reply components/drops/useDrops.ts]: thanks, I just realize I have already implemented the `collection` query on the worker side : ) Updated

**Review by preschian — APPROVED** [review]

**Review by hassnian — APPROVED** [review]
