### PR TITLE
fix: Tags on RMRK NFTs

### LINKED ISSUE #3765: Tags on RMRK NFTs
I've minted two NFTs with tags on RMRK recently and I can't find the tags of these NFTs. I've checked on the detail of the NFT in gallery 

https://beta.kodadot.xyz/rmrk/gallery/14019028-A4598F5615F201D739-GBD-STATIC_NOISE-0000000000000001?page=1

and it's not there (perhaps the idea was to make it hidden?)

But then I've checked in rubick and I can't find it there either? @vikiival told me to look in meta/traits, but one of them has meta null and the other one doesn't have any of the tags I've selected. Am I doing/understanding something wrong here?

```json
{
  "data": {
    "collectionEntityById": {
      "nfts": [
        {
          "createdAt": "2022-08-15T15:28:00.008000Z",
          "currentOwner": "GHoyYbdFWAsjACxgfAofb2M9KPARrbJCm1ZfZpzKyig9XRJ",
          "hash": "a64c5433743730e31d03fdc0c221a3b2",
          "id": "14019028-A4598F5615F201D739-GBD-STATIC_NOISE-0000000000000001",
          "instance": "STATIC_NOISE",
          "issuer": "GHoyYbdFWAsjACxgfAofb2M9KPARrbJCm1ZfZpzKyig9XRJ",
          "price": "500000000000",
          "sn": "0000000000000001",
          "transferable": 1,
          "updatedAt": "2022-08-15T15:28:54.011000Z",
          "metadata": "ipfs://ipfs/bafkreicyev7tio5xtynbaool2crjzri4lkqzo45t5ay6s3ka3sd6iu7kxq",
          "name": "Static Noise",
          "meta": null
        },
        {
          "createdAt": "2022-08-17T07:42:24.014000Z",
          "currentOwner": "GHoyYbdFWAsjACxgfAofb2M9KPARrbJCm1ZfZpzKyig9XRJ",
          "hash": "421178bf8d86f1c018a0b08763f6e166",
          "id": "14043122-A4598F5615F201D739-GBD-FACELESS-0000000000000002",
          "instance": "FACELESS",
          "issuer": "GHoyYbdFWAsjACxgfAofb2M9KPARrbJCm1ZfZpzKyig9XRJ",
          "price": "500000000000",
          "sn": "0000000000000002",
          "transferable": 1,
          "updatedAt": "2022-08-17T07:43:00.011000Z",
          "metadata": "ipfs://ipfs/bafkreifmsranjomcmtsrjcgwnp3mzuhpqmb4rlzxxnbkc2rfxbqnefocbm",
          "name": "Faceless",
          "meta": {
            "id": "ipfs://ipfs/bafkreifmsranjomcmtsrjcgwnp3mzuhpqmb4rlzxxnbkc2rfxbqnefocbm",
            "image": "ipfs://ipfs/bafybeigbecbefvc3oq72jwncdb7ihhztrjowxmx3wfssyxczaxrjy5le3y",
            "name": "Faceless",
            "type": "image/png",
            "animationUrl": null,
            "attributes": [
              {
                "value": "1",
                "trait": "carbonless",
                "display": "undefined"
              }
            ],
            "description": "I ain’t nobody, and neither are you 🎵"
          }
        }
      ],
      "symbol": "GBD",
      "version": null
    }
  }
}



```

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3765
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

File: components/rmrk/Gallery/GalleryItem.vue [hunk 1]
```diff
@@ -368,6 +372,8 @@ export default class GalleryItem extends mixins(PrefixMixin) {
         ),
       }
 
+      console.log('jarsen this', this.meta)
+
```
Comment (roiLeo) [inline components/rmrk/Gallery/GalleryItem.vue:376]:
```suggestion
```

jarsen this, jarsen that 👀

**Comment by roiLeo** [comment]
How does it work? Where can we test this?

**Comment by petersopko** [comment]
> How does it work? Where can we test this?

you mint NFT with selected tags and test whether they are included in metadata of the NFT at https://app.gc.subsquid.io/beta/rubick/007/graphql and now, whether they are showing with @Jarsen136's implementation

**Review by petersopko — CHANGES_REQUESTED** [review]
now something gets saved, but is this the way it should work? 👀

image


```json
"meta": {
              "attributes": [
                {
                  "display": "undefined",
                  "trait": "undefined",
                  "value": "image"
                },
                {
                  "display": "undefined",
                  "trait": "undefined",
                  "value": "dall·e"
                },
                {
                  "display": "undefined",
                  "trait": "undefined",
                  "value": "generative"
                },
                {
                  "display": "undefined",
                  "trait": "carbonless",
                  "value": "1"
                }
              ]
            }
```

**Comment by Jarsen136** [comment]
> now something gets saved, but is this the way it should work? 👀
> 
> image
> 
I think it's not.
By the way, I wonder what's name of the key should be shown when user selected some tag 🤔

**Comment by Jarsen136** [comment]
I guess it's better now with the redesign of the property component.
image

File: components/shared/gallery/Properties.vue [hunk 2]
```diff
@@ -6,7 +6,9 @@
         :key="attribute[fieldKey]"
         class="column is-4">
         <div class="notification is-primary is-light">
-          <div class="is-size-7 has-text-grey-lighter is-uppercase">
+          <div
+            v-if="attribute[fieldKey] && attribute[fieldKey] !== 'undefined'"
```
Comment (roiLeo) [inline components/shared/gallery/Properties.vue:10]: hey, why is it needed? 
`<Properties />` component is already wrapped with a `v-if="meta.attributes && meta.attributes.length"`

Comment (Jarsen136) [reply components/shared/gallery/Properties.vue:10]: Because the tag object doesn't have the property of 'trait_type' or 'display_type'.

Comment (roiLeo) [reply components/shared/gallery/Properties.vue:10]: How did this happen? can't it be possible to leave it empty if not filled in? (I'm asking this since It can introduce spacing issue)

Comment (Jarsen136) [reply components/shared/gallery/Properties.vue:10]: It happens during the minting process. On the front-end side, it's already empty, but after process by server side, it
turn into an `undefined` string.

image

Comment (Jarsen136) [reply components/shared/gallery/Properties.vue:10]: >I'm asking this since It can introduce spacing issue

How about leaving an empty string like ' ' to keep them the same height?

Comment (roiLeo) [reply components/shared/gallery/Properties.vue:10]: > How about leaving an empty string like ' ' to keep them the same height?

Let's try this solution

Comment (Jarsen136) [reply components/shared/gallery/Properties.vue]: image

File: components/shared/gallery/Properties.vue [hunk 3]
```diff
@@ -35,3 +34,9 @@ export default class Properties extends Vue {
   @Prop({ type: String, default: 'trait_type' }) public fieldKey!: string
 }
 </script>
+<style scoped>
+.attribute-key {
+  min-height: 18px;
+}
+</style>
```
Comment (roiLeo) [inline components/shared/gallery/Properties.vue:41]: oh no... :(
any other solution than a fixed height? 
could you remove scoped?

Comment (Jarsen136) [reply components/shared/gallery/Properties.vue:41]: > oh no... :( any other solution than a fixed height? could you remove scoped?
I found no other better solution in this case. Empty string ' ' does not have height.
Why should we remove `scoped`?

Comment (roiLeo) [reply components/shared/gallery/Properties.vue:41]: https://github.com/kodadot/nft-gallery/issues/1348#issuecomment-1189026590

Comment (Jarsen136) [reply components/shared/gallery/Properties.vue]: DONE!

**Comment by roiLeo** [comment]
I have doubts about the correct functioning, as this been tested on mint?

**Comment by Jarsen136** [comment]
> I have doubts about the correct functioning, as this been tested on mint?

Yup, petersopko have tested on rmrk. I have tested on bsx as well. It works well on minting.

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 48.63 USD/KSM ~ 1.028 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x6be1c14cea661eea68fdc9338e410f221b7174f12a9c16dabf5ab6c93964dc1a](https://kusama.subscan.io/extrinsic/0x6be1c14cea661eea68fdc9338e410f221b7174f12a9c16dabf5ab6c93964dc1a)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
