### PR TITLE
fix: Statemine properties not showing

### LINKED ISSUE #6426: Statemine properties not showing
### What happened?

The properties/attributes are not showing on kodadot currently for Statemine NFTs pallet NFTs.

### Please reproduce in steps

Go to [this NFT](https://kodadot.xyz/stmn/gallery/9-231) and check out the properties section. It will be empty.

The batch call that mints the nft and adds the attributes can be verified [here](https://assethub-kusama.subscan.io/block/4704472).

### Expected Behavior

I expect the added attributes to be displayed in the UI under properties.

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### Screenshots

Screenshot 2023-07-12 at 14 50 33

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #6426
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed UI

`/stmn/gallery/3-1` 

image

### <samp>🤖 Generated by Copilot at 57c6b3b</samp>

This pull request fixes a bug in displaying NFT attributes and updates the stick indexer URL to use the latest version. It modifies `useNft.ts`, `indexers.ts`, `nftById.graphql`, and `constants.ts` to handle the new NFT attributes format.

### <samp>🤖 Generated by Copilot at 57c6b3b</samp>

> _`stick indexer` v4_
> _fixes NFT attributes_
> _fall is for bug squash_

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
Tested on `https://deploy-preview-6438--koda-canary.netlify.app/stmn/gallery/9-231` 

✅ code lgtm

File: composables/useNft.ts [hunk 1]
```diff
@@ -52,7 +52,7 @@ async function getProcessMetadata(nft: NFTWithMetadata) {
   const getAttributes = () => {
     const hasMetadataAttributes =
       metadata.attributes && metadata.attributes.length > 0
-    const attr = nft?.meta?.attributes || []
+    const attr = nft?.attributes || nft?.meta?.attributes || []
```
Comment (vikiival) [inline composables/useNft.ts:55]: I would probably do a merge of properties?

**Comment by vikiival** [comment]
Otherwise LGTM

**Comment by prury** [comment]
once this is merged, I'll be opening another issue for this: 
image
https://deploy-preview-6438--koda-canary.netlify.app/stmn/gallery/9-143

File: composables/useNft.ts (hunk 1 above)
Comment (Jarsen136) [reply composables/useNft.ts]: Done. Now they are merging to a properties list.

**Review by vikiival — APPROVED** [review]

File: composables/useNft.ts [hunk 2]
```diff
@@ -2,7 +2,7 @@ import type { NFT, NFTMetadata } from '@/components/rmrk/service/scheme'
 import { sanitizeIpfsUrl } from '@/utils/ipfs'
 import { processSingleMetadata } from '@/utils/cachingStrategy'
 import { getMimeType } from '@/utils/gallery/media'
-
+import unionBy from 'lodash/unionBy'
```
Comment (roiLeo) [inline composables/useNft.ts:5]:
```ts
const unionBy = (arr, ...args) => {
  let iteratee = args.pop()
  if (typeof iteratee === 'string') {
    const prop = iteratee
    iteratee = item => item[prop]
  }

  return arr
    .concat(...args)
    .filter(
      (x, i, self) => i === self.findIndex(y => iteratee(x) === iteratee(y))
    )
}
```

Comment (Jarsen136) [reply composables/useNft.ts:5]: Sorry, but I do not understand why we would write a common util function instead of using lodash. Imo using lodash could avoid some unexpected mistakes.

Comment (roiLeo) [reply composables/useNft.ts:5]: you might not need loadash

Comment (Jarsen136) [reply composables/useNft.ts:5]: image

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 5.15 USD/DOT ~ 3.883 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0xad9080282965edd220ccb252ecb1b1d7c63779c14bbb29373de6a65c0b2e89ba](https://polkadot.subscan.io/extrinsic/0xad9080282965edd220ccb252ecb1b1d7c63779c14bbb29373de6a65c0b2e89ba)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
