### PR TITLE
fix: indexed-db for media component

### LINKED ISSUE #3798: 3D Model not Loaded on Collection Page
### What happened?

some items are not loaded on the collection page. because indexed-db only stored `type` key. maybe related with https://github.com/kodadot/nft-gallery/issues/3751

Screen Shot 2022-08-21 at 13 37 57 

### Please reproduce in steps

1. visit https://beta.kodadot.xyz/rmrk/gallery/14024372-7CF9DAA38281A57331-APO-12-0000000000000012
2. click collection name

### Expected Behavior

should be loaded properly with correct indexed-db

Screen Shot 2022-08-21 at 13 43 16

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz, kodadot.xyz

### Are you logged in?

No

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

RMRK

### Screenshots

-

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3798 

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged the recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

File: components/rmrk/Gallery/GalleryCard.vue [hunk 1]
```diff
@@ -14,11 +14,10 @@
           <span class="card-image__emotes__count">{{ emoteCount }}</span>
         </span>
         <BasicImage
-          v-if="!animatedUrl"
+          v-if="!animatedUrl || image"
```
Comment (Jarsen136) [inline components/rmrk/Gallery/GalleryCard.vue:17]: I'm afraid that some 3d models nft could not be shown properly because it has `image`.

Could you pls explain why ?

Comment (preschian) [reply components/rmrk/Gallery/GalleryCard.vue:17]: let me check other 3d collections again, or do you have which 3d items have `animatedUrl` and `image` at the same time?

afaik for 3d use `animatedUrl` only

Comment (preschian) [reply components/rmrk/Gallery/GalleryCard.vue:17]: initially, this is for handling `audio` items because it has `animatedUrl` and `image`. so, instead of showing the audio player on the collection page, `audio` items show the image instead

Comment (preschian) [reply components/rmrk/Gallery/GalleryCard.vue:17]: tested in another 3d collections seems fine [`34db249` (#3799)](https://github.com/kodadot/nft-gallery/pull/3799/commits/34db24931b3a9c92ec8930ce19a69015ff518906#diff-8917895a9cfaf52ac3c6af17865d77851ad60ab4401d2b1581e7776b76abe14d)

**Comment by yangwao** [comment]
It's this good to go? :)

**Comment by preschian** [comment]
I added @roiLeo for additional feedback 🙏🏻

**Comment by roiLeo** [comment]
> I added @roiLeo for additional feedback 🙏🏻

lol I'm not really the one to check tests, but i'll take a look (if it pass then it means it's good!)

**Comment by preschian** [comment]
> lol I'm not really the one to check tests, but i'll take a look (if it pass then it means it's good!)

oh, not on the test files, I mean logic on vue components 🙈
but thanks anyway

File: components/media/PreviewMediaResolver.vue [hunk 2]
```diff
@@ -33,7 +34,9 @@ const fetchMimeType = async () => {
     return
   }
 
-  const nftMetadata = await get<NFTMetadata>(props.metadata)
+  const nftMetadata = (await processSingleMetadata(
+    props.metadata
+  )) as NFTMetadata
```
Comment (roiLeo) [inline components/media/PreviewMediaResolver.vue:39]:
```suggestion
  const nftMetadata = await processSingleMetadata<NFTMetadata>(props.metadata)
```

**Review by roiLeo — COMMENTED** [review]
Tested on:
- https://deploy-preview-3799--koda-nuxt.netlify.app/bsx/u/bXhWeVLtArWauM8UmbaVdDmXmo5uSDk6DAa2YxQ5zbt2sDcbW?page=1
- https://deploy-preview-3799--koda-nuxt.netlify.app/bsx/collection/2444376227?page=1

and I can't see my balls :(
Screenshot 2022-08-23 at 13-31-23 Ping Pong Ball KodaDot - Kusama NFT Market Explorer

File: components/media/PreviewMediaResolver.vue (hunk 2 above)
Comment (preschian) [reply components/media/PreviewMediaResolver.vue:39]: aahh, good call to summon you to this PR XD
will check

File: components/rmrk/Gallery/GalleryCard.vue (hunk 1 above)
Comment (Jarsen136) [reply components/rmrk/Gallery/GalleryCard.vue:17]: Oki

**Comment by yangwao** [comment]
deepscan issue 👀

**Review by roiLeo — APPROVED** [review]
all links are working as excepted

**Review by Jarsen136 — APPROVED** [review]
LGTM

**Comment by yangwao** [comment]
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 49.7 USD/KSM ~ 1.006 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0xf76eeff486caa1539555d78688422b519f83ad43c146594bbc4e2c37e3f18cc0](https://kusama.subscan.io/extrinsic/0xf76eeff486caa1539555d78688422b519f83ad43c146594bbc4e2c37e3f18cc0)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by preschian** [comment]
thanks for the reviews 🙏🏻
review from @Jarsen136 was correct regarding the image in 3d https://github.com/kodadot/nft-gallery/pull/3799#discussion_r950865860
