### PR TITLE
fix: Create profile when not connected

### LINKED ISSUE #10446: Create profile when not connected
somehow i managed to click follow even if i was not connected - create profile displayed
image

overall, quite weird behavior after that 

so, what I did before: 
- I was connected on the app with my profile, disconnected, clicked follow Thomas -> create profile displayed

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs Design check

- @exezbcz please review

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #10446

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

File: components/profile/ProfileDetail.vue [hunk 1]
```diff
@@ -487,13 +487,13 @@ const followConfig: ButtonConfig = {
...
   classes: 'hover:!bg-transparent',
-}
+}))
 
 const followingConfig: ButtonConfig = {
   label: $i18n.t('profile.following'),
 }
 
-const unfollowConfig: ButtonConfig = {
+const unfollowConfig: ComputedRef<ButtonConfig> = computed(() => ({
```
Comment (hassnian) [inline components/profile/ProfileDetail.vue:496]:
```suggestion
const unfollowConfig = computed<ButtonConfig>(() => ({
```

File: components/profile/ProfileDetail.vue [hunk 2]
```diff
@@ -472,7 +472,7 @@ const createProfileConfig: ButtonConfig = {
   variant: 'k-accent',
 }
 
-const followConfig: ButtonConfig = {
+const followConfig: ComputedRef<ButtonConfig> = computed(() => ({
```
Comment (hassnian) [inline components/profile/ProfileDetail.vue:475]:
```suggestion
const followConfig = computed<ButtonConfig>(() => ({
```

**Review by hassnian — APPROVED** [review]

**Review by vikiival — APPROVED** [review]
