### PR TITLE
fix: close modal after clicking settings btn

### LINKED ISSUE #7153: Nova wallet: Hide side bar after clicking on Settings
## What happened

IMG_6878

After clicking on Settings in the Profile - in the mobile app (Nova Wallet) - it looks like nothing happened (even though the settings loaded), but the sidebar did not disappear, and it makes you feel like its not working. 

Here is the video: 
https://github.com/kodadot/nft-gallery/assets/104380776/1c4d5f97-7b1f-43a9-80cb-fe4e0698f97c

I had to manually go back:

## How it should be
After you click on settings, the bar should disappear, and settings should load. Same as other things (teleport, transfer - all work okay, all hide sidebar, only settings are weird)

### PR DESCRIPTION
**Pull request by xiiiAtCn**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #7153  
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] my DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=12jXHf7yYF4wTRjDPbwFB24V1nVRPRkuU2S8Ke5ZWTfvyBGW&usdamount=8.82&donation=true)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

### <samp>🤖 Generated by Copilot at 8280712</samp>

Fixed a bug in the `NeoModalExtend` plugin that prevented removing modal listeners. Improved the user experience of the wallet asset menu by closing it when not needed.

### <samp>🤖 Generated by Copilot at 8280712</samp>

> _Oh we splice the `openListener` with a clever trick_
> _We find the index with `indexOf` and we do it quick_
> _We close the wallet modal when we change the route_
> _We use the `useNuxtApp` hook and the `NeoModalExtend` to boot_

### CODE REVIEW

File: libs/ui/src/components/NeoModalExtend/plugin.js [hunk 1]
```diff
@@ -14,7 +14,7 @@ const ModalProgrammatic = {
   removeOpenListener(callback) {
     for (const listener of openListener) {
       if (listener === callback) {
-        openListener.splice(i, 1)
+        openListener.splice(openListener.indexOf(listener), 1)
         break
       }
     }
```
Comment (Jarsen136) [inline libs/ui/src/components/NeoModalExtend/plugin.js:20]: You could use `filter` to avoid looping twice.

**Review by Jarsen136 — CHANGES_REQUESTED** [review]

**Review by Jarsen136 — APPROVED** [review]

**Review by preschian — APPROVED** [review]

**Comment by yangwao** [comment]
Most code approvals for the least lines added 👀

image
image

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 4.22 USD/DOT ~ 7.109 $DOT
🧗 [12jXHf7yYF4wTRjDPbwFB24V1nVRPRkuU2S8Ke5ZWTfvyBGW](https://polkadot.subscan.io/account/12jXHf7yYF4wTRjDPbwFB24V1nVRPRkuU2S8Ke5ZWTfvyBGW)
🔗 [0x273d2d8baafb917d5c6334e7586a7aea88535092f81df1013a84ee927404bcf5](https://polkadot.subscan.io/extrinsic/0x273d2d8baafb917d5c6334e7586a7aea88535092f81df1013a84ee927404bcf5)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
