### PR TITLE
:ambulance: MINT Does not work correctly

### LINKED ISSUE #5020: Collection name changed to something letters and numbers
### What happened?

An artist was creating his new collection:
image

After minting the collection has a different name

### Please reproduce in steps

RMRK, mint classic

### Expected Behavior

mint collection with normal name

### What browsers are you seeing the problem on?

_No response_

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### At which chain did you encounter bug?

_No response_

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by vikiival**
- :ambulance: BasicInput does not emit any function
- :bug: disable collection mint if name, symbol or image is not provided
- :bug: Spaces are illegal in names

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5020

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [x] I've tested it at </bsx/collection>

Before 

Screenshot 2023-02-17 at 16 54 14

After 

Screenshot 2023-02-17 at 16 54 09

### Investigation

My bet is that it was broken by 3b018a32c51b40c4c151e8c6d862d71f32684943

### CODE REVIEW

File: components/shared/form/BasicInput.vue [hunk 1]
```diff
@@ -48,13 +49,18 @@ withDefaults(
...
-
+const emit = defineEmits(['input'])
 const input = ref<BInput>(null)
 
 function checkValidity() {
   return input.value?.checkHtml5Validity()
 }
 
+const handleInput = (value: string) => {
+  console.log('input', value)
```
Comment (Jarsen136) [inline components/shared/form/BasicInput.vue:60]:
```suggestion
```

**Review by Jarsen136 — APPROVED** [review]
