### PR TITLE
fix: ignore metadata endpoint for fxart

### LINKED ISSUE #10347: Enough: Quality and resolution is very bad
Collection [Enough](https://kodadot.xyz/ahp/gallery/130-2405249231).

Tried to open full-screen mode:
1) Images are in very low resolution?! 
2) once downloaded, they look like this:

I have an info that the original code should make images with higher resolution - in a much better quality

### LINKED ISSUE #10348: Enough: Predefined function not working!
Hey guys, another issue with collection Enough: https://kodadot.xyz/ahp/gallery/130-2405249231

You can not use the function (just press "s" key) to save the work when you open art on fullscreen.

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #10347
- [x] Closes #10348

#### Did your issue had any of the "$" label on it?

- [ ] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by prury** [comment]
- the predefined "s" key still won't work on full screen
- download quality still very small

**Comment by preschian** [comment]
> * the predefined "s" key still won't work on full screen
> * download quality still very small

Related: https://github.com/kodadot/nft-gallery/issues/9355. For some genart, it's recommended to click open in a new tab and press "s" to save it as an image.

**Comment by prury** [comment]
@preschian can you also change the quality of the download button so it matches the download quality of using "s" in new tab? ty!

image

**Comment by preschian** [comment]
> @preschian can you also change the quality of the download button so it matches the download quality of using "s" in new tab? ty!


that one related with this: https://github.com/kodadot/nft-gallery/issues/8453. different issue

File: components/gallery/GalleryItem.vue [hunk 1]
```diff
@@ -49,7 +49,7 @@
             class="gallery-item-media relative"
             :src="getMediaSrc(image)"
             :animation-src="nftAnimation"
-            :mime-type="nftAnimationMimeType || nftMimeType"
+            :mime-type="(nftAnimation && nftAnimationMimeType) || nftMimeType"
```
Comment (Jarsen136) [inline components/gallery/GalleryItem.vue:52]:
```suggestion
            :mime-type="(nftAnimation && nftAnimationMimeType) || nftMimeType"
```


```suggestion
            :mime-type="(nftAnimation ? nftAnimationMimeType : undefined) || nftMimeType"
```
In case of that `nftAnimation` is not empty but `nftAnimationMimeType` is undefined.

**Review by Jarsen136 — APPROVED** [review]

**Review by hassnian — APPROVED** [review]
