### PR TITLE
Admin Panel Fixes

### LINKED ISSUE #1701: Admin panel doesnt work
- make send window at least three times height of original one 
image

- on beta, could not load collections 
image

### PR DESCRIPTION
**Pull request by chandradot99**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

### PR type
- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main-nuxt** and I've no conflicts
- [x] I've tried respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases

### What's new?
- [x] PR closes #1701 
- [x] Added Client option in Apollo manual query
- [x] Increased Address Parser height to 400px

### Had issue bounty label ?
- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=CeBWgisygADqqxGk7ju8aMNEKz1K2WkxMKC3G8HsMnm119n)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [x] My fix has changed **something** on UI, a screenshot is best to understand changes for others.

### CODE REVIEW

File: components/accounts/AddressParser.vue [hunk 1]
```diff
@@ -29,3 +29,9 @@ export default class AddressParser extends Vue {
   }
 }
 </script>
+
+<style lang="scss">
+  .ap-textarea {
+    height: 400px !important;
+  }
+</style>
```
Comment (roiLeo) [inline components/accounts/AddressParser.vue:37]: Why did you need to specify height of textare?

Comment (chandradot99) [reply components/accounts/AddressParser.vue:37]: @roiLeo because the height of current textarea is small and @yangwao mentioned to make the send window at least three times height of original one.

**Review by roiLeo — APPROVED** [review]
lgtm

**Comment by yangwao** [comment]
Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0xa724e21533cd19d834733b3dd66629a04d020b98ef0282256358a02ae76343d3

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/
