### PR TITLE
fix: unable to make offer due to balance issue

### LINKED ISSUE #5938: unable to make offer due to balance issue
LOOKS LIKE THERE IS SOME Balance issue

Screenshot 2023-05-12 at 14 03 07

Screenshot 2023-05-12 at 14 03 16

_Originally posted by @vikiival in https://github.com/kodadot/nft-gallery/issues/5891#issuecomment-1545637276_
            

It only happens on the nft that has no price on bsx

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5938
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### <samp>🤖 Generated by Copilot at dc1efde</samp>

Improved offer functionality and code quality in `GalleryItemOffer.vue`. Fixed a balance update bug.

### <samp>🤖 Generated by Copilot at dc1efde</samp>

> _Some variables were not in use_
> _So they got the axe and no excuse_
> _To fetch the BSX balance_
> _We imported a function with valence_
> _And fixed a bug that caused some abuse_

### CODE REVIEW

File: components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue [hunk 1]
```diff
@@ -106,21 +106,27 @@ const props = defineProps<{
...
 const connected = computed(() => Boolean(accountId.value))
 
-const balance = computed<string>(() => {
-  if (urlPrefix.value == 'rmrk' || urlPrefix.value == 'ksm') {
-    return identityStore.getAuthBalance
-  }
-  return identityStore.getTokenBalanceOf(tokenId.value)
+const balance = ref<string>('0')
+onMounted(() => {
+  fetchBalance()
```
Comment (roiLeo) [inline components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue:119]: `identityStore.fetchBalance`

**Review by roiLeo — COMMENTED** [review]
please could you use pinia storage to fetch & get balance so we can share the value between components

File: components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue [hunk 2]
```diff
@@ -106,21 +106,27 @@ const props = defineProps<{
...
 const { accountId } = useAuth()
 const { decimals } = useChain()
-const identityStore = useIdentityStore()
 const root = ref<Vue<Record<string, string>>>()
 const connected = computed(() => Boolean(accountId.value))
 
-const balance = computed<string>(() => {
-  if (urlPrefix.value == 'rmrk' || urlPrefix.value == 'ksm') {
-    return identityStore.getAuthBalance
-  }
```
Comment (roiLeo) [inline components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue:121]: If you remove this "BUY" button will be disabled for everyone on rmrk

**Review by roiLeo — CHANGES_REQUESTED** [review]

File: components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue (hunk 2 above)
Comment (roiLeo) [reply components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue:121]: nvm wrong component

File: components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue (hunk 1 above)
Comment (Jarsen136) [reply components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue:119]: It dose not work actually. It will fetch the balance of bsx token on bsx. : ) 
That's why I delete this part.

Comment (roiLeo) [reply components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue:119]: I don't think your solution will work on `snek` chain `bsx => '1'; snek => '5'`
We need to find a way to proper fetch balance on each chain, maybe rework `auth.balance` from pinia store to have something like: `auth.balance[prefix][token]`

Comment (Jarsen136) [reply components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue:119]: I have changed the id `1` to variable `tokenId`, so that it would fetch balance properly on other chains, including snek. Reworking `auth.balance[prefix][token]` on identityStore would bring too many changes, which seems unnecessary in this case.

**Review by roiLeo — COMMENTED** [review]
`Error: Unable to retrieve keypair '...'` Warning poping on snek, I don't think it's related to this PR

**Comment by Jarsen136** [comment]
> `Error: Unable to retrieve keypair '...'` Warning poping on snek, I don't think it's related to this PR

It should be fixed now, as I merged the main branch into this one.

**Comment by roiLeo** [comment]
> It should be fixed now, as I merged the main branch into this one.

Still not working for me

**Review by roiLeo — APPROVED** [review]
worked after clearing local storage

**Comment by vikiival** [comment]
Works!

Screenshot 2023-05-15 at 21 55 33

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
pay 15 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $15 @ 25.76 USD/KSM ~ 0.582 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x90199f364af2dd7d57c12514bcc4626b703791fc2d735469b8044e8858c51b1d](https://kusama.subscan.io/extrinsic/0x90199f364af2dd7d57c12514bcc4626b703791fc2d735469b8044e8858c51b1d)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
