### PR TITLE
fix: Rankings & See All in search bar outside of landing page doesnot follow design

### LINKED ISSUE #4259: Rankings & See All in search bar outside of landing page doesn't follow design
"Rankings -->" & See All -->" don't follow the design like is on the landing page 

image

image

how it should look like, same for See All  

image

### PR DESCRIPTION
**Pull request by Jarsen136**
… follow design

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## PR Context?

- [x] Closes #4259
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

File: components/search/SearchSuggestion.vue [hunk 1]
```diff
@@ -141,7 +152,18 @@
           :to="{ name: 'series-insight' }"
           @click.native="$emit('close')">
           <div :class="loadMoreItemClassName">
-            {{ $t('search.rankings') }} <span class="info-arrow">--></span>
+            {{ $t('search.rankings') }}
+            <svg
```
Comment (prachi00) [inline components/search/SearchSuggestion.vue:156]: would it be possible to import these in a .svg file and then import it to avoid repetition?

**Comment by yangwao** [comment]
pay 30

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 38.03 USD/KSM ~ 0.789 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xb96ba6151d189d14c54184465ff6d0b22536ec4b6cceaa265b39207aac4acfbf](https://kusama.subscan.io/extrinsic/0xb96ba6151d189d14c54184465ff6d0b22536ec4b6cceaa265b39207aac4acfbf)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
