### PR TITLE
#5531 toggle issue fix

### LINKED ISSUE #5531: "do nothing" when clicking icon again
- when you have opened sidebar and you click the icon again it is placed on top and creates double sidebar? 
- 
image
image
image

- happens mainly when you connect wallet for the first time, and then click the wallet icon 

I think we should either close it and dont stack two sidebars on top - also the dark bg is duplicating - or do nothing :D 
- we already have close when clicking it again so we can use this type

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5531
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

File: components/shared/ConnectWalletButton.vue [hunk 1]
```diff
@@ -21,17 +20,7 @@ export default class ConnectWalletButton extends Vue {
...
-      this.modal.close()
-      this.modal = null
-      return
-    }
-    this.modal = this.$buefy.modal.open({
-      parent: this,
-      ...ConnectWalletModalConfig,
-    })
-
-    this.$emit('closeBurgerMenu')
```
Comment (Jarsen136) [inline components/shared/ConnectWalletButton.vue:34]: pls do not delete this stuff. The changes will break the functionality to open the modal on mobile.

**Review by Jarsen136 — CHANGES_REQUESTED** [review]

File: components/shared/ConnectWalletButton.vue (hunk 1 above)
Comment (prachi00) [reply components/shared/ConnectWalletButton.vue:34]: oh, can we add mobile check then? we dont need this on web, its what was breaking this issue

File: components/navbar/ProfileDropdown.vue [hunk 2]
```diff
@@ -165,7 +165,7 @@
         class="button-connect-wallet px-4"
         variant="k-accent"
         no-shadow
-        @closeBurgerMenu="closeBurgerMenu" />
+        @toggleConnectModal="toggleWalletConnectModal" />
```
Comment (Jarsen136) [inline components/navbar/ProfileDropdown.vue:168]: Could you pls check if this change would break something? I have seen that the `closeBurgerMenu` event was listened at several places. How about providing both two kinds of events.
image

File: components/shared/ConnectWalletButton.vue (hunk 1 above)
Comment (Jarsen136) [reply components/shared/ConnectWalletButton.vue:34]: Is there any better way to handle this case? The function name is `toggleWalletConnectModal` which is not related to mobile check I guess : )

**Review by daiagi — CHANGES_REQUESTED** [review]
Connect button doesn't work on some device
I have a laptop that can be folded into tablet and it doesn't work on this device (when folded in tablet mode)
probably because of this:
````import { isMobileDevice } from '@/utils/extension'```

please don't use this to check screen dimensions, it doesn't work as expected, it checks user agent...

image

File: components/navbar/ProfileDropdown.vue (hunk 2 above)
Comment (prachi00) [reply components/navbar/ProfileDropdown.vue:168]: closeBurgerMenu is also being called inside toggleWalletConnectModal, so its all working fine

**Comment by prachi00** [comment]
> Connect button doesn't work on some device I have a laptop that can be folded into tablet and it doesn't work on this device (when folded in tablet mode) probably because of this: `import { isMobileDevice } from '@/utils/extension'`
> 
> please don't use this to check screen dimensions, it doesn't work as expected, it checks user agent...
> 
> image

maybe in another issue we can refactors this utils function then if it isnt usable, for now I have used 
  private isMobile = ref(window.innerWidth < 1024)

which is the same check we are using to show the menu on mobile so all good

**Comment by daiagi** [comment]
wfm on desktop
could you do the same for tablet?

[screen-capture.webm](https://user-images.githubusercontent.com/22791238/230858506-0e10c4c3-4f83-4206-8100-22439aba6dcf.webm)

**Comment by daiagi** [comment]
>  for now I have used
private isMobile = ref(window.innerWidth < 1024)

works now. thanks

**Review by Jarsen136 — APPROVED** [review]
It's a strange fix but works for me

**Comment by prachi00** [comment]
> wfm on desktop could you do the same for tablet?

bit tricky to do the same on mobile, pulling this in for a separate issue

**Review by daiagi — APPROVED** [review]
bug fixed on desktop
needs fixing in mobile /tablet as well
* #5636

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 37.26 USD/KSM ~ 0.805 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x6aacb845986c9709697b23daa0ca30bc0bd3b4744701cff8c243fbc4d055c20a](https://kusama.subscan.io/extrinsic/0x6aacb845986c9709697b23daa0ca30bc0bd3b4744701cff8c243fbc4d055c20a)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
