### PR TITLE
fix: snek bugs

### LINKED ISSUE #3186: Balance Input should be handled as BigInt
### What happened?

the problem is that Balance input uses numbers 
and then the number is multiplied by `value * 10 ** decimals` and it simply fails on numbers bigger than 9k KSM ([MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER))

### Please reproduce in steps

- [ ] go to basilisk
- [ ] send 10k BSX
- [ ] Will see err

### Expected Behavior

The Balance input should operate in BigInt and emmited value should be string/BigInt

- [ ] Code
- [ ] make tests
- [ ] test properly one more time (transfer, list, mint)
- [ ] make sure you added helper functions 

### What browsers are you seeing the problem on?

_No response_

### Are you logged in?

Yes

### At which address did you encounter bug?

beta.kodadot.xyz

### Screenshots

Screenshot 2022-06-19 at 12 25 25

@yangwao 
174477623-4416d3a1-b7a0-4053-96fc-03b619e96b43

### Relevant log output

_No response_

### Payment link for reward

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

## REF
 - #3163
 - #3191
 - #3189

### LINKED ISSUE #3187: wrong redirect to rmrk
clicking on collection in profile detail redirects to rmrk collection (should be bsx)
image
image

### LINKED ISSUE #3188: Explorer on BSX gallery don't show any items
It Seems collections show something, but in an explorer-like gallery, I see nothing?

image

Collections seems ok 

image

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/3171#issuecomment-1159684521_

### PR DESCRIPTION
**Pull request by petersopko**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3186, closes #3188, closes #3187 
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

File: components/rmrk/Profile/NavbarProfileDropdown.vue [hunk 1]
```diff
@@ -34,23 +34,23 @@
       <b-dropdown-item v-if="isRmrk" has-link aria-role="menuitem">
         <nuxt-link to="/rmrk/admin">{{ $t('Admin') }}</nuxt-link>
       </b-dropdown-item>
-      <b-dropdown-item has-link aria-role="menuitem">
+      <b-dropdown-item has-link aria-role="menuitem" v-if="isRmrk">
```
Comment (vikiival) [inline components/rmrk/Profile/NavbarProfileDropdown.vue:37]: add to `<template>` to avoid repetition

**Review by vikiival — CHANGES_REQUESTED** [review]
smol stuff

**Review by vikiival — APPROVED** [review]
