### PR TITLE
Fixing IdentityPopover Last bought

### LINKED ISSUE #3160: IdentityPopover Last bought
It show "Last bought 4month ago" when I bought one 14 days ago

Capture d’écran 2022-06-16 à 10 08 29 AM
Capture d’écran 2022-06-16 à 10 08 47 AM

_Originally posted by @roiLeo in https://github.com/kodadot/nft-gallery/pull/3153#pullrequestreview-1008663687_

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #3160
- [ ] Requires deployment <rubick/magick_issue>
- [x] Added another query to fetch this information, cant think of any other better solution for this 

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
- [x] [Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

File: components/shared/IdentityPopover.vue [hunk 1]
```diff
@@ -113,6 +115,19 @@ export default class IdentityPopover extends mixins(
   protected totalCollected = 0
   protected totalSold = 0
 
+  public async mounted() {
+    const { data } = await this.$apollo.query<{ events: Interaction[] }>({
+      query: buyEventByProfile,
+      client: 'subsquid',
```
Comment (Jarsen136) [inline components/shared/IdentityPopover.vue:121]: This query could not work on the bsx chain.

**Review by Jarsen136 — COMMENTED** [review]
Let's wait until #3153 is merged, so that we could add query parameter into `userStatsByAccount.graphql` instand of creating a new query.

`userStatsByAccount` could work on both rmrk and bsx chain.

File: components/shared/IdentityPopover.vue (hunk 1 above)
Comment (vikiival) [reply components/shared/IdentityPopover.vue:121]: Nice catch

Comment (prachi00) [reply components/shared/IdentityPopover.vue:121]: one doubt tho, why are we using subquery userStatsByAccount in rmrk and subsquid in bsx?

**Comment by prachi00** [comment]
so I tried using userStatsByAccount for getting events info, but it wasn't always giving the correct info in the 0th position, so it was kinda hard to get the buy event always
so decided it was better to use a new one only, updated new query to be supported by all chains, lmkwyt

**Comment by vikiival** [comment]
the please use 

`client: this.client`

This means it will use subsquid on all chains

**Comment by prachi00** [comment]
> the please use
> 
> `client: this.client`
> 
> This means it will use subsquid on all chains

replaced!

**Comment by petersopko** [comment]
@prachi00 can you check/confirm this one works as well?
- https://github.com/kodadot/nft-gallery/issues/3225

File: components/shared/IdentityPopover.vue (hunk 1 above)
Comment (vikiival) [reply components/shared/IdentityPopover.vue]: > why are we using subquery userStatsByAccount in rmrk and subsquid in bsx?
not sure that you mean

**Review by roiLeo — COMMENTED** [review]
Fixed for me
Capture d’écran 2022-06-21 à 1 57 14 PM

Still weird for `/rmrk/u/DSdZVzpW6MZgYw2ajxXLmDYox17X8SnNzSz5rGyZ6niiA8j`

Capture d’écran 2022-06-21 à 1 59 15 PM

maybe some burned nfts are still in query?

File: components/shared/IdentityPopover.vue [hunk 2]
```diff
@@ -190,18 +205,11 @@ export default class IdentityPopover extends mixins(
       } else if (data?.firstMint?.nodes?.length > 0) {
         this.firstMintDate = data.firstMint.nodes[0].createdAt
       }
-
-      if (data?.collected?.nodes?.length > 0) {
-        this.lastBoughtDate = data.collected.nodes[0].collection.createdAt
-      } else if (data?.collected?.edges?.length > 0) {
-        this.lastBoughtDate = data.collected.edges[0].node.events[0].timestamp
-      }
```
Comment (Jarsen136) [inline components/shared/IdentityPopover.vue:198]: It would be better if we fetch the data from `userStatsByAccount`, so that we do not need to request twice for every identity. What's more, it could be cached.

If not, let's delete `lastBoughtDate` stuff in `userStatsByAccount.graphql`

Comment (prachi00) [reply components/shared/IdentityPopover.vue:198]: I tried using `userStatsByAccount` but it just wont give the correct format of data that is required for this

I have deleted the stuff from` userStatsByAccount.graphql `

**Comment by prachi00** [comment]
> Fixed for me Capture d’écran 2022-06-21 à 1 57 14 PM
> 
> Still weird for `/rmrk/u/DSdZVzpW6MZgYw2ajxXLmDYox17X8SnNzSz5rGyZ6niiA8j`
> 
> Capture d’écran 2022-06-21 à 1 59 15 PM
> 
> maybe some burned nfts are still in query?

@roiLeo added `collected` check as well to fix this, so it won't show up if an account doesn't have any collected

File: components/shared/IdentityPopover.vue (hunk 2 above)
Comment (Jarsen136) [reply components/shared/IdentityPopover.vue:198]: Ok. There is still something unused query in `@/queries/userStatsByAccount.graphql`. Let's delete it and it's good to go.

Comment (prachi00) [reply components/shared/IdentityPopover.vue:198]: Done!

File: components/shared/IdentityPopover.vue [hunk 3]
```diff
@@ -94,6 +94,8 @@ import CreatedAtMixin from '@/utils/mixins/createdAtMixin'
 import { isAfter, subHours } from 'date-fns'
 import shouldUpdate from '@/utils/shouldUpdate'
 import resolveQueryPath from '@/utils/queryPathResolver'
+import { Interaction } from '@/components/rmrk/service/scheme'
+import buyEventByProfile from '@/queries/rmrk/subsquid/buyEventByProfile.graphql'
```
Comment (roiLeo) [inline components/shared/IdentityPopover.vue:98]:
```suggestion
```

**Review by roiLeo — APPROVED** [review]
> @roiLeo added `collected` check as well to fix this, so it won't show up if an account doesn't have any collected

Capture d’écran 2022-06-24 à 3 17 09 PM

not sure about this one but the rest is ok you fixed "sold" stat

✅ lgtm

**Comment by Jarsen136** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 57.94 USD/KSM ~ 1.726 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xb0ec64aa2237d673d3b39e44ef6639a2450c4269e6d98786a813d9dd2b130b4c](https://kusama.subscan.io/extrinsic/0xb0ec64aa2237d673d3b39e44ef6639a2450c4269e6d98786a813d9dd2b130b4c)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
