### PR TITLE
quick fix: ensure drop loading state can be cleared

### LINKED ISSUE #9585: button on the old drop is always loading
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

The "see lists" & "generating" buttons on the old drop is always loading

https://canary.kodadot.xyz/ahp/drops/motherboard

### Please reproduce in steps

- go to https://canary.kodadot.xyz/ahp/drops/motherboard
- see the buttons

### Expected Behavior

After some time has passed, the "see lists" & "generating" buttons should work as expected when clicked

### What browsers are you seeing the problem on?

_No response_

### At which address did you encounter bug?

_No response_

### Are you logged in?

None

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

https://github.com/kodadot/nft-gallery/assets/10708802/61eaf1f1-c3a1-4709-a6a8-76e8f4e7b82d

### Wallet Address & Transaction hash

_No response_

### Relevant log output

_No response_

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by newraina**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

 The reason for the issue is: In the sketch code of old drop, `kodahash/render/completed` event might not exist.

## Context

- [x] Closes #9585 
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer?target=1CAv6Zq3yVxL3eKhC94GWTWVwp1w4jZbqeZ6wXx1rPAhrce&usdamount=0&donation=true)

## Screenshot 📸

- [ ] My fix has changed UI

### CODE REVIEW

File: components/collection/drop/GenerativePreview.vue [hunk 1]
```diff
@@ -112,6 +112,15 @@ const props = defineProps<{
...
 const emit = defineEmits(['generation:start', 'generation:end', 'mint'])
 const { imageDataPayload, imageDataLoaded } = useGenerativeIframeData()
+
+const { start: startTimer } = useTimeoutFn(() => {
+  // quick fix: ensure that even if the completed event is not received, the loading state of the drop can be cleared
+  if (!props.mintCountAvailable && !imageDataLoaded.value) {
+    isLoading.value = false
+    emit('generation:end')
+  }
+}, 3000)
```
Comment (Jarsen136) [inline components/collection/drop/GenerativePreview.vue:122]: It's not enough because sometimes drop could take 10+ s.

I would suggest adding the check that this drop has been minted out, so it only apply to `old` drop.

Comment (newraina) [reply components/collection/drop/GenerativePreview.vue:122]: `!props.mintCountAvailable` check should be enough?

Comment (Jarsen136) [reply components/collection/drop/GenerativePreview.vue:122]: Okay, could you add a comment that it is only for old drops?

Comment (Jarsen136) [reply components/collection/drop/GenerativePreview.vue:122]: What if the user trigger the variation button again?

Comment (newraina) [reply components/collection/drop/GenerativePreview.vue]: @Jarsen136 done

File: components/collection/drop/GenerativePreview.vue [hunk 2]
```diff
@@ -112,6 +112,16 @@ const props = defineProps<{
...
 const { imageDataPayload, imageDataLoaded } = useGenerativeIframeData()
+
+const { start: startTimer } = useTimeoutFn(() => {
+  // quick fix: ensure that even if the completed event is not received, the loading state of the drop can be cleared
+  // only applicable if drop is ended (mintCountAvailable is false)
+  if (!props.mintCountAvailable && !imageDataLoaded.value) {
+    isLoading.value = false
+    emit('generation:end')
+  }
+}, 3000)
```
Comment (Jarsen136) [inline components/collection/drop/GenerativePreview.vue:123]:
```suggestion
 // only applicable if the drop is old one that missing`kodahash/render/completed` event
 
  if (!props.mintCountAvailable && !imageDataLoaded.value) {
    isLoading.value = false
    emit('generation:end')
  }
}, 5000)
```

**Review by Jarsen136 — APPROVED** [review]

**Review by preschian — APPROVED** [review]

**Comment by prury** [comment]
> @prury good to go?

yup

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 8.46 USD/DOT ~ 3.546 $DOT
🧗 [1CAv6Zq3yVxL3eKhC94GWTWVwp1w4jZbqeZ6wXx1rPAhrce](https://polkadot.subscan.io/account/1CAv6Zq3yVxL3eKhC94GWTWVwp1w4jZbqeZ6wXx1rPAhrce)
🔗 [0xb8cc711595b89dcf88918c70800f4f6db73b11e018002005cfa1c00576b61538](https://polkadot.subscan.io/extrinsic/0xb8cc711595b89dcf88918c70800f4f6db73b11e018002005cfa1c00576b61538)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
