### PR TITLE
fix: Avatar image does not fit

### LINKED ISSUE #11124: Avatar image does not fit
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

avatar image does not fit, especially for non-square images

image

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #11124

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image
image
image

### CODE REVIEW

File: libs/ui/src/components/MediaItem/type/ImageMedia.vue [hunk 1]
```diff
@@ -81,9 +83,9 @@ const loading = computed<'eager' | 'lazy'>(() =>
 )
 
 const className = computed(() =>
-  !props.original && !props.isFullscreen
+  `${(!props.original && !props.isFullscreen
     ? 'object-contain absolute inset-0 w-full h-full !rounded-none'
-    : 'block !rounded-none',
+    : 'block !rounded-none')} ${props.innerClass}`,
```
Comment (vikiival) [inline libs/ui/src/components/MediaItem/type/ImageMedia.vue:88]: isn't it easier to have backticks only on the second statment?

**Review by vikiival — APPROVED** [review]
Otherwise ok

**Review by hassnian — APPROVED** [review]

File: libs/ui/src/components/MediaItem/type/ImageMedia.vue (hunk 1 above)
Comment (Jarsen136) [reply libs/ui/src/components/MediaItem/type/ImageMedia.vue]: updated

**Review by vikiival — APPROVED** [review]
