### PR TITLE
fix: Retry transaction is not displayed after canceling signing

### LINKED ISSUE #9632: Retry transaction is not displayed after canceling signing
image

after i canceled the sign, the retry button did not appear 

tested on canary as well - happened to me in gallery detail
image

https://canary.kodadot.xyz/ahp/gallery/106-30

using polkadot js

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #9632

## Needs QA check

- @kodadot/qa-guild please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

https://github.com/kodadot/nft-gallery/assets/44554284/75e645aa-9d15-4fad-85a4-efda1b0410fd

### CODE REVIEW

File: composables/autoTeleport/useAutoTeleportTransactionActions.ts [hunk 1]
```diff
@@ -58,9 +35,9 @@ export default function (actions: ComputedRef<AutoTeleportAction[]>) {
 
   watch(
     actions,
-    (newActions, prevActions) => {
-      newActions.forEach((action, index) => {
-        const cancelled = isCancelled(action, prevActions?.[index])
+    (actions) => {
```
Comment (preschian) [inline composables/autoTeleport/useAutoTeleportTransactionActions.ts:38]: Since we are not using the previous state, can we use `watchEffect` instead of `watch` here?

**Review by preschian — APPROVED** [review]

File: composables/autoTeleport/useAutoTeleportTransactionActions.ts (hunk 1 above)
Comment (hassnian) [reply composables/autoTeleport/useAutoTeleportTransactionActions.ts:38]: just checked, `watchEffect` does not watch for `deep` changes

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 10.31 USD/DOT ~ 2.91 $DOT
🧗 [16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD](https://polkadot.subscan.io/account/16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)
🔗 [0xe166ddc15f24586a42d2a365b1b5f75e6138311861f4b39d79b1c58d986aa533](https://polkadot.subscan.io/extrinsic/0xe166ddc15f24586a42d2a365b1b5f75e6138311861f4b39d79b1c58d986aa533)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
