### PR TITLE
fix: some images can't load  in profile activity table

### LINKED ISSUE #7121: images in profile activty table not loading
image

### PR DESCRIPTION
**Pull request by xiiiAtCn**
Pull Request Template

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #7121 
- [ ] Requires deployment <snek/rubick/worker>

## Reason

NFT's image link may be store in `NFTMetadata.mediaUri` instead of `Metadata.image`

#### Did your issue had any of the "$" label on it?

- [x] my DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=12jXHf7yYF4wTRjDPbwFB24V1nVRPRkuU2S8Ke5ZWTfvyBGW&usdamount=8.82&donation=true)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

### <samp>🤖 Generated by Copilot at 9bf7ebb</samp>

Improved NFT avatar parsing by using `mediaUri` as a fallback option. This affects the `parseNftAvatar` function in `utils/nft.ts`.

### <samp>🤖 Generated by Copilot at 9bf7ebb</samp>

> _`parseNftAvatar`_
> _Finds `mediaUri` if no `image`_
> _A better gallery_

### CODE REVIEW

**Comment by daiagi** [comment]
Seem doesn't work

**Comment by xiiiAtCn** [comment]
@daiagi  The most are worked  for me.  Small part not. I will figure out why they are not worked as expected.

File: components/profile/activityTab/HistoryRow.vue [hunk 1]
```diff
@@ -135,25 +135,23 @@
...
 import BlockExplorerLink from '@/components/shared/BlockExplorerLink.vue'
-
+import { useGalleryItem } from '@/components/gallery/useGalleryItem'
 const props = defineProps<{
   event: Event
   withToColumn: boolean
   variant: 'Desktop' | 'Touch'
 }>()
 
+const { nftResources, nftImage } = useGalleryItem(props.event.Item.id)
```
Comment (daiagi) [inline components/profile/activityTab/HistoryRow.vue:152]: nope.
this will make a graphql call for each row, where you should already get all the data you need in the call that fetches the events

image

Comment (xiiiAtCn) [reply components/profile/activityTab/HistoryRow.vue:152]: Some of your nfts can't get their image urls with `processSingleMetadata`  method in `nft.parseNftAvatar`. Each of them has  more than one image, for example [Referendum 209](https://kodadot.xyz/ksm/gallery/13485165-3208723ec6f65df810-ITEM-209ST-00000317) . This api responds with 
```
"'Stamp'

In Referendum 209 the community voted on whether to reset the Pichiu Parachain in order to fix bugs. The underlying proposal of this Referendum has been replaced by Referendum 205. Since Referendum 205 has passed community vote already, this Referendum was superfluous.

Artist: @kseniashikh

Type of vote: Direct."
```
I have to get their images by graphql call. It's better to  fix this abnormal response so that we can keep efficient.

Comment (daiagi) [reply components/profile/activityTab/HistoryRow.vue:152]: see `useGalleryItem` line 113
`nftMetadata.value = await getNftMetadata(nftEntity, urlPrefix.value)`

uses `getNftMetadata`

this is in contrast to `parseNftAvatar` that uses `processSingleMetadata`

that's the direction I would look at

Comment (xiiiAtCn) [reply components/profile/activityTab/HistoryRow.vue:152]: `parseNftAvatar` call stack:
 - processSingleMetadata

`getNftMetadata` call stack:
- getProcessMetadata
  - processSingleMetadata

they both come to the same method at last.

Comment (daiagi) [reply components/profile/activityTab/HistoryRow.vue:152]: let's look at `getNFTMetadata`:
image

where do we have problem with profile activity images? on rmrk2
image


so in this case we need the resources field on the nft.

but wait , the query to get the events doesn't fetch resources field:

```graphql
query allEventsByProfile($id: String) {
  events(where: {caller_eq: $id, OR: {currentOwner_eq: $id}}) {
    meta
    interaction
    blockNumber
    timestamp
    currentOwner
    caller
    id
    nft {
      id
      name
      metadata
      collection {
        id
        name
        __typename
      }
      __typename
    }
    __typename
  }
}
```

so what need to be done?

1. make the query fetch resources
2.  use `getNftMetadata`  from `useNFT` composable

Comment (daiagi) [reply components/profile/activityTab/HistoryRow.vue]: Please don't resolve conversations that reviewers started
It is up to me to do so

Comment (xiiiAtCn) [reply components/profile/activityTab/HistoryRow.vue]: mb. I don't do this before

File: components/profile/activityTab/HistoryRow.vue [hunk 2]
```diff
@@ -170,7 +168,9 @@ const interactionName = computed(
 
 const getAvatar = async () => {
   if (props.event.Item) {
-    avatar.value = await parseNftAvatar(props.event.Item)
+    avatar.value = (
+      await getNftMetadata(props.event.Item, urlPrefix.value)
+    ).image
```
Comment (daiagi) [inline components/profile/activityTab/HistoryRow.vue:173]: Please fix `parseNftAvatar` instead of fixing it here
as other components are also using `parseNftAvatar`

**Review by daiagi — CHANGES_REQUESTED** [review]
yes sir
This is the right solution

The only thing is please fix `pasrseNftAvatar` instead of fixing only `HistoryRow`

Thank you

**Comment by daiagi** [comment]
the pictures are loading well but....
the events don't always load
i needed to refresh the page to get it to load

reproduce:

go to profile page
click activity tab

**Review by daiagi — APPROVED** [review]
lgtm

**Review by preschian — APPROVED** [review]

**Review by prury — APPROVED** [review]

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 4.23 USD/DOT ~ 11.82 $DOT
🧗 [12jXHf7yYF4wTRjDPbwFB24V1nVRPRkuU2S8Ke5ZWTfvyBGW](https://polkadot.subscan.io/account/12jXHf7yYF4wTRjDPbwFB24V1nVRPRkuU2S8Ke5ZWTfvyBGW)
🔗 [0xaf92974ca46d161982bc977814604913a0df5b34cccd4651b6e3532bd3bba787](https://polkadot.subscan.io/extrinsic/0xaf92974ca46d161982bc977814604913a0df5b34cccd4651b6e3532bd3bba787)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
