### PR TITLE
fix: Offer expiration dropdown moving on scroll

### LINKED ISSUE #10951: Offer expiration dropdown moving on scroll
https://github.com/user-attachments/assets/83cfdc95-fd7e-4598-802c-e1d3cc9513df

followup for: 
- https://github.com/kodadot/nft-gallery/pull/10909

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs Design check

- @exezbcz please review

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #10951

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

x

### CODE REVIEW

**Review by hassnian — DISMISSED** [review]

File: libs/ui/src/components/NeoDropdown/NeoDropdown.vue [hunk 1]
```diff
@@ -90,6 +94,7 @@ export default {
     else {
       this.autoPosition = this.position
     }
+    watch(useElementBounding(this.$refs.trigger).top, this.onTriggerMove)
```
Comment (hassnian) [inline libs/ui/src/components/NeoDropdown/NeoDropdown.vue:97]:
```suggestion
    if (this.closeMenuOnMove) {
       watch(useElementBounding(this.$refs.trigger).top, this.onTriggerMove)
      }
```

File: libs/ui/src/components/NeoDropdown/NeoDropdown.vue [hunk 2]
```diff
@@ -105,6 +110,11 @@ export default {
           : 'left'
       this.autoPosition = this.position.replace('auto', side)
     },
+    onTriggerMove() {
+      if (this.closeMenuOnMove && this.isActive) {
+        this.isActive = false
+      }
```
Comment (hassnian) [inline libs/ui/src/components/NeoDropdown/NeoDropdown.vue:116]:
```suggestion
      if (this.isActive) {
        this.isActive = false
      }
```

**Review by hassnian — COMMENTED** [review]
small improvement, avoids unnecessary watchers

**Review by vikiival — APPROVED** [review]
