### PR TITLE
:bug: ability to sign transactions with any extension

### LINKED ISSUE #2594: Is the emote feature broken?
### What happened?

when I want to press the emoticon button I select it only appears "Error: Unable to retrieve key pair". 
even though I'm already connected to the site

### Please reproduce in steps

click emoticon

### Expected Behavior

I've expected ...

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

Yes

### At which address did you encounter bug?

beta.kodadot.xyz, kodadot.xyz

### Screenshots

Screenshot_5
Screenshot_2

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer/?target=GF4v68qJmh47eShYNpPs5JNfn5bxG5Kz1U2Y4xC2xAqXqmq

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #2607: Unable to retrieve keypair
Seems I can't dispatch tx :| 
But I guess it's related https://docs.kodadot.xyz/tutorials/how-to-fix-error-keypair.html#_1-are-you-using-a-ledger-hardware-wallet :|

https://kodadot.xyz/transfer/?target=G29NScLSew5zqwmJAPupvJWDCDkpxKUhDnMeVdD2BBcnHar&usdamount=500

image

image

no update here 
image

@cryptodamsky 🥺

### PR DESCRIPTION
**Pull request by vikiival**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

What: the previous implementation relies on the fact that we support only one extension.
Since our wallet model changed: App checked if the address is in the polkadot-js (false) fallback was keypair (false) so it threw error.

ht/ @roiLeo for the nice wallet impl :)

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2607
- [x] Closes #2594
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

### Optional

- [x] I've tested it [Kusama Bot 075 :: robot emote] rmrk/gallery/11895344-900D19DC7D3C444E4C-KSMBOT-KUSAMA_BOT_075-0000000000000078
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### CODE REVIEW

File: utils/extension.ts [hunk 1]
```diff
@@ -1,12 +1,19 @@
...
+import { getWalletBySource, WalletAccount } from '@/utils/config/wallets'
 
 export const enableExtension = async () => await web3Enable('KodaDot')
 
 export const getAddress = async (address: string) => {
   try {
-    const injector = await web3FromAddress(address)
-    return injector
+    const walletName = localStorage.getItem('wallet')
+    console.log(walletName)
```
Comment (roiLeo) [inline utils/extension.ts:9]:
```suggestion
```

**Comment by yangwao** [comment]
seems emote worked https://deploy-preview-2614--koda-nuxt.netlify.app/rmrk/gallery/10871723-7294d22dea11a96c3f-ZEUE1-PINKY-0000000000000018

image

**Comment by yangwao** [comment]
managed to submit list wfm https://deploy-preview-2614--koda-nuxt.netlify.app/rmrk/detail/11626180-160a6f4320f11acb25-LCKWV-PIXEL_BABE_092-0000000000000092?event=all
