### PR TITLE
fix: HolderOf does not work on drops

### LINKED ISSUE #9386: HolderOf does not work on drops
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

I want to mint [reflection](https://canary.kodadot.xyz/ahk/drops/reflection)
but I cannot because UI tells me 'Conditions not Met'

Screenshot 2024-02-13 at 10 14 17

However [I have minted my complexity NFT](https://canary.kodadot.xyz/ahk/gallery/352-35)

### Please reproduce in steps

1. [Mint Complexity](https://canary.kodadot.xyz/ahk/drops/complexity)
2. [Go to Reflection](https://canary.kodadot.xyz/ahk/drops/reflection)
3. You are unable to mint

### Expected Behavior

I expect to be able to mint **reflection** when I am holder of **complexity**

### What browsers are you seeing the problem on?

_No response_

### At which address did you encounter bug?

_No response_

### Are you logged in?

None

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

~

### Wallet Address & Transaction hash

_No response_

### Relevant log output

_No response_

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #9386

image

https://assethub-kusama.subscan.io/extrinsic/6415378-2

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [ ] My fix has changed UI

  ## Copilot Summary
  copilot:summary

  copilot:poem

### CODE REVIEW

File: components/collection/drop/HolderOfGenerative.vue [hunk 1]
```diff
@@ -253,27 +246,22 @@ const mintNft = async () => {
     }
 
     initTransactionLoader()
-    const cb = api.tx.utility.batchAll
-    const mint = api.tx.nfts.mint(
+    const cb = api.tx.nfts.mint
+
+    const args = [
       collectionId.value,
       collectionRes.items,
```
Comment (preschian) [inline components/collection/drop/HolderOfGenerative.vue:253]: @Jarsen136 @vikiival should we revert this section on paid drops component until this issue is resolved? https://github.com/kodadot/nft-gallery/issues/9328

Comment (vikiival) [reply components/collection/drop/HolderOfGenerative.vue:253]: #9328 has nothing to do with a on-chain BadWitness error.
The implementation is correct.
