### PR TITLE
fix: Sorting by price in offers made doesn't work properly

### LINKED ISSUE #3549: Sorting by price in offers made doesn't work properly
Sorting by price in offers made seems doesn't work. 
I recall we fixed it already in the global offers list?

feel free to test it here https://beta.kodadot.xyz/bsx/u/bXgvP2cQzEnPvuPQHRghz9dUYovqzyPhXBRXbNwVCef7nsmqb?tab=offers 

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3549 
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

File: components/bsx/Offer/OffersUserTable.vue [hunk 1]
```diff
@@ -88,6 +89,13 @@ export default class OffersUserTable extends mixins(
     return formatDistanceToNow(new Date(date), { addSuffix: true })
   }
 
+  get displayOffers() {
```
Comment (prachi00) [inline components/bsx/Offer/OffersUserTable.vue:92]: I see that we use this getter in 2 other files, would it be possible to add it in `offermixin` or somewhere else to avoid repetition?

Comment (Jarsen136) [reply components/bsx/Offer/OffersUserTable.vue]: make sense!

**Review by prachi00 — APPROVED** [review]

**Comment by prachi00** [comment]
@Jarsen136 we have some conflicts nowww

**Review by petersopko — APPROVED** [review]
wfm

**Comment by petersopko** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 62.74 USD/KSM ~ 0.797 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x7c7192bf4237488bd43056bf39e7bda343af84afccdbe4c0c0cc125f588236da](https://kusama.subscan.io/extrinsic/0x7c7192bf4237488bd43056bf39e7bda343af84afccdbe4c0c0cc125f588236da)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 62.73 USD/KSM ~ 0.797 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x296dc3a90d0f850888c677a7bf3e74123f67dca0ca547b09a2a6c8d50e7ee14f](https://kusama.subscan.io/extrinsic/0x296dc3a90d0f850888c677a7bf3e74123f67dca0ca547b09a2a6c8d50e7ee14f)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
