### PR TITLE
Gallery item video full screen not working as expected

### LINKED ISSUE #10083: Gallery item video full screen not working as expected?
### What happened?

I think the full screen button should open the video on full screen mode and not do what it's doing now

https://github.com/kodadot/nft-gallery/assets/44554284/9ece6587-fd5a-4ee0-b7b0-a5be572c1b91

### PR DESCRIPTION
**Pull request by Temidayo32**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #10083 
- [ ] Requires deployment <worker/stick/speck>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ahp/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [ ] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=14rs1iTduAn9YrqtDwsTZxK9YDbkzDekBstqxc78M6An87fX&usdamount=0)

#### Community participation

- [x] [Are you at Koda Ecosystem Telegram?](https://t.me/koda_eco)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
fullscreen

### CODE REVIEW

File: libs/ui/src/components/MediaItem/type/VideoMedia.vue [hunk 1]
```diff
@@ -38,6 +43,8 @@ const props = withDefaults(
 )
 
 const video = ref()
+const imgref = ref<HTMLElement | null>(null)
```
Comment (Jarsen136) [inline libs/ui/src/components/MediaItem/type/VideoMedia.vue:46]: `imgref` It does nothing here.

**Review by Jarsen136 — CHANGES_REQUESTED** [review]
The fullscreen preview for video is still not ideal. I have to click buttons twice to enter the real fullscreen mode.
Kapture 2024-04-16 at 20 10 53



Could you please make it like the demo for `useFullscreen` ?
ref: https://vueuse.org/core/useFullscreen/

image

**Comment by Temidayo32** [comment]
> The fullscreen preview for video is still not ideal. I have to click buttons twice to enter the real fullscreen mode. Kapture 2024-04-16 at 20 10 53 [ Kapture 2024-04-16 at 20 10 53 ](https://private-user-images.githubusercontent.com/31397967/322954621-5c30e7cf-a935-40e1-b63d-66c5b7c0a5a2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NTE2NTAsIm5iZiI6MTcxMzU1MTM1MCwicGF0aCI6Ii8zMTM5Nzk2Ny8zMjI5NTQ2MjEtNWMzMGU3Y2YtYTkzNS00MGUxLWI2M2QtNjZjNWI3YzBhNWEyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDE4MjkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5MGE4NjdhMmVkMWRmMTA0MjRjNDFjOWVhMTMzYjdkM2M4YmQ0NGM3OTkwZjJlZWQ3ZmYxYzkzZGQ2ODAyMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VhAKikZznF4CgvNnKUQ6PpjOleHG0sCJRbqBlCfFosY) [ ](https://private-user-images.githubusercontent.com/31397967/322954621-5c30e7cf-a935-40e1-b63d-66c5b7c0a5a2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NTE2NTAsIm5iZiI6MTcxMzU1MTM1MCwicGF0aCI6Ii8zMTM5Nzk2Ny8zMjI5NTQ2MjEtNWMzMGU3Y2YtYTkzNS00MGUxLWI2M2QtNjZjNWI3YzBhNWEyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDE4MjkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5MGE4NjdhMmVkMWRmMTA0MjRjNDFjOWVhMTMzYjdkM2M4YmQ0NGM3OTkwZjJlZWQ3ZmYxYzkzZGQ2ODAyMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VhAKikZznF4CgvNnKUQ6PpjOleHG0sCJRbqBlCfFosY)
> 
> Could you please make it like the demo for `useFullscreen` ? ref: https://vueuse.org/core/useFullscreen/
> 
> image

I think the way to do this is to expose the `toggle` method from the video component and send it up through the component hierrachy (which is what I implemented and so should fix the problem).  The component hierrachy is probably getting in the way of the `toggleFullscreen` from properly working on the video element.

File: libs/ui/src/components/MediaItem/type/VideoMedia.vue [hunk 2]
```diff
@@ -1,9 +1,14 @@
 <template>
-  <div class="w-full h-full z-10 min-w-0 relative">
-    <div class="h-0 w-full pb-[100%]" />
+  <div
+    class="h-full min-w-0 relative"
+    :class="{ 'w-[95%]': isFullscreen, 'w-full': !isFullscreen }">
+    <div
+      class="h-0 w-full"
+      :class="{ 'pb-[65%]': isFullscreen, 'pb-[100%]': !isFullscreen }" />
```
Comment (Jarsen136) [inline libs/ui/src/components/MediaItem/type/VideoMedia.vue:7]:
```suggestion
  <div class="w-full h-full z-10 min-w-0 relative">
    <div class="h-0 w-full pb-[100%]" />
```

It does not need to change now. Could you pls revert it?

**Review by Jarsen136 — COMMENTED** [review]
otherwise lgtm

**Review by Jarsen136 — APPROVED** [review]

**Review by daiagi — APPROVED** [review]

**Comment by Temidayo32** [comment]
I just merged recent commits, and it appears the button isn't working. I am fixing that.

**Comment by Temidayo32** [comment]
Fixed some missing imports. Works fine now

File: components/base/MediaItem.vue [hunk 3]
```diff
@@ -174,7 +176,13 @@ const toggleContent = () => {
 
 const isMediaItemHovering = useElementHover(mediaItem)
 
-defineExpose({ isLewdBlurredLayer })
+function toggleVideoFullscreen() {
+  if (video.value.toggleVideoFullscreen) {
+    video.value.toggleVideoFullscreen()
+  }
+}
```
Comment (Jarsen136) [inline components/base/MediaItem.vue:183]: It makes no sense to call `toggleVideoFullscreen` inside the common `MediaItem` component. 

I would make the change like below:
MediaItem.vue:  `mediaRef.value.toggleFullscreen() `
VideoMedia.vue:  `const toggleFullscreen = () => { video.value.toggleVideoFullscreen()}`

**Review by Jarsen136 — COMMENTED** [review]
Look like there are some big changes after resolving code conflict.

File: components/base/MediaItem.vue (hunk 3 above)
Comment (Temidayo32) [reply components/base/MediaItem.vue:183]: I don't think it should follow this way. `toggleVideoFullscreen` is a method exposed directly from  `VideoMedia`. 

```
videomedia
const { toggle: toggleVideoFullscreen } = useFullscreen(video)

defineExpose({ toggleVideoFullscreen })
```
Calling this `const toggleFullscreen = () => { video.value.toggleVideoFullscreen()}` in the `MediaItem` component is because I created a `ref` called `video` on the `component` tag. 

```
<template>
  <div ref="mediaItem" class="media-object h-fit">
    <component
      :is="resolveComponent"
      ref="video"
      
      ....
      
      ````

Comment (Jarsen136) [reply components/base/MediaItem.vue:183]: I'm not talking about whether it will work. The current implementation will work but it's not easy to extend in the future. It also looks confusing. Setting `video` ref inside `MediaItem` is improper because it assumes that this component is only for `video`. 

What if I would like to customize the fullscreen process for `image` in the current implementation pattern? We need a unified method to adopt fullscreen mode for different kinds of nft.

Comment (Temidayo32) [reply components/base/MediaItem.vue:183]: Yes, absolutely, I agree with you. The unified method for fullscreen mode is actually already set in the `GalleryItem` component. And I think the reason each media type wasn't given its own fullscreen method initially was to avoid unnecessary duplication. However, it appears video is an exception. The current component hierarchy has a ref introduced for at least all child components used in each of the module files. The `useFullscreen` api requires the direct ref of the video file provided, and if otherwise, might not work as desired, which explains the issue with toggling video files to fullscreen. 

Perhaps, a trade-off here might be to use a generic name for the ref other than `video`. To reduce confusion.

File: libs/ui/src/components/MediaItem/type/VideoMedia.vue [hunk 4]
```diff
@@ -38,6 +38,7 @@ const props = withDefaults(
 )
 
 const video = ref()
+const { toggle: toggleVideoFullscreen } = useFullscreen(video)
```
Comment (Jarsen136) [inline libs/ui/src/components/MediaItem/type/VideoMedia.vue:41]:
```suggestion
const { toggle: toggleFullscreen } = useFullscreen(video)
```

File: libs/ui/src/components/MediaItem/type/VideoMedia.vue [hunk 5]
```diff
@@ -50,4 +51,6 @@ if (!autoPlay.value && props.src) {
     video.value.pause()
   })
 }
+
+defineExpose({ toggleVideoFullscreen })
```
Comment (Jarsen136) [inline libs/ui/src/components/MediaItem/type/VideoMedia.vue:55]:
```suggestion
defineExpose({ toggleFullscreen })
```

File: components/base/MediaItem.vue [hunk 6]
```diff
@@ -174,7 +176,13 @@ const toggleContent = () => {
...
+
+defineExpose({ isLewdBlurredLayer, toggleVideoFullscreen })
```
Comment (Jarsen136) [inline components/base/MediaItem.vue:185]:
```suggestion
defineExpose({ isLewdBlurredLayer, toggleFullscreen })
```

File: components/base/MediaItem.vue (hunk 3 above)
Comment (Jarsen136) [inline components/base/MediaItem.vue:183]:
```
 <component
      :is="resolveComponent"
      ref="mediaRef"
      ...
 />

const mediaRef = ref()

function toggleFullscreen() {
  if (mediaRef.value.toggleFullscreen) {
    mediaRef.value.toggleFullscreen()
  }
}


defineExpose({ isLewdBlurredLayer, toggleFullscreen })

```

File: components/gallery/GalleryItem.vue [hunk 7]
```diff
@@ -318,6 +323,15 @@ function toggleFullscreen() {
   })
 }
 
+function toggleFullscreen() {
+  const mediaType = resolveMedia(nftAnimationMimeType.value)
+  if ([MediaType.VIDEO].includes(mediaType)) {
+    mediaItemRef.value?.toggleVideoFullscreen()
```
Comment (Jarsen136) [inline components/gallery/GalleryItem.vue:329]:
```suggestion
    mediaItemRef.value?.toggleFullscreen()
```

**Review by Jarsen136 — COMMENTED** [review]
Could you try with this code? It should work the same as the previous implementation but with different naming.

File: components/base/MediaItem.vue (hunk 3 above)
Comment (Jarsen136) [reply components/base/MediaItem.vue:183]: > However, the `useFullscreen` api requires the direct ref of the video file provided, and if otherwise, might not work as desired, which explains the issue with toggling video files to fullscreen.
> 

Could you please check this? It should work.
https://github.com/kodadot/nft-gallery/pull/10089#pullrequestreview-2020074089
