### PR TITLE
fix: Disabled BUY button on bsx

### LINKED ISSUE #6309: Disabled BUY button
Tested on https://kodadot.xyz/stmn/gallery/19-2

Screenshot 2023-06-22 at 14-04-30 NFT Universe 2 KodaDot - NFT Market Explorer

Screenshot 2023-06-22 at 14-06-37 NFT Universe 2 KodaDot - NFT Market Explorer

### LINKED ISSUE #6411: buy button is always disabled on basilisk item page
### What happened?

buy button is always disabled on basilisk item page 

### Please reproduce in steps

open https://canary.kodadot.xyz/bsx/gallery/3030053998-6

### Expected Behavior

buy button should be available.

### Are you logged in?

Yes

### Screenshots

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context
1. style on the disabled button is wired. 
- [x] Closes #6309

2. KSM Balance does not load correctly on the bsx, so the button is always disabled.
- [x] Closes #6411

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed UI

image

### <samp>🤖 Generated by Copilot at ded8a70</samp>

This pull request adds support for buying NFTs with KSM on the Basilisk chain in `GalleryItemBuy.vue` and fixes a tooltip overflow issue in `NeoTooltip.vue`.

### <samp>🤖 Generated by Copilot at ded8a70</samp>

> _`urlPrefix` checks_
> _Basilisk and Kusama_
> _Autumn NFTs_

### CODE REVIEW

File: components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue [hunk 1]
```diff
@@ -120,6 +120,8 @@ const label = computed(() =>
 const balance = computed<string>(() => {
   if (['rmrk', 'ksm', 'stmn'].includes(urlPrefix.value)) {
     return identityStore.getAuthBalance
+  } else if (urlPrefix.value === 'bsx') {
```
Comment (roiLeo) [inline components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue:123]: No snek?

**Review by roiLeo — APPROVED** [review]
Otherwise lgtm

File: components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue (hunk 1 above)
Comment (Jarsen136) [reply components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue]: ✅ added

**Comment by prury** [comment]
@Jarsen136 it is indeed fixed for small KSM values, but strangely, even if i have: 
image
the buy button still stays disabled when i try to buy NFTs with .4 .3 KSM values

https://github.com/kodadot/nft-gallery/assets/36627808/59eb8e00-5317-42dc-9404-86203e7454c8

**Comment by Jarsen136** [comment]
> @Jarsen136 it is indeed fixed for small KSM values, but strangely, even if i have: image the buy button still stays disabled when i try to buy NFTs with .4 .3 KSM values
> 

Because you are buying item on bsx network, you should check the ksm balance on the bsx. From the screenshot, I could see there is not enough ksm balance

image

**Comment by prury** [comment]
pardon me @Jarsen136, brain defect on my side

File: components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue [hunk 2]
```diff
@@ -118,10 +118,19 @@ const label = computed(() =>
...
-    return identityStore.getAuthBalance
+  switch (urlPrefix.value) {
+    case 'rmrk':
+    case 'ksm':
+    case 'stmn':
+      return identityStore.getAuthBalance
+    case 'bsx':
+      return identityStore.multiBalances.chains.basilisk?.ksm?.nativeBalance
+    case 'snek':
+      return identityStore.multiBalances.chains['basilisk-testnet']?.ksm
```
Comment (vikiival) [inline components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue:129]: Me: let's call Basilisk on rococo as snek for simplicity
Someone: `basilisk-testnet`

**Review by vikiival — APPROVED** [review]
