### PR TITLE
fix: use ipfsio gateway on apple device

### LINKED ISSUE #11397: Video NFT not working
I swear this video was working yesterday: https://koda.art/ahp/gallery/312-11

It's not working today. I was preparing files for the NFT gallery, and this NFT was submitted; yesterday, I was checking it out, and today, I was preparing files.

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #11397

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

Screenshot 2025-02-06 at 17 08 22

### CODE REVIEW

File: utils/config/ipfs.ts [hunk 1]
```diff
@@ -24,6 +25,7 @@ const ipfsProviders: Partial<Record<IPFSProviders, string>> = {
   dweb: 'https://dweb.link/',
   image: kodaImage,
   nftStorage: 'https://nftstorage.link/',
```
Comment (Jarsen136) [inline utils/config/ipfs.ts:27]: can we delete it? `nftStorage`

**Review by Jarsen136 — COMMENTED** [review]
otherwise lgtm

**Comment by preschian** [comment]
updated, use dweb

**Review by Jarsen136 — APPROVED** [review]

File: utils/config/ipfs.ts [hunk 2]
```diff
@@ -23,7 +23,7 @@ const ipfsProviders: Partial<Record<IPFSProviders, string>> = {
   ipfs: DEFAULT_IPFS_PROVIDER,
   dweb: 'https://dweb.link/',
   image: kodaImage,
-  nftStorage: 'https://nftstorage.link/',
```
Comment (vikiival) [inline utils/config/ipfs.ts:26]: update the config then

**Review by hassnian — APPROVED** [review]
