### PR TITLE
fix: Cart icon scalling in quick actions

### LINKED ISSUE #8142: Cart icon scalling in quick actions
Followup for: 
- https://github.com/kodadot/nft-gallery/pull/8099

https://github.com/kodadot/nft-gallery/issues/6655#issuecomment-1768015727
- the icons provided there have the same outer container
- could we please make the icons so that when switching between active and default state it's not rescaling 

https://github.com/kodadot/nft-gallery/assets/90852205/fa32e016-d942-4f5f-9177-e16bef170afa

## gallery 
image

- the container the icon is wrapped in should be square

let me know if any other files are needed

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Needs Design check

  - @exezbcz please review

  ## Context

  - [x] Closes #8142
  - [ ] Requires deployment <snek/rubick/worker>

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image

  ## Copilot Summary
  
### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at c0c42aa</samp>

Improved the UI design and usability of the `GalleryItemBuy` component by adjusting its CSS properties. Modified the `outline-offset` and `border-width` properties in the `ktheme` mixin for the component and applied the same changes to its variant in the `ItemsGridImageTokenEntity` component.

  
### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at c0c42aa</samp>

> _To make the buy button more clear_
> _We tweaked the `ktheme` mixin here_
> _We changed the offset_
> _And the border we set_
> _To match the outline and appear_

### CODE REVIEW

**Comment by exezbcz** [comment]
cart != card

**Comment by Jarsen136** [comment]
> cart != card
> 
> the card is completely fine, it is about the cart icon that is jumping all over the place when active

Oh I see.

I found that it's because these two icons have different sizes. One is 22px but the other is 21.4px. Could you pls unify them on the figma, so that we can upload these icons again? @exezbcz 

image

File: components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue [hunk 1]
```diff
@@ -102,6 +102,9 @@ const onClickShoppingCart = () => {
 :deep(.button-height) {
   height: 55px !important;
 }
+.square-button-width {
+  width: 55px;
+}
```
Comment (roiLeo) [inline components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue:107]: I would use px-4 instead (even if it's not square square)

**Review by roiLeo — APPROVED** [review]
We don't need `button-height` class if you use prop `size="large"`

**Review by preschian — APPROVED** [review]

**Comment by exezbcz** [comment]
> One is 22px but the other is 21.4px. Could you pls unify them on the figma, so that we can upload these icons again? @exezbcz

I tried to export it in the frame with same size with its core icon same as well. Will try again I guess

File: components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue (hunk 1 above)
Comment (Jarsen136) [reply components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue]: `size="large"` does not work well because the 55px height is applied on different elements. I have replaced it with `px-4` as you mentioned.

Comment (roiLeo) [reply components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue]: > `size="large"` does not work well because the 55px height is applied on different elements. I have replaced it with `px-4` as you mentioned.

Have you tried to setup `size="large"` on the 2 `NeoButton` it was working on my side

Comment (Jarsen136) [reply components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue]: Yes, I have tried. It did not work as well.
image
image

Comment (roiLeo) [reply components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue]: 1px different ;(

Comment (roiLeo) [reply components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue]: continue in #7957

**Comment by exezbcz** [comment]
not sure if the svg will get exported inside the frame that has padding 
image


both icons there are with 20x20 px fixed frame 
image
image



these two exports have different size or? 
icon-fa62
custom-shopping2


cc @Jarsen136

**Comment by Jarsen136** [comment]
> these two exports have different size or? icon-fa62 custom-shopping2
> 
> cc @Jarsen136

Thank you! These two icons have the same size.

**Comment by Jarsen136** [comment]
> > these two exports have different size or? icon-fa62 custom-shopping2




@preschian Could you please help to upload these two icons to `fontawesome`? I have no account for it by the way.

 Their original id: `fa-striked-out-cart-shopping` `fa-shopping-cart-outline-sharp`

**Comment by roiLeo** [comment]
> @preschian Could you please help to upload these two icons to `fontawesome`? I have no account for it by the way.
> 
> Their original id: `fa-striked-out-cart-shopping` `fa-shopping-cart-outline-sharp`

DM me, I can provide credentials

**Comment by Jarsen136** [comment]
✅ Uploaded. It should work well now. @exezbcz  

Kapture 2023-11-22 at 00 12 27

**Comment by exezbcz** [comment]
@Jarsen136 smooth! thank you 


image
- could you please just center it out now, then it is perfect and I remain silent :D 



image
plus this centered in square

**Comment by Jarsen136** [comment]
> @Jarsen136 smooth! thank you
> 
> image
> 
> * could you please just center it out now, then it is perfect
> 
> image plus this centered in the square

✅ DONE

File: components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue [hunk 2]
```diff
@@ -13,11 +13,12 @@
         </div>
 
         <NeoButton
-          class="button-height no-border-left"
+          class="button-height square-button-width no-border-left"
           data-testid="item-add-to-cart"
           @click="onClickShoppingCart">
           <NeoIcon
             size="medium"
+            class="is-flex is-align-items-center is-justify-content-center"
```
Comment (roiLeo) [inline components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue:21]: I think you can use `class="icon"` instead

Comment (Jarsen136) [reply components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue]: Updated

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 5.21 USD/DOT ~ 5.758 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x5e5a79f4db9a64ea095733a44ee2fc3b4389f9e2761284e8433613a0ed9e2eff](https://polkadot.subscan.io/extrinsic/0x5e5a79f4db9a64ea095733a44ee2fc3b4389f9e2761284e8433613a0ed9e2eff)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
