### PR TITLE
fix: empty section on migrate page

### LINKED ISSUE #8577: Remove waiting for your action
image

- lets remove this section when its empty

### LINKED ISSUE #8578: Change copy in review step
in the review step it should be this 

image

currently, there is this and its not accurate 

telegram-cloud-photo-size-4-6037465636164190063-y

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #8577
- [x] Closes #8578

### CODE REVIEW

File: components/migrate/landing/Index.vue [hunk 1]
```diff
@@ -2,6 +2,48 @@
...
+    <div class="flex flex-col md:flex-row gap-4 justify-between">
+      <div>
+        <div
+          v-if="accountId"
+          class="flex flex-col md:flex-row gap-4 items-center">
+          <p class="mr-4">{{ $t('migrate.resultFor') }}</p>
+          <div class="flex">
+            <Avatar :value="accountId" :size="26" class="mr-2" />
+            <nuxt-link class="has-text-k-blue" :to="`/ksm/u/${accountId}`">
+              <Identity :address="accountId" hide-identity-popover />
```
Comment (roiLeo) [inline components/migrate/landing/Index.vue:14]:
```suggestion
              <IdentityIndex :address="accountId" hide-identity-popover />
```

File: components/migrate/landing/Index.vue [hunk 2]
```diff
@@ -2,6 +2,48 @@
...
+    </div>
+
+    <hr />
+    <MigrateLandingContent :key="sourceSelected?.value" />
   </div>
 </template>
+
+<script setup lang="ts">
+import { NeoIcon, NeoTooltip } from '@kodadot1/brick'
+import Identity from '@/components/identity/IdentityIndex.vue'
```
Comment (roiLeo) [inline components/migrate/landing/Index.vue:45]:
```suggestion
```

File: components/migrate/landing/Index.vue [hunk 3]
```diff
@@ -2,6 +2,48 @@
...
-    <MigrateLandingContent />
+    <div class="flex flex-col md:flex-row gap-4 justify-between">
+      <div>
+        <div
+          v-if="accountId"
+          class="flex flex-col md:flex-row gap-4 items-center">
+          <p class="mr-4">{{ $t('migrate.resultFor') }}</p>
+          <div class="flex">
+            <Avatar :value="accountId" :size="26" class="mr-2" />
+            <nuxt-link class="has-text-k-blue" :to="`/ksm/u/${accountId}`">
```
Comment (roiLeo) [inline components/migrate/landing/Index.vue:13]: `has-text-k-blue` any tailwind equivalent maybe `text-text-k-blue`

force link to `/ksm/u/`? no prefix?

**Review by roiLeo — COMMENTED** [review]
otherwise lgtm

**Review by roiLeo — APPROVED** [review]

**Comment by prury** [comment]
should be disabled only when i have nothing waiting for my action, right? 
on canary i have one waiting for my action but deployed shows none: 

https://github.com/kodadot/nft-gallery/assets/36627808/5da476e3-6cb2-49df-9c8d-be83000cee70

**Comment by preschian** [comment]
> should be disabled only when i have nothing waiting for my action, right?
> on canary i have one waiting for my action but deployed shows none:

checking, please give me your address

File: components/migrate/landing/Index.vue [hunk 4]
```diff
@@ -2,6 +2,49 @@
...
+    <div class="flex flex-col md:flex-row gap-4 justify-between">
+      <div>
+        <div
+          v-if="accountId"
+          class="flex flex-col md:flex-row gap-4 items-center">
+          <p class="mr-4">{{ $t('migrate.resultFor') }}</p>
+          <div class="flex">
+            <Avatar :value="accountId" :size="26" class="mr-2" />
+            <nuxt-link
+              class="!text-k-blue"
```
Comment (Jarsen136) [inline components/migrate/landing/Index.vue:14]:
```suggestion
              class="text-k-blue"
```

**Review by Jarsen136 — APPROVED** [review]

File: components/migrate/landing/Index.vue (hunk 4 above)
Comment (preschian) [reply components/migrate/landing/Index.vue:14]: Unfortunately, I need `!important` here because the style overridden with global style (`.dark-mode body a`)

image

Comment (Jarsen136) [reply components/migrate/landing/Index.vue:14]: Interesting, I thought this kind of class name should not be overridden.

**Comment by prury** [comment]
@preschian working now, thank you!
