### PR TITLE
I spent whole day trying to find an issue

### LINKED ISSUE #2058: When you go directly to the unique asset the app fails
### What happened?

When you visit directly ani Statemine art directly
[Anatomy of a cryptocanary](https://kodadot.xyz/statemine/gallery/0-2)
The app will fail

### Please reproduce in steps

1. Visit any statemine detail [Anatomy of a cryptocanary](https://kodadot.xyz/statemine/gallery/0-2)

### Expected Behavior

The app should show the art

### What browsers are you seeing the problem on?

_No response_

### Are you logged in?

_No response_

### At which address did you encounter bug?

_No response_

### Screenshots

Screenshot 2022-01-24 at 12 24 53

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by vikiival**
## What's the hack

We had vuexPersist in the old spa which was resolved incorrectly so it connected by default to Kusama but it showed that settings.apiUrl is statemine. [YOLO]

- Close #2058
- :zap: api will await for readyness
- :bug: forgot to remove vuex plugin from store
- :clown_face: Workaround for unique nfts without metadata

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Do a quick check before the merge.

### PR type

- [x] Bugfix
- [x] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #2058

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### CODE REVIEW

File: plugins/endpoint.ts [hunk 1]
```diff
@@ -0,0 +1,9 @@
+import '@polkadot/api-augment'
+import Connector from '@vue-polkadot/vue-api'
+
+export default ({ store }) => {
+  const endpoint = store.state.setting.apiUrl
```
Comment (kkukelka) [inline plugins/endpoint.ts:5]: so because vuex-persist plugin is being loaded beforehand we can always be assured that `setting.apiUrl` is set right?

**Review by kkukelka — APPROVED** [review]
GTG 👍

File: plugins/endpoint.ts (hunk 1 above)
Comment (vikiival) [reply plugins/endpoint.ts:5]: It was problem that vuex persist used older approach and that the session storage was rehydrated too late
