### PR TITLE
fix: Chart dropdown menu all white buttons

### LINKED ISSUE #5865: Chart dropdown menu all white buttons
image

https://user-images.githubusercontent.com/5887929/236443007-a34a458a-8b3f-4a6f-a948-0669b0fd96e2.mov

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5865
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### <samp>🤖 Generated by Copilot at 73ccf5e</samp>

Simplify active dropdown item styling in `NeoDropdown.scss`. Use inherited background color instead of inverse text color for better flexibility and consistency.

### <samp>🤖 Generated by Copilot at 73ccf5e</samp>

> _Sing, O Muse, of the skillful coder who refined_
> _the styling of the active dropdown item, and thus_
> _removed the inverse text color, a harsh contrast,_
> _and used the inherited background, a subtle grace._

### CODE REVIEW

**Comment by exezbcz** [comment]
it sometimes switch the text on hover to k-white, should be k-black 
image

**Comment by Jarsen136** [comment]
> it sometimes switch the text on hover to k-white, should be k-black image

✅  Fixed

File: libs/ui/src/components/NeoDropdown/NeoDropdownItem.vue [hunk 1]
```diff
@@ -3,6 +3,7 @@
     aria-role="listitem"
     :disabled="disabled"
     :class="{ 'is-active': active }"
+    :value="NaN"
```
Comment (vikiival) [inline libs/ui/src/components/NeoDropdown/NeoDropdownItem.vue:6]: Is this good?

**Review by preschian — COMMENTED** [review]
bug in this file I guess https://github.com/kodadot/nft-gallery/blob/main/components/chart/PriceChart.vue#LL19C47-L19C47

fixed with this change
```vue
@click.native="setTimeRange({ value: range.value, label: range.label })"
```

**Comment by Jarsen136** [comment]
> bug in this file I guess https://github.com/kodadot/nft-gallery/blob/main/components/chart/PriceChart.vue#LL19C47-L19C47
> 
> fixed with this change
> 
> ```
> @click.native="setTimeRange({ value: range.value, label: range.label })"
> ```

Thanks. It also fixes the bug.

**Review by preschian — APPROVED** [review]

**Review by roiLeo — APPROVED** [review]

**Comment by yangwao** [comment]
pay 20 usd
perfect

**Comment by yangwao** [comment]
pay 20 usd
perfect

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 26 USD/KSM ~ 0.769 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x82454ff16ab97f63cd0f5be45700565576e749da1e8279f7fb2bf4666fafee16](https://kusama.subscan.io/extrinsic/0x82454ff16ab97f63cd0f5be45700565576e749da1e8279f7fb2bf4666fafee16)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 26 USD/KSM ~ 0.769 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x36e180b05f7b91e4a9c6673ba31dfe08341dd9dce69be7269edd2f6f35df4c5e](https://kusama.subscan.io/extrinsic/0x36e180b05f7b91e4a9c6673ba31dfe08341dd9dce69be7269edd2f6f35df4c5e)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
whatever

**Comment by yangwao** [comment]
gh have fun 

image
