### PR TITLE
fix(useRedirectModal): Switch button items and activity at collection view opens new page and cart button on explorer too

### LINKED ISSUE #6817: Switch button items and activity at collection view opens new page and cart button on explorer too
From recent refactoring ?

- click on items or activity
- should keep in same window

image

ah cart button was affected too

image

https://canary.kodadot.xyz/ahk/collection/u-2024

### PR DESCRIPTION
**Pull request by hassnian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

The event listener inside `useRedirectModal` was affecting the entire website and not just the items inside the target node in this case the .content-markdown

- [x] Closes #6817
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

https://github.com/kodadot/nft-gallery/assets/44554284/8810b840-d0b7-4091-8225-c04b2af9ff11

### <samp>🤖 Generated by Copilot at 7afa09a</samp>

Improved the `useRedirectModal` function to use element references and added a link confirmation feature to the `Markdown` component.

### <samp>🤖 Generated by Copilot at 7afa09a</samp>

> _Sing, O Muse, of the skillful refactorer_
> _Who made the code more swift and error-free_
> _By using `ref` and `useRedirectModal`_
> _To handle links with grace and clarity_

### CODE REVIEW

File: components/redirect/useRedirectModal.ts [hunk 1]
```diff
@@ -6,6 +6,7 @@ import {
   isExternal,
 } from '@/utils/url'
 import { useEventListener } from '@vueuse/core'
+import { Ref } from 'vue/types'
```
Comment (preschian) [inline components/redirect/useRedirectModal.ts:9]:
```suggestion
import type { Ref } from 'vue/types'
```

**Review by preschian — APPROVED** [review]
otherwise lgtm

**Review by vikiival — APPROVED** [review]

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 4.5 USD/DOT ~ 11.111 $DOT
🧗 [16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD](https://polkadot.subscan.io/account/16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)
🔗 [0x6cd2a86a0cdfa93c7da308b651b08091749f600823443ced2cff9d81be007195](https://polkadot.subscan.io/extrinsic/0x6cd2a86a0cdfa93c7da308b651b08091749f600823443ced2cff9d81be007195)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
