### PR TITLE
fix: tooltip inside modal style

### LINKED ISSUE #6837: Transfer - Info tooltip missing? (NeoTooltip overflow bug on the modal)
this does nothing on send DOT dialog

image

### PR DESCRIPTION
**Pull request by floyd-li**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #6837
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

iShot_2023-08-21_09 52 08

iShot_2023-08-21_09 52 54

### <samp>🤖 Generated by Copilot at b18b253</samp>

Enhanced the user interface of the NFT transfer feature by using a custom tooltip component and fixing a styling bug. Modified the `NeoTooltip` component to accept a `rootClass` prop and updated the `TransferConfirmModal` component to use it.

### <samp>🤖 Generated by Copilot at b18b253</samp>

> _`NeoTooltip` shines_
> _Customizing its root class_
> _Winter bug is fixed_

### CODE REVIEW

File: components/transfer/TransferConfirmModal.vue [hunk 1]
```diff
@@ -265,3 +272,18 @@ const isExpandList = ref(false)
...
+}
+
+div:has(> .parent-z-index-auto.mobile) {
+  .o-tip__content {
+    transform: translateX(calc(-100vw + 2rem));
+  }
+  .o-tip__arrow {
+    transform: translateX(calc(50vw - 2rem));
+  }
+}
```
Comment (Jarsen136) [inline components/transfer/TransferConfirmModal.vue:288]: Can you remove this logic into NeoTooltip component? I think it would be reused in other places in the future.

**Review by Jarsen136 — COMMENTED** [review]
otherwise lgtm

**Comment by floyd-li** [comment]
> **Firefox:(was not happening on canary)**
> 
> image
> 
> tooltip showing faster tho

alright seem `:has` selector has compatibility issue with firefox. i'll try another way to solve it.
图片

**Review by vikiival — APPROVED** [review]

File: components/transfer/TransferConfirmModal.vue [hunk 2]
```diff
@@ -77,11 +77,12 @@
...
               </span>
-              <NeoIcon
-                icon="circle-info"
-                class="is-size-6"
-                pack="far"
-                :title="targetAddresses[0].address" />
+              <NeoTooltip
+                :label="targetAddresses[0].address"
+                append-to-body
+                :content-class="`transfer-tooltip ${isMobile ? 'mobile' : ''}`">
```
Comment (Jarsen136) [inline components/transfer/TransferConfirmModal.vue:83]:
```suggestion
                content-class="transfer-tooltip">
```

File: components/transfer/TransferConfirmModal.vue [hunk 3]
```diff
@@ -113,11 +114,17 @@
...
-                      icon="circle-info"
-                      class="is-size-6"
-                      pack="far"
-                      :title="address.address" />
+                    <NeoTooltip
+                      :label="address.address"
+                      append-to-body
+                      :content-class="`transfer-tooltip ${
+                        isMobile ? 'mobile' : ''
+                      }`">
```
Comment (Jarsen136) [inline components/transfer/TransferConfirmModal.vue:122]: Is the classname `mobile` used somewhere?
```suggestion
                      content-class="transfer-tooltip">
```

**Review by Jarsen136 — APPROVED** [review]

**Comment by yangwao** [comment]
> may i have any bonus for this pr🤔

if you want to take time, it's oke to fix it in this pr

**Comment by Jarsen136** [comment]
>> may i have any bonus for this pr🤔

> if you want to take time, it's oke to fix it in this pr

The compatibility issue should have already been fixed in this PR. 

image

**Review by preschian — APPROVED** [review]

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 4.42 USD/DOT ~ 6.787 $DOT
🧗 [13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A](https://polkadot.subscan.io/account/13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A)
🔗 [0x84da5f0cc87431e32257f23b03ae65a07157a3ac122b2c11095cd7c1d2fa21db](https://polkadot.subscan.io/extrinsic/0x84da5f0cc87431e32257f23b03ae65a07157a3ac122b2c11095cd7c1d2fa21db)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
