### PR TITLE
fix: fix error when estimate fee without connecting wallet

### LINKED ISSUE #2530: Estimation on minting costs doesn't work properly
Just done a blind test and seem the price estimator rounds up wrong?

Also minting without setting price missing estimator https://github.com/kodadot/nft-gallery/issues/2276#issuecomment-1060745382

image

### ref 
- https://github.com/kodadot/nft-gallery/issues/2514

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2530
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [x] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

File: utils/transactionExecutor.ts [hunk 1]
```diff
@@ -89,9 +91,10 @@ export const estimate = async (
   params: any[]
 ): Promise<string> => {
   const transfer = await callback(...params)
-  const address = typeof account === 'string' ? account : account.address
+  let address = typeof account === 'string' ? account : account.address
+  // if user have not connect wallet, we provide a mock address to estimate fee
+  address = address ? address : MOCK_ADDRESS
```
Comment (vikiival) [inline utils/transactionExecutor.ts:96]: Please use KODADOT_DAO as mock addr `@/utils/support.ts`

File: components/rmrk/Create/SimpleMint.vue [hunk 2]
```diff
@@ -276,12 +276,10 @@ export default class SimpleMint extends mixins(
...
-    const {
-      data: {
-        collectionEntities: { nodes },
-      },
-    } = data
-    this.collections = nodes
+    const collectionEntities = data?.data?.collectionEntities
+    if (collectionEntities) {
+      this.collections = collectionEntities.nodes
+    }
```
Comment (vikiival) [inline components/rmrk/Create/SimpleMint.vue:282]: Why?

File: utils/transactionExecutor.ts [hunk 3]
```diff
@@ -89,9 +91,10 @@ export const estimate = async (
   params: any[]
 ): Promise<string> => {
   const transfer = await callback(...params)
-  const address = typeof account === 'string' ? account : account.address
+  let address = typeof account === 'string' ? account : account.address
```
Comment (vikiival) [inline utils/transactionExecutor.ts:94]:
```suggestion
  let address = typeof account === 'string' ? account ?? KODADOT_DAO : account.address
```

**Review by vikiival — CHANGES_REQUESTED** [review]
~

File: components/rmrk/Create/SimpleMint.vue (hunk 2 above)
Comment (Jarsen136) [reply components/rmrk/Create/SimpleMint.vue:282]: Because at some point when the page loads, the errors below appear
image

**Comment by Jarsen136** [comment]
@vikiival  Thank a lot for your review. I have modified the code. ❤️

File: components/rmrk/Create/SimpleMint.vue (hunk 2 above)
Comment (Jarsen136) [reply components/rmrk/Create/SimpleMint.vue:282]: By the way, you can also see this error in the issue description.

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 124.24 USD/KSM ~ 0.805 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x28eaef6507ec5a6664c51914c49f24b0354915c57b60eed894f9a7276cda743d](https://kusama.subscan.io/extrinsic/0x28eaef6507ec5a6664c51914c49f24b0354915c57b60eed894f9a7276cda743d)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
