### PR TITLE
fix: Search tag when searching nothing

### LINKED ISSUE #5166: Search tag when searching nothing
image
when you input something into search field, then delete it and hit enter, the tag is added into breadcrumbs

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5166
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

File: components/shared/gallery/BreadcrumbsFilter.vue [hunk 1]
```diff
@@ -34,7 +34,8 @@ const breads = computed(() => {
 
   const activeFilters = Object.entries(query).filter(
     ([key, value]) =>
-      (key === 'search' && value !== undefined) || value === 'true'
+      (key === 'search' && value !== undefined && value !== '') ||
```
Comment (daiagi) [inline components/shared/gallery/BreadcrumbsFilter.vue:37]: How about this instead?
```suggestion
(key === 'search' && Boolean(value)) ||
```

**Review by daiagi — CHANGES_REQUESTED** [review]

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
pay 10 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $10 @ 34.86 USD/KSM ~ 0.287 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x588c7aca4eab5d48bca2859ccd1d4b20fad6da1ac29344a639cd820bc77edf9c](https://kusama.subscan.io/extrinsic/0x588c7aca4eab5d48bca2859ccd1d4b20fad6da1ac29344a639cd820bc77edf9c)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
