### PR TITLE
fix: Make fullscreen iframe to fit on code-check page

### LINKED ISSUE #10133: Make fullscreen iframe to fit on code-check page
looks like its working, just my full-screen mode is not really fullscreen:
Screenshot 2024-04-23 at 13 51 50

_Originally posted by @JustLuuuu in https://github.com/kodadot/nft-gallery/issues/10092#issuecomment-2072095910_
        
path: `/code-check`

code of art: https://github.com/kodadot/nft-gallery/files/14994217/Unfoldings.v1_9.zip

It should be a similar solution as we have on the gallery item page. ref: #9951  #10084

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

@prury pls test both `/gallery` and `/code-checker`

- [x] Closes #10133

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

https://github.com/kodadot/nft-gallery/assets/44554284/95ff37ad-278b-45dc-906d-795689964bef

### CODE REVIEW

**Review by preschian — APPROVED** [review]

File: libs/ui/src/components/MediaItem/type/IFrameMedia.vue [hunk 1]
```diff
@@ -17,11 +19,23 @@ import { useElementSize } from '@vueuse/core'
...
+  defineProps<{
+    src?: string
+    animationSrc?: string
+    alt?: string
+    iframeId?: string
+    sandbox?: string
+    allow?: string
+  }>(),
+  {
+    title: 'html-embed',
```
Comment (daiagi) [inline libs/ui/src/components/MediaItem/type/IFrameMedia.vue:33]: missing 'title' prop

i.e default exists  but not the actual props

**Review by daiagi — CHANGES_REQUESTED** [review]

File: libs/ui/src/components/MediaItem/type/IFrameMedia.vue (hunk 1 above)
Comment (hassnian) [reply libs/ui/src/components/MediaItem/type/IFrameMedia.vue:34]: thanks! , fixed

**Review by daiagi — APPROVED** [review]
