### PR TITLE
#645 Paste image from clipboard

### LINKED ISSUE #645: Paste image from clipboard
In simple mint and probably elsewhere doesn't work to paste image right away from the clipboard.

Would be great to upload from the clipboard.

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the KodaDot NFT gallery.
Let's do a quick check before the merge.
Your contribution will be an eternal part of the community codebase

### Before submitting this PR, please make sure:
- [x] Code builds clean without any errors or warnings
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I didn't break any original functionality

### Optional
- [ ] I've tested it on mobile and everything works

### PR type
- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new? (maybe part of changelog)
- closes #645 
Have added an event listener for paste, fetched the required info and sent it to the common function

### If issue contains bounty label ($,$$,$$$)
- Your KSM address: EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU

### Community participation
- [x] Are you at KodaDot Discord? If no, [let's join us - https://discord.gg/35hzy2dXXh](https://discord.gg/35hzy2dXXh)

### Screenshot
- [ ] Whenever your fix will change **something** on UI, a screenshot is more than welcome

### CODE REVIEW

File: src/components/rmrk/Create/DropUpload.vue [hunk 1]
```diff
@@ -35,6 +35,25 @@ export default class extends Vue {
...
+  }
+
+  public beforeDestroy() {
+    document.removeEventListener('paste', this.onPasteImage);
+  }
+
+  public onPasteImage(pasteEvent: ClipboardEvent) {
+    /* handling paste logic */
+    let item :DataTransferItem | any = pasteEvent?.clipboardData?.items[0];
+    if (item && item?.type.indexOf("image") === 0) {
```
Comment (roiLeo) [inline src/components/rmrk/Create/DropUpload.vue:50]: First expression 'item' in condition could be removed because it's already checked after with 'item?'

Comment (vikiival) [reply src/components/rmrk/Create/DropUpload.vue:50]: Good point

**Comment by yangwao** [comment]
@prachi00 can you take a peak at this so we can resolve it and merge it?:)

**Comment by prachi00** [comment]
@yangwao Have done all the mentioned changes

**Comment by yangwao** [comment]
Oh, I miss that we support that functionality. Others really don't know that exists.

I guess adding text Paste from Clipboard is crucial here, I'll merge it for now but looking for a new PR @prachi00 :)

image
