### PR TITLE
Fixed mobile pagination

### LINKED ISSUE #8539: Changing page using on mobile won't change button state
it also never goes back to first page once you change it to the second one

https://github.com/kodadot/nft-gallery/assets/36627808/447f43a4-335a-49b7-b5ed-ae5ca9d48431

### PR DESCRIPTION
**Pull request by shashkovdanil**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #8539 
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [x] I've tested it at </ksm/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer?target=16SpvdDgKNiQ3c53DxX7refnQcKUD3uRNim3Z1HBJLNGrtSP&usdamount=0)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 3c7fbc6</samp>

Fixed a pagination bug in the profile activity history tab and added a debugging statement. The bug affected the `History.vue` component and was caused by using the wrong prop binding.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 3c7fbc6</samp>

> _`currentPage` prop_
> _changed from `v-model` to `:value`_
> _pagination fixed_

### CODE REVIEW

File: components/profile/activityTab/History.vue [hunk 1]
```diff
@@ -119,6 +119,7 @@ onMounted(() => {
 })
 
 const updateCurrentPage = (value) => {
+  console.log(value)
```
Comment (roiLeo) [inline components/profile/activityTab/History.vue:122]:
```suggestion
```

File: components/profile/activityTab/History.vue [hunk 2]
```diff
@@ -10,7 +10,7 @@
 
     <div v-if="!desktop" class="is-flex is-justify-content-flex-end my-5">
       <Pagination
-        v-model="currentPage"
+        :value="currentPage"
```
Comment (roiLeo) [inline components/profile/activityTab/History.vue:13]: looks like root issue is in `Pagination` component which don't emit updated value

**Review by roiLeo — APPROVED** [review]

**Review by daiagi — APPROVED** [review]

**Comment by vikiival** [comment]
Thanks!
