### PR TITLE
Breaking new substrate API

### LINKED ISSUE #3312: JS error in basilisk collection creation interface: undefined variable
### What happened?

A bug happened!
When trying to create a collection on kodadot x basilisk beta, I got this error:
kodaerror

### Please reproduce in steps

Try to create a collection on the basilisk beta

### Expected Behavior

I've expected  the collection to be created but instead I got an error message

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

Yes

### At which address did you encounter bug?

beta.kodadot.xyz

### Screenshots

kodaerror

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #3364: Fetching for collection for KSM chain while on BSX
Seems singleton instance might cause some issues but seems this is not the case as don't have opened another window as it is the only one point to kodadot

Mind **set correct address 2** after connected to basilisk. 
Seems this is the culprit of many issues we have there.

image

### you can replicate it
- open incognito
- open console
- https://beta.kodadot.xyz/bsx/explore/?tab=GALLERY&page=1
- check logs

image

### PR DESCRIPTION
**Pull request by vikiival**
# It is possible that I broke something. 
If you find something please paste it here so I can fix it as soon as possible

## Known bugs:
- Identicon is making a ton of bugs: https://github.com/polkadot-js/ui/pull/668

## commits:
- :package: updated @polkadot packages
- :zap: api url minin that knows current websocket
- :coffin: :mute: legacyyy API code
- :zap: api constants use agnostic impl kodadot/packages#31
- :snake: BSX create collection is using new api
- :snake: BSX create token is using new api
- :memo: new usage of sub-api
- :memo: useApi
- :zap: useApiMixin
- :zap: upgraded metatxmixin to new api
- :snake: available action API::new
- :memo: useApi
- :zap: you wont believe that offers useApi]
- :dolphin: subscription returned to BSX gallery item
- :zap: onApiConnect from sub-api
- :construction: new apin in components/bsx/specific/DestroyCollection.vue
- :construction: new apin in components/rmrk/Create/Admin/AdminPanel.vue
- :construction: new apin in components/rmrk/Create/Admin/SendHandler.vue
- :construction: new apin in components/rmrk/Create/CreateCollection.vue
- :construction: new apin in components/rmrk/Create/CreateToken.vue
- :construction: new apin in components/rmrk/Create/CreativeMint.vue
- :construction: new apin in components/rmrk/Create/SimpleMint.vue
- :construction: new apin in components/rmrk/Gallery/Appreciation.vue
- :construction: new apin in components/rmrk/Gallery/AvailableActions.vue
- :construction: new apin in components/rmrk/Pack/PackSaver.vue
- :construction: new apin in components/rmrk/Profile/IdentityForm.vue
- :construction: new apin in components/shared/format/Identity.vue
- :construction: new apin in components/unique/Collection/Item/CollectionItem.vue
- :construction: new apin in components/unique/Collection/Item/TransferCollectionModal.vue
- :construction: new apin in components/unique/Create/CreateToken.vue
- :construction: new apin in components/unique/Gallery/Item/AvailableActions.vue
- :construction: new apin in components/unique/Gallery/Item/DangerModal.vue
- :construction: new apin in components/unique/Gallery/Item/GalleryItem.vue
- :construction: new apin in components/unique/apiConstants.ts
- :construction: new apin in pages/teleport.vue
- :construction: new apin in pages/transfer.vue
- :top: kodadot1-sub-api-0.1.0-alpha.1.tgz
- :broom: cleaned up configs
- :zap: chain mixin is using config instead of reading data from chain
- :bug: since 5b955bab7425d21c7c9dc7b6bf6399d5f6548514
- :zap: wallet modal uses chain mixin
- :zap: ss58 of the chain
- :zap: vuex plugin to change ss58 of the logged user
- :mute: chainPropListOf
- :package: sub-api-0.1.0-alpha.1

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [x] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #3364
- [x] PR closes #3312

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### CODE REVIEW

**Comment by yangwao** [comment]
- I went to https://deploy-preview-3500--koda-nuxt.netlify.app/bsx/gallery/515729876-6
- connected wallet 
- I see UNIT

image

**Comment by yangwao** [comment]
It seems needs to bump polkadot/util? 

image

**Comment by petersopko** [comment]
I achieved this couple of times in console by flipping between RMRK (kusama) / BSX, or more specifically following these steps:

- log in with bsx wallet
- switch to rmrk
- switch back to bsx
- go to explore
- switch to rmrk
- redirected back to home page, console looks like this

image

File: utils/shoppingActions.ts [hunk 1]
```diff
@@ -17,6 +17,7 @@ export type ShoppingActions = Interaction | BasiliskActions
 export const ShoppingActions = {
   ...Interaction,
   ...BasiliskActions,
+  DOWNLOAD: 'DOWNLOAD',
```
[the remark this answers is not in the document]
Comment (vikiival) [reply utils/shoppingActions.ts:20]: Why it was removed ? :D

[the remark this answers is not in the document]
Comment (Jarsen136) [reply utils/shoppingActions.ts:20]: Because it can not stay at AvailableAction list according to the above issue : )

**Comment by vikiival** [comment]
31745615-897B-4E84-BDF9-46F8699E33D1

**Comment by vikiival** [comment]
Gonna resolve the bugs tomorrow

File: utils/shoppingActions.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (vikiival) [reply utils/shoppingActions.ts:20]: The issue talks about CSS for the button not about download functionality

but whatever.

**Comment by vikiival** [comment]
> It seems needs to bump polkadot/util?
> 
> image

https://github.com/polkadot-js/extension/issues/1113

**Comment by vikiival** [comment]
> I achieved this couple of times in console by flipping between RMRK (kusama) / BSX, or more specifically following these steps:


Thanks for the good eye! It was fixed in kodadot/packages@986447e4ac881c8d243510794c2f3c3749f65675

**Comment by vikiival** [comment]
@petersopko @Jarsen136 all issues should be fixed now. 

If you will be able to crack it again I would be super happy

**Comment by yangwao** [comment]
Let's make a release https://github.com/kodadot/nft-gallery/releases/tag/untagged-08c2fed23fc63c6921d9 and then we can merge this 👌

File: components/bsx/Gallery/Item/GalleryItem.vue [hunk 2]
```diff
@@ -407,24 +409,24 @@ export default class GalleryItem extends mixins(
...
+  //       collection: (this.nft.collection as any).name,
+  //       date: new Date(),
+  //       description: this.meta.description,
+  //       author: this.nft.currentOwner,
+  //       price: this.nft.price,
+  //       mimeType: this.mimeType,
+  //       prefix: this.urlPrefix,
+  //     })
+  //   }
+  // }
```
Comment (Jarsen136) [inline components/bsx/Gallery/Item/GalleryItem.vue:429]: Why we delete this part?
IMO it's being used in somewhere at BSX currently.

File: FIRST_TIME.md [hunk 3]
```diff
@@ -211,13 +212,13 @@ Then we can use it like this:
 <script lang="ts">
   import { Component, mixins } from 'nuxt-property-decorator'
   import MetaTransactionMixin from '@/utils/mixins/metaMixin'
-  // import AuthMixin from '~/utils/mixins/authMixin' // get currently logged in account
-
-  import Connector from '@kodadot1/sub-api'
+  import UseApiMixin from '@/utils/mixins/useApiMixin'
+  // import AuthMixin from '@/utils/mixins/authMixin' // get currently logged in account
```
Comment (Jarsen136) [inline FIRST_TIME.md:216]: I prefer to remove some unused code. 👀

**Review by Jarsen136 — COMMENTED** [review]
A few comments

File: components/bsx/Gallery/Item/GalleryItem.vue (hunk 2 above)
Comment (vikiival) [reply components/bsx/Gallery/Item/GalleryItem.vue:429]: Because it is crashing on the BSX :)

Comment (vikiival) [reply components/bsx/Gallery/Item/GalleryItem.vue:429]: 5b955bab7425d21c7c9dc7b6bf6399d5f6548514

Comment (Jarsen136) [reply components/bsx/Gallery/Item/GalleryItem.vue:429]: This part is related to the History component.

image

Comment (Jarsen136) [reply components/bsx/Gallery/Item/GalleryItem.vue:429]: > Because it is crashing on the BSX :)

 Aright, maybe we could create another issue to trace it : )

**Review by Jarsen136 — APPROVED** [review]
LGTM

**Comment by petersopko** [comment]
Tried flipping between rmrk / bsx again, landed at bsx. My balance seems to be zero everywhere I look (even after refreshing at BSX couple times. No visible issue in the console for me:
image


links to check: 
- https://deploy-preview-3500--koda-nuxt.netlify.app/bsx/create
- https://deploy-preview-3500--koda-nuxt.netlify.app/transfer

**Comment by vikiival** [comment]
> Tried flipping between rmrk / bsx again, landed at bsx. My balance seems to be zero everywhere I look

d57f2c4a6de364f2812c9ccf934744086f63e0b5

**Comment by petersopko** [comment]
classic RMRK mint repeatedly fails
image

**Comment by yangwao** [comment]
Would be nice to push this to `main` 👀

**Comment by vikiival** [comment]
I think It would be nice to have a last check and merge cc @petersopko

**Review by petersopko — APPROVED** [review]
I've minted at both BSX and RMRK, except the indexer problem we know about and @vikiival is working on, there's no visible problem for me. WFM 🚀

**Comment by Jarsen136** [comment]
tested on https://deploy-preview-3500--koda-nuxt.netlify.app/transfer

I could see an incorrect balance after I switch from BSX to RMRK
image

After I reload the page, it works well as usual.
image

**Comment by vikiival** [comment]
@Jarsen136 fixed in [19b1984](https://github.com/kodadot/nft-gallery/pull/3500/commits/19b1984b0fb14c3e3e1ff778465f8f3243914820)

**Comment by Jarsen136** [comment]
> @Jarsen136 fixed in [19b1984](https://github.com/kodadot/nft-gallery/pull/3500/commits/19b1984b0fb14c3e3e1ff778465f8f3243914820)

Seems that I could still reproduce it and there is no any error related in the console.

Kapture 2022-07-27 at 18 18 05

**Comment by vikiival** [comment]
Let's open an issue for that and merge this

**Review by Jarsen136 — APPROVED** [review]
