### PR TITLE
fix: Explore gallery cards have unequeal height

### LINKED ISSUE #5077: Explore gallery cards have unequeal height
### What happened?

Depending on screen width, some cards have unequal heights
seems to be due to test wrapping

image
image

### Please reproduce in steps

go to https://beta.kodadot.xyz/bsx/explore/items?page=1&listed=true
* make screen width = 1100px
* make sure filter side bar is open
* filter by "Buy Now"

### Expected Behavior

All cards to have equal heights

### What browsers are you seeing the problem on?

Desktop Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

None

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

Basilisk

### Screenshots

image

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer/?target=EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5077
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

File: libs/ui/src/components/NeoNftCard/NeoNftCard.vue [hunk 1]
```diff
@@ -17,26 +17,28 @@
...
+                  (nft.collection.name || nft.collection.id)
+                "
+                :title="nft.collectionName || nft.collection.name"
+                :to="`/${prefix}/collection/${nft.collection.id}`"
+                class="is-size-7 nft-info-collection-name">
+                {{ nft.collection.name || '--' }}
+              </nuxt-link>
+            </template>
+          </CollectionDetailsPopover>
+        </span>
```
Comment (roiLeo) [inline libs/ui/src/components/NeoNftCard/NeoNftCard.vue:37]:
```suggestion
        <CollectionDetailsPopover
          :show-delay="collectionPopoverShowDelay"
          :nft="nft"
          class="is-ellipsis"
        >
          <template #trigger>
            <nuxt-link
              v-if="
                variant !== 'minimal' &&
                (nft.collection.name || nft.collection.id)
              "
              :title="nft.collectionName || nft.collection.name"
              :to="`/${prefix}/collection/${nft.collection.id}`"
              class="is-size-7 nft-info-collection-name">
              {{ nft.collection.name || '--' }}
            </nuxt-link>
          </template>
        </CollectionDetailsPopover>
```
no need to wrap it with `<span>`

**Comment by yangwao** [comment]
pay 20 usd
