### PR TITLE
🔧 massmint missing names & numbers

### LINKED ISSUE #11320: Display what nft is incomplete - Massmint
> a couple of weeks ago patricia was having issues mass-minting a large amount of NFTs
> 
> apparently she had enough funds on-chain but she could not mint (transaction would fail), after checking her address she did not have funds on `AHP` after transferring funds to her wallet everything worked.
> 
> that's how I found that the **massmint does not check the user balance at all**
> 
> it should
> 
> 1. take minting cost (**itemDeposit** and a **base transaction fee**) into consideration
> 2. ideally support auto-teleport
> 
> 
> _Originally posted by @hassnian in [#11188 (comment)](https://github.com/kodadot/nft-gallery/pull/11188#issuecomment-2502633458)_

good comment to show which nft is incomplete, low hanging fruit imo

https://github.com/kodadot/nft-gallery/issues/11189

image
as we have column for "#" 

lets use the number of the nft and how it in the brackets after the copy "incomplete" 

it will look like this: incomplete: 1 NFT (#4)

### PR DESCRIPTION
**Pull request by roiLeo**
- closes #11320 i guess
- not tested

### CODE REVIEW

File: components/massmint/modals/MissingInfoModal.vue [hunk 1]
```diff
@@ -35,7 +35,7 @@
             }}
           </div>
           <div
-            v-if="numMissingNames"
+            v-if="numMissingPrices"
```
Comment (Jarsen136) [inline components/massmint/modals/MissingInfoModal.vue:38]: `numMissingPrices.length`

File: components/massmint/modals/MissingInfoModal.vue [hunk 2]
```diff
@@ -14,7 +14,7 @@
           <div>{{ $t('massmint.required') }}</div>
 
           <div class="pl-3">
-            • {{ $t('massmint.incompleteNfts', { count: numMissingNames }) }}
+            • {{ $t('massmint.incompleteNfts', { count: missingNames.length }) }} ({{ missingNames.map(nft => nft.id).join(', ') }})
```
Comment (Jarsen136) [inline components/massmint/modals/MissingInfoModal.vue:17]: It should looks like `#${nft.id}` according to https://github.com/kodadot/nft-gallery/issues/11320#issue-2765028112

**Review by Jarsen136 — COMMENTED** [review]
otherwise lgtm

File: components/massmint/modals/MissingInfoModal.vue (hunk 1 above)
Comment (roiLeo) [reply components/massmint/modals/MissingInfoModal.vue:38]: ? `numMissingPrices` is not an array

File: components/massmint/modals/MissingInfoModal.vue (hunk 2 above)
Comment (roiLeo) [reply components/massmint/modals/MissingInfoModal.vue]: yeet https://github.com/kodadot/nft-gallery/pull/11340/commits/ed158ce7a25e662366fff75bd1aefa34bf8ee3a7

File: components/massmint/modals/MissingInfoModal.vue (hunk 1 above)
Comment (Jarsen136) [reply components/massmint/modals/MissingInfoModal.vue:38]: My bad. Ignore it : )

**Review by vikiival — APPROVED** [review]
