### PR TITLE
fix: Drop Calendar section is missing & mobile view a bit off 

### LINKED ISSUE #10791: Mobile view: callendar - bit off
Open Drops, Calendar on your mobile:

image

The text if out the circle

### LINKED ISSUE #10794: Drop calendar Section Missing
### What happened?

luu added some drop calendars they appear on prod but not on canary

CleanShot 2024-08-12 at 11 36 54@2x

### Please reproduce in steps

-

### Expected Behavior

-

### What browsers are you seeing the problem on?

_No response_

### At which address did you encounter bug?

_No response_

### Are you logged in?

None

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

-

### Relevant log output

_No response_

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #10794
- [x] Closes #10791

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI;

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]

File: components/drops/calendar/DropsCalendar.vue [hunk 1]
```diff
@@ -15,6 +15,7 @@
         <div class="mb-6 flex items-center">
           <NeoButton
             variant="secondary-rounded"
+            root-class="!flex-shrink-0"
```
Comment (hassnian) [inline components/drops/calendar/DropsCalendar.vue:18]: was thinking if we should add this to the button css file itself

Comment (preschian) [reply components/drops/calendar/DropsCalendar.vue:18]: no need, I think

**Review by preschian — APPROVED** [review]
