### PR TITLE
fix: Followup Transfer Redesign

### LINKED ISSUE #6529: Followup: Transfer Redesign
### What happened?

https://github.com/kodadot/nft-gallery/assets/36627808/acebd3c6-3c4c-4bae-bc3b-e81773a709d5

problems found in the video: 
- page "jumping" when typing value
- Total of $xxx dollars always showing no matter what you type on ksm transfer page, prob because this browser address is not getting updated: image
- dollar calculation seems wrong
- i think the total should appear as: ($0.00) 0.00 KSM when you chose KSM as unit and (0.00 KSM) $0.00 when you choose USD
- Continue button deactivates if i type a value higher than my balance, but won't come back after i remove or type a value that i have balance to transfer

wdyt @exezbcz 

### Please reproduce in steps

https://deploy-preview-6486--koda-canary.netlify.app/ksm/transfer?redesign=true
https://deploy-preview-6486--koda-canary.netlify.app/dot/transfer?redesign=true

### Expected Behavior

.

### What browsers are you seeing the problem on?

_No response_

### At which address did you encounter bug?

_No response_

### Are you logged in?

None

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

^

### Relevant log output

_No response_

### Payment link for reward

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #6529
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [ ] My fix has changed UI

### <samp>🤖 Generated by Copilot at 8dcdccd</samp>

This pull request fixes a bug in the `Transfer.vue` component and enables scrolling to the top of the page on the transfer route. These changes improve the user experience of the NFT transfer feature.

### <samp>🤖 Generated by Copilot at 8dcdccd</samp>

> _`Transfer.vue` fixed_
> _NFTs can change owners now_
> _Autumn of tokens_

### CODE REVIEW

**Comment by prury** [comment]
continue button never gets active here for me, tried both firefox and chrome

File: components/transfer/Transfer.vue [hunk 1]
```diff
@@ -349,6 +349,9 @@ const onAmountFieldChange = (target: TargetAddress) => {
       )
     : 0
 
+  // update targetAddresses
+  targetAddresses.value = targetAddresses.value.slice(0)
```
Comment (daiagi) [inline components/transfer/Transfer.vue:353]: How about `[...targetAddresses.value]`

**Review by daiagi — APPROVED** [review]

File: components/transfer/Transfer.vue (hunk 1 above)
Comment (yangwao) [reply components/transfer/Transfer.vue:353]: good point 🫠

Comment (Jarsen136) [reply components/transfer/Transfer.vue]: Sure.  Thank you.

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 5.03 USD/DOT ~ 5.964 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x95478eb714b72ec5f588e0aedfe14906eea72b5ce5dfbf163c3e90ca2d6ab395](https://polkadot.subscan.io/extrinsic/0x95478eb714b72ec5f588e0aedfe14906eea72b5ce5dfbf163c3e90ca2d6ab395)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
