### PR TITLE
Show available balance at NFTs for BUY

### LINKED ISSUE #2282: Show available balance at NFTs for BUY
When people are eyeballing for NFTs, show them the available balance next to the name 
This would avoid some future failed transactions and UX Foppa

Optionally disable BUY when not enough balance but keep it there, tell the user why is disabled.
Don't forget to add it to translations
Subscribe pooling for balance to see and avoid edge case if someone refuelled their wallet meanwhile.
Please test all edge cases I was might not think of 

Optionally make it to hide in user preferences

image

test case 
https://kodadot.xyz/rmrk/gallery/11163449-6ec662611f161fd10a-DDWORLD-DOODLE_ANIMATRONIC_CARACAL-0000000000000034

### PR DESCRIPTION
**Pull request by chandradot99**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #2282 
- [x] Added balance info and disabled buy button in case of insufficient balance.

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=CeBWgisygADqqxGk7ju8aMNEKz1K2WkxMKC3G8HsMnm119n)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

File: components/rmrk/Gallery/AvailableActions.vue [hunk 1]
```diff
@@ -394,3 +411,11 @@ export default class AvailableActions extends mixins(
   }
 }
 </style>
+
+<style lang="scss">
+.buttons {
+  .b-tooltip {
+    width: 100%;
+  }
+}
```
Comment (roiLeo) [inline components/rmrk/Gallery/AvailableActions.vue:420]: this will be global

File: components/rmrk/Gallery/GalleryItem.vue [hunk 2]
```diff
@@ -197,6 +198,8 @@ export default class GalleryItem extends mixins(PrefixMixin) {
   public message = ''
   public priceChartData: [Date, number][][] = []
   public showNavigation = false
+  public userBalance
+  public isBuyDisabled = true
```
Comment (roiLeo) [inline components/rmrk/Gallery/GalleryItem.vue:202]: - missing types
- I would prefer `hasBuyDisabled`

File: components/shared/Auth.vue [hunk 3]
```diff
@@ -30,29 +33,45 @@ const components = {
 export default class Auth extends Vue {
   @Prop({ default: 24 }) public size!: number
   private balance = ''
+  private interval
```
Comment (roiLeo) [inline components/shared/Auth.vue:36]: - missing type

File: components/shared/Auth.vue [hunk 4]
```diff
@@ -30,29 +33,45 @@ const components = {
...
+  }
+
+  private async pollBalance(account) {
+    if (this.interval) {
+      clearInterval(this.interval)
+    }
+
+    this.interval = setInterval(() => {
+      this.calculateBalance(account)
+    }, 5000)
```
Comment (roiLeo) [inline components/shared/Auth.vue:70]: Why would you need this interval?

Comment (yangwao) [reply components/shared/Auth.vue:70]: probably if has on one tab opened and meanwhile balanced has changed on the second tab? Hence our app doesn't communicate between tabs :|

File: components/rmrk/Gallery/GalleryItem.vue (hunk 2 above)
Comment (chandradot99) [reply components/rmrk/Gallery/GalleryItem.vue]: @roiLeo once I add types, eslint gives this error

`Type boolean trivially inferred from a boolean literal, remove type annotation.eslint[@typescript-eslint/no-inferrable-types](https://typescript-eslint.io/rules/no-inferrable-types)`

File: components/rmrk/Gallery/AvailableActions.vue (hunk 1 above)
Comment (chandradot99) [reply components/rmrk/Gallery/AvailableActions.vue]: @roiLeo done

**Comment by roiLeo** [comment]
IMO, in the futur, it would be better to have userBalance accessible throught Vuex store

File: styles/global.scss [hunk 5]
```diff
@@ -208,6 +208,12 @@ button.button.is-bordered {
   }
 }
 
+.buttons {
+  .b-tooltip {
+    width: 100%;
+  }
+}
```
Comment (roiLeo) [inline styles/global.scss:215]: Why would you want to make it global? I mean that if any other component that have tooltip on buttons will now have a width of 100% and it could break something somewhere.
What did you try to fix here? Couldn't it be scoped to component?

**Review by roiLeo — COMMENTED** [review]
Is it normal that it show my staked ksm in balance? I thought they shouldn't be available

File: styles/global.scss (hunk 5 above)
Comment (chandradot99) [reply styles/global.scss:215]: @roiLeo now I understood your point, I thought you want this to be global, my bad. I will add this to component scope.

**Comment by yangwao** [comment]
> IMO, in the futur, it would be better to have userBalance accessible throught Vuex store

yes, @chandradot99 let's do it within this issue, I'll raise bounty :)

**Comment by yangwao** [comment]
@chandradot99 any eta to close on this? :)

**Comment by chandradot99** [comment]
> @chandradot99 any eta to close on this? :)

yes @yangwao I will try to close it today.

File: components/Navbar.vue [hunk 6]
```diff
@@ -72,9 +75,49 @@ import PrefixMixin from '~/utils/mixins/prefixMixin'
...
+    if (!this.account || !api) {
+      return
+    }
+
+    try {
+      const result = await api.query.system.account(account)
+      const balance = result.data.free.toString()
+      this.$store.dispatch('setBalance', balance)
+
+      // Here we subscribe to any balance changes and update the on-screen value
```
Comment (chandradot99) [inline components/Navbar.vue:105]: @yangwao got to know that we can listen for balance changes from here

https://polkadot.js.org/docs/api/examples/promise/listen-to-balance-change

**Review by roiLeo — CHANGES_REQUESTED** [review]
I would move `loadBalance` outside navbar component, you could put it in `store/identity.ts` and try to fetch balance when we fetch identity or create a new action to fetchBalance.
It still show my locked balance, maybe [this](https://github.com/polkadot-js/apps/blob/master/packages/page-accounts/src/Accounts/Account.tsx) & [this](https://github.com/polkadot-js/apps/blob/master/packages/react-hooks/src/useBalancesAll.ts) from polkadot.js app could help

**Comment by chandradot99** [comment]
> I would move `loadBalance` outside navbar component, you could put it in `store/identity.ts` and try to fetch balance when we fetch identity or create a new action to fetchBalance. It still show my locked balance, maybe [this](https://github.com/polkadot-js/apps/blob/master/packages/page-accounts/src/Accounts/Account.tsx) & [this](https://github.com/polkadot-js/apps/blob/master/packages/react-hooks/src/useBalancesAll.ts) from polkadot.js app could help

@roiLeo when the user is already logged in and if we reload the page, then we have to fetch the user balance and I think since we don't have any root component, so we have to make a call to fetch balance inside the navbar component, since this is the only component which renders on initial app load. I also tried to move the fetchBalance api call in `store/identity.ts` but for the first time api instance is undefined.

**Comment by vikiival** [comment]
lala 

Plugin is your friend
https://nuxtjs.org/docs/directory-structure/plugins/

**Comment by chandradot99** [comment]
> > since this is the only component which renders on initial app load.
> 
> [Plugin is your friend](https://nuxtjs.org/docs/directory-structure/plugins/)
> 
> > I also tried to move the fetchBalance api call in store/identity.ts but for the first time api instance is undefined.
> 
> Api is a singleton instance, I recommend to wait for `'connect'` event
> 
> ```ts
> const { getInstance: Api } = Connector
> 
> Api().once('connect', api => console.log('api defined here'))
> ```
> 
> But yeah also you need to reflect the fact that logged user can be changed

Yes, I was also thinking to add it as a plugin.

**Comment by chandradot99** [comment]
@roiLeo @yangwao I have done the required changes.

**Comment by yangwao** [comment]
@chandradot99 resolve conflicts and less push it :)

File: components/shared/Auth.vue (hunk 4 above)
Comment (roiLeo) [reply components/shared/Auth.vue]: outdated

**Comment by chandradot99** [comment]
@yangwao all conflicts resolved and pushed.

File: nuxt.config.js [hunk 7]
```diff
@@ -98,7 +98,7 @@ export default {
     { src: '~/plugins/polkadot', mode: 'client' },
     { src: '~/plugins/endpoint', mode: 'client' },
     { src: '~/plugins/seoMetaGenerator', mode: 'client' },
-    { src: '~/plugins/keyboardEvents', mode: 'client' },
+    { src: '~/plugins/appLoad', mode: 'client' },
```
Comment (vikiival) [inline nuxt.config.js:101]: typo?

File: plugins/appLoad.ts [hunk 8]
```diff
@@ -86,5 +86,12 @@ const listenGlobalKeyboardEvents = (app, store) => {
 }
 
 export default ({ app, store }): void => {
+  // Bind Global Keyboard Events
   listenGlobalKeyboardEvents(app, store)
+
+  // Fetch User balance
+  const account = store.getters.getAuthAddress
```
Comment (vikiival) [inline plugins/appLoad.ts:93]: ???? 
Please use separated file

File: store/identity.ts [hunk 9]
```diff
@@ -62,8 +68,22 @@ export const actions = {
       console.error('[FETCH IDENTITY] Unable to get identity', e)
     }
   },
-  setAuth({ commit }: any, authRequest: Auth): void {
+  async fetchBalance({ dispatch }: any, address: string) {
```
Comment (vikiival) [inline store/identity.ts:71]: dispatch has a type

File: nuxt.config.js (hunk 7 above)
Comment (chandradot99) [reply nuxt.config.js:101]: No @vikiival I have renamed the file name to `appLoad`, so that we can write code which needs to be run on app first load, like binding keyboard events and fetching user balance.

**Review by vikiival — CHANGES_REQUESTED** [review]
Few things worth mention.


Also you have an edge case:
What if you buy an NFT ? You should refetch balance

File: plugins/appLoad.ts (hunk 8 above)
Comment (chandradot99) [reply plugins/appLoad.ts:93]: ok so what we can do is polling after every 5 to 10 seconds because user can add balance to wallet and this needs to be reflected on our app also.

File: nuxt.config.js (hunk 7 above)
Comment (vikiival) [reply nuxt.config.js:101]: Yeah, use separated file for that

File: plugins/appLoad.ts (hunk 8 above)
Comment (chandradot99) [reply plugins/appLoad.ts:93]:
```
api.derive.balances.all(accountId, ({ availableBalance }) => { // set balance on change })
```

@vikiival I think this should work, right ??

**Comment by vikiival** [comment]
Hello, 
I wrote you a component which should be very easy to use for you

**Comment by chandradot99** [comment]
> Hello, I wrote you a component which should be very easy to use for you

ok @vikiival

**Comment by yangwao** [comment]
#2373 is merged tho! Let's close this one :D

**Comment by chandradot99** [comment]
Yes @yangwao working on the changes

File: store/subscription.ts [hunk 10]
```diff
@@ -0,0 +1,39 @@
+import Vue from 'vue'
```
Comment (chandradot99) [inline store/subscription.ts:1]: @roiLeo @vikiival I have add subscription in Vuex store, so this will handle all of the subscriptions. `singleSubscribeMixin` will not be useful in our case since we need to subscribe in `userBalance.ts` plugin and I think the mentioned mixin will not be helpful in that case. I think this is the best way to handle subscriptions.

**Comment by yangwao** [comment]
nice seems working for me.
 
image

File: plugins/appLoad.ts (hunk 8 above)
Comment (vikiival) [reply plugins/appLoad.ts]: Yup, but you have to unsubscribe

File: store/subscription.ts (hunk 10 above)
Comment (vikiival) [reply store/subscription.ts:1]: And what about unsubscribe?

File: store/subscription.ts [hunk 11]
```diff
@@ -0,0 +1,39 @@
...
+// Disabling namespace to match with the original repo
+export const namespaced = false
+
+export const state = () => defaultState
+
+export const mutations = {
+  addSubscription(state: SubscriptionStruct, { key, sub }): void {
+    // unsubscribe previous subsription
+    const oldSub = state[key]
+    oldSub()
```
Comment (chandradot99) [inline store/subscription.ts:22]: @vikiival we are unsubscribing before any new subscription here.

Comment (vikiival) [reply store/subscription.ts:22]: Oh ok

File: plugins/userBalance.ts [hunk 12]
```diff
@@ -0,0 +1,9 @@
+export default ({ store }): void => {
+  const account = store.getters.getAuthAddress
+  if (account) {
+    store.dispatch('fetchBalance', account)
```
Comment (vikiival) [inline plugins/userBalance.ts:4]: Why you need both fetch and subscribe?

Comment (chandradot99) [reply plugins/userBalance.ts:4]: @vikiival I think for the first time subscribe will not return balance, it will only work in case of any balance changes, but let me confirm once more.

**Review by vikiival — COMMENTED** [review]
Just a few points: 
- [ ] you make both fetch and subscription which is a bit repetitive (would try it without fetch)
- [ ] Why do you have a separate store for a subscription? (I would just store it as constant in auth)
- [ ] Optional: Still can't help myself but I would make a separated component from the buy button

Otherwise: a really good job, you have figured a lot 👍

**Comment by chandradot99** [comment]
> 

@vikiival 
1. yes there is no need for both fetch and subscription, I just verified now only subscription will also work.
2. First I also thought to make it as constant in auth, but I think it will be good to create separate store, because in future we can have multiple subscriptions and it will be easy to maintain.

**Comment by vikiival** [comment]
> we can have multiple subscriptions

it's called subscribe mixin.
for now I would keep the implementation as simple as possible

**Comment by chandradot99** [comment]
> > we can have multiple subscriptions
> 
> it's called subscribe mixin. for now I would keep the implementation as simple as possible

@vikiival I have done the suggested changes.

**Comment by chandradot99** [comment]
@yangwao let's merge this PR if everything looks good.

**Comment by yangwao** [comment]
> @yangwao let's merge this PR if everything looks good.

I've merged main and let's wait for @vikiival review to merge it as noticed there was lots of changes so want to be sure :)

File: plugins/userBalance.ts [hunk 13]
```diff
@@ -0,0 +1,7 @@
+export default ({ store }): void => {
+  const account = store.getters.getAuthAddress
+  if (account) {
+    // Subscribe to balance changes
+    store.dispatch('fetchBalance', account)
```
Comment (vikiival) [inline plugins/userBalance.ts:5]: // Subscribe to balance changes
and then function dispatch fetch?

😕 viki

Comment (chandradot99) [reply plugins/userBalance.ts:5]: yes @vikiival looks like wrong comment message, it should be `Fetch and subscribe to balance changes`.

**Comment by yangwao** [comment]
works, let's merge it 😇 

pay 200 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $200 @ 163.18 USD/KSM ~ 1.226 $KSM
🧗 [CeBWgisygADqqxGk7ju8aMNEKz1K2WkxMKC3G8HsMnm119n](https://kusama.subscan.io/account/CeBWgisygADqqxGk7ju8aMNEKz1K2WkxMKC3G8HsMnm119n)
🔗 [0xa60c8eda47807651d47079645ac2a23241e38ec6f5f434b229eebbcdd1fa4c10](https://kusama.subscan.io/extrinsic/0xa60c8eda47807651d47079645ac2a23241e38ec6f5f434b229eebbcdd1fa4c10)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
