### PR TITLE
fix: Search Hard to read (adjust colours)

### LINKED ISSUE #8283: Search: Hard to read (adjust colours)
Please adjust colors in the collection search. Once you search for something and click enter it appears almost invisible:

Screenshot 2023-11-28 at 12 51 58

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Needs Design check

  - @exezbcz please review

  ## Context

  - [x] Closes #8283

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image

image

  ## Copilot Summary
  
### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 07c697a</samp>

Improved color styling of `.tag` component using ktheme mixin. This change affects the `NeoTag.vue` file and enhances the UI design.

  
### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 07c697a</samp>

> _Oh we're the coders of the `.tag` component_
> _And we like to keep our colors nice and bright_
> _We use the ktheme mixin for our styling_
> _So we can make our UI more accessible and tight_

### CODE REVIEW

File: components/shared/gallery/NeoTag.vue [hunk 1]
```diff
@@ -47,12 +47,14 @@ const onClose = () => {
   border-radius: 1rem !important;
   background: transparent;
   font-size: 1rem !important;
+  @include ktheme() {
+    color: theme('text-color');
+  }
```
Comment (preschian) [inline components/shared/gallery/NeoTag.vue:52]:
```suggestion
  @apply text-text-color;
```

**Review by preschian — APPROVED** [review]

File: components/shared/gallery/NeoTag.vue (hunk 1 above)
Comment (Jarsen136) [reply components/shared/gallery/NeoTag.vue]: Updated
