### PR TITLE
Error on infinity scroll at collections

### LINKED ISSUE #2860: Error on infinity scroll at collections
When I land at https://beta.kodadot.xyz/rmrk/explore/?page=160

Seems the error is timeouts SubSquid and can't browse previous and next 

Happens only if I scroll too fast. 

Oh, sometimes when I click the random button doesn't work at all going upper or down.
Backward scrolling fetches almost all time but next forward most likely doesn't work :)

image

Sometimes doesn't scroll at all :| 

image

### PR DESCRIPTION
**Pull request by Jarsen136**
fetch error while fast scroll

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2860 
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by Jarsen136** [comment]
The way to reproduce is to click the random button, then quickly scroll from top to bottom : ) 

Already fixed it and WFM

**Review by roiLeo — COMMENTED** [review]
can we remove `NavigationDuplicated: Avoided redundant navigation` warning when scrolling?

**Comment by Jarsen136** [comment]
> can we remove NavigationDuplicated: Avoided redundant navigation warning when scrolling?

Yup, I have removed it.

File: utils/mixins/infiniteScrollMixin.ts [hunk 1]
```diff
@@ -71,33 +71,31 @@ export default class InfiniteScrollMixin extends Vue {
...
-    this.$consola.warn(
-      'fetchPageData need to be extended',
-      page,
-      loadDirection,
-      cb
-    )
+  protected async fetchPageData(page, loadDirection): Promise<boolean> {
+    this.$consola.warn('fetchPageData need to be extended', page, loadDirection)
+    return true
   }
```
Comment (roiLeo) [inline utils/mixins/infiniteScrollMixin.ts:100]: why async? this will always return true

File: components/rmrk/Collection/List/CollectionList.vue [hunk 2]
```diff
@@ -180,12 +180,11 @@ export default class CollectionList extends mixins(
     this.fetchPageData(this.startPage)
   }
 
-  public async fetchPageData(
+  protected async fetchPageData(
```
Comment (roiLeo) [inline components/rmrk/Collection/List/CollectionList.vue:183]: have you try to make it work with smartQuery? something like this
```ts
  protected fetchPageData(
    page: number,
    loadDirection = 'down'
  ): any {
    this.$apollo.addSmartQuery('collections', {
      query: collectionListWithSearch,
      loadingKey: 'isFetchingData',
      client: this.urlPrefix === 'rmrk' ? 'subsquid' : this.urlPrefix,
      manual: true,
      variables: {
        orderBy: this.searchQuery.sortBy,
        search: this.buildSearchParam(),
        listed: this.searchQuery.listed
          ? [{ price: { greaterThan: '0' } }]
          : [],
        first: this.first,
        offset: (page - 1) * this.first,
      },
      result: (res) => {
        this.handleResult(res, loadDirection)
      }
    })
  }
```

File: components/rmrk/Collection/List/CollectionList.vue [hunk 3]
```diff
@@ -180,12 +180,11 @@ export default class CollectionList extends mixins(
...
     page: number,
-    loadDirection = 'down',
-    callback?: () => void
```
Comment (roiLeo) [inline components/rmrk/Collection/List/CollectionList.vue:186]: yee no more weird callback!

**Comment by Jarsen136** [comment]
will check it later

File: components/rmrk/Collection/List/CollectionList.vue (hunk 2 above)
Comment (Jarsen136) [reply components/rmrk/Collection/List/CollectionList.vue:183]: I think it could not work with smartQuery, because it could not figure out in which `loadDirection` should be loaded when `page` change

Comment (roiLeo) [reply components/rmrk/Collection/List/CollectionList.vue:183]: > SmartQuery will auto fetch data when `page` changes.

I was going to say it's the expected result since you change page url on scroll, tbh I don't really see the usefulness of having a direction

**Review by roiLeo — APPROVED** [review]
meging this since it's working, can't reproduce the bug

File: components/rmrk/Collection/List/CollectionList.vue (hunk 2 above)
Comment (Jarsen136) [reply components/rmrk/Collection/List/CollectionList.vue:183]: yes I change page url on scroll, but it's unnecessary to fetch data every time. 
It only need to get data when reach the top or bottom.

**Comment by roiLeo** [comment]
Pay 50

**Comment by Jarsen136** [comment]
It seems the bot is broken. 👀   @roiLeo
